### PR TITLE
[NUI] Support List property, load multi EXaml and fix svace issue

### PR DESCRIPTION
**Pull request by AdunFang**
### Description of Change ###

Fix SVACE issue.

### API Changes ###

 - ACR:

### CODE REVIEW

**Review by zhouleonlei — APPROVED** [review]
LGTM

**Review by elishateng — APPROVED** [review]
LGTM

**Review by AchoWang — APPROVED** [review]
Looks  good to me.

**Review by huayongxu — APPROVED** [review]
lgtm.

**Pull request merged**
