### PR TITLE
[NUI] Add TCs for NUI.Components.Devel.

### PR DESCRIPTION
**Pull request by AchoWang**
### Description of Change ###
Add TCs of FlexibleView and RecyclerView (Control).

### API Changes ###

 - ACR:

### CODE REVIEW

**Review by wb0716 — APPROVED** [review]
Good for me

**Review by elishateng — APPROVED** [review]
LGTM

**Review by dongsug-song — APPROVED** [review]
looks good to me

**Review by zhouleonlei — COMMENTED** [review]
LGTM

**Review by zg2nets — COMMENTED** [review]
lgtm

**Review by huayongxu — COMMENTED** [review]
lgtm

**Pull request merged**
