### PR TITLE
[NUI] Fix svace issue

### PR DESCRIPTION
**Pull request by zhouleonlei**
### Description of Change ###

Fix svace issue

### API Changes ###

 - ACR:

### CODE REVIEW

**Comment by xuelian-bai** [comment]
looks good to me

**Review by huayongxu — COMMENTED** [review]
lgtm

**Review by zg2nets — APPROVED** [review]
It's good！

**Review by elishateng — APPROVED** [review]
LGTM

**Review by wb0716 — APPROVED** [review]
Good for me

**Review by dongsug-song — APPROVED** [review]
looks good to me

**Review by xiaowei-guan — COMMENTED** [review]
LGTM

**Review by AchoWang — COMMENTED** [review]
Looks good to me.

**Pull request merged**
