### PR TITLE
[NUI] Fix build warning CS1064

### PR DESCRIPTION
**Pull request by tscholb**
https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1064
CA1064: Exceptions should be public

### API Changes ###

 - ACR:

### CODE REVIEW

**Review by dongsug-song — APPROVED** [review]
LGTM

**Comment by dongsug-song** [comment]
@tscholb 
Hello, could you resolve the conflicts above?
thank you.

**Comment by tscholb** [comment]
I upload this to new PR
https://github.com/Samsung/TizenFX/pull/2388

**Comment by dongsug-song** [comment]
the conflicts are resolved by https://github.com/Samsung/TizenFX/pull/2388
so being closed now.
thank you.

**Pull request closed without merging**
