### PR TITLE
[NUI] Rename functions, variables, etc related to policy decision.

### PR DESCRIPTION
**Pull request by huayongxu**
This patch is related to the patch at csharp-binder side:
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/257751/

### API Changes ###

 - ACR:

### CODE REVIEW

**Review by zg2nets — APPROVED** [review]
lgtm

**Comment by huiyueun** [comment]
Could you add '[NUI]' tag to title?

**Comment by huayongxu** [comment]
> Could you add '[NUI]' tag to title?

Done

**Review by rabbitfor — APPROVED** [review]

**Comment by rabbitfor** [comment]
Mr. Xu, could you also make same PR for the master branch?

**Pull request merged**
