### PR TITLE
[NUI] Change IsCreateByXaml to virtual

### PR DESCRIPTION
**Pull request by AdunFang**
### API Changes ###

 - ACR:

### CODE REVIEW

**Comment by xuelian-bai** [comment]
looks good to me

**Review by dongsug-song — APPROVED** [review]

**Review by huayongxu — APPROVED** [review]
lgtm

**Review by wb0716 — APPROVED** [review]
Good for me

**Review by AchoWang — APPROVED** [review]
Looks  good to me

**Review by wanchao-xu — COMMENTED** [review]
Looks good to me

**Review by elishateng — COMMENTED** [review]
LGTM

**Review by xiaowei-guan — COMMENTED** [review]
LGTM

**Review by zhouleonlei — COMMENTED** [review]
lgtm

**Pull request merged**
