### PR TITLE
[NUI] Use 'Container GetParent() for derived class' instead of Parent.

### PR DESCRIPTION
**Pull request by AchoWang**
### Description of Change ###
Parent was deprecated in API5 and  removed in API8, so use 'Container GetParent() for derived class' instead!

### API Changes ###

 - ACR:

### CODE REVIEW

**Review by AdunFang — APPROVED** [review]
It is OK.

**Review by XuWanchaoS — APPROVED** [review]
Looks good to me

**Review by xuelian-bai — APPROVED** [review]
looks good to me

**Review by zg2nets — APPROVED** [review]
it is good！

**Review by elishateng — APPROVED** [review]
LGTM

**Review by zhouleonlei — APPROVED** [review]
LGTM

**Review by zhouleonlei — APPROVED** [review]
LGTM

**Review by huiyueun — APPROVED** [review]

**Pull request merged**
