### PR TITLE
[NUI][API10] Add a WebView API for notifying orientation change.

### PR DESCRIPTION
**Pull request by huayongxu**
### Description of Change ###

Related patch at csharp binder:
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/305521/

### API Changes ###

 - ACR:

### CODE REVIEW

**Review by wanchao-xu — APPROVED** [review]
Looks good to me

**Review by wb0716 — APPROVED** [review]
Good for me

**Comment by zhouhao02** [comment]
LGTM

**Review by AchoWang — APPROVED** [review]
Looks good to me.

**Review by xiaowei-guan — APPROVED** [review]
LGTM

**Review by zg2nets — APPROVED** [review]
Good job~ thank you

**Review by hyue7 — APPROVED** [review]

**Review by dongsug-song — APPROVED** [review]
approved

**Pull request merged**
