### PR TITLE
[NUI] Add Transition(internal & public) TCs.

### PR DESCRIPTION
**Pull request by AchoWang**
### Description of Change ###
Add Transition(internal & public) TCs.

### API Changes ###

 - ACR:

### CODE REVIEW

**Review by elishateng — APPROVED** [review]
LGTM

**Review by huayongxu — APPROVED** [review]
lgtm

**Review by zhouleonlei — APPROVED** [review]
LGTM

**Review by AdunFang — APPROVED** [review]
It is OK.

**Review by zg2nets — APPROVED** [review]
looks good ！

**Review by dongsug-song — APPROVED** [review]
looks good to me

**Pull request merged**
