### PR TITLE
[NUI] Fix PointSizeTypeConverter error

### PR DESCRIPTION
**Pull request by elishateng**
### Description of Change ###

1. Fix PointSizeTypeConverter error

### API Changes ###

 - ACR:

### CODE REVIEW

**Review by AchoWang — APPROVED** [review]
Looks good to me.

**Review by huayongxu — APPROVED** [review]
lgtm

**Review by everLEEst — APPROVED** [review]
Thanks for fixing it!! Its my mistake.

**Review by dongsug-song — APPROVED** [review]
looks good to me

**Pull request merged**
