### PR TITLE
[Tts] Raise exception for screen reader off error from native library

### PR DESCRIPTION
**Pull request by stom-hwang**
Signed-off-by: Suyeon Hwang <stom.hwang@samsung.com>

### Description of Change ###

Raise proper exception for screen reader off error from native library.

### CODE REVIEW

**Review by psw0405 — APPROVED** [review]
lgtm

**Review by dyamylee — APPROVED** [review]
Looks good to me:)

**Review by imfine98 — APPROVED** [review]
LGTM

**Review by sungraejo — APPROVED** [review]
LGTM

**Pull request merged**
