### PR TITLE
[NUI] Fix issue if application info is null

### PR DESCRIPTION
**Pull request by elishateng**
### Description of Change ###

1. Fix issue if application info is null

### API Changes ###

 - ACR:

### CODE REVIEW

**Review by wb0716 — APPROVED** [review]
Good for me

**Review by zg2nets — APPROVED** [review]
lgtm

**Review by zhouleonlei — APPROVED** [review]
lgtm

**Review by xuelian-bai — APPROVED** [review]
looks good to me

**Review by huayongxu — APPROVED** [review]
lgtm

**Review by dongsug-song — APPROVED** [review]
looks good to me

**Review by AchoWang — COMMENTED** [review]
Looks good to me.

**Pull request merged**
