### PR TITLE
[NUI][NUI.Devel] Fix build errors of NUI.Devel.

### PR DESCRIPTION
**Pull request by AchoWang**
### Description of Change ###
Reason:
Did not implement interface member 'IBorderInterface.OnMoved(int, int).

Solution:
Implement the interface member.

### API Changes ###

 - ACR:

### CODE REVIEW

**Review by wb0716 — APPROVED** [review]
Good for me

**Comment by xuelian-bai** [comment]
looks good to me

**Review by zg2nets — APPROVED** [review]
lgtm

**Review by huayongxu — APPROVED** [review]
lgtm

**Review by AdunFang — APPROVED** [review]
It is OK.

**Review by everLEEst — APPROVED** [review]
LGTM. thank you.
if we want to avoid further update on version 10,
how about using * such as 10.0.0.*?

**Comment by AchoWang** [comment]
> LGTM. thank you. if we want to avoid further update on version 10, how about using * such as 10.0.0.*?

Thanks for your comment.
Done!

**Pull request merged**
