### PR TITLE
[NUI] Fix crash when background color of webview is set.

### PR DESCRIPTION
**Pull request by huayongxu**
### Description of Change ###

This patch is to rename some functions in WebContext too.

### API Changes ###

 - ACR:

### CODE REVIEW

**Review by zg2nets — APPROVED** [review]
looks good！

**Review by rabbitfor — COMMENTED** [review]
It seems that this patch is including not only crash fix but also renaming WebContext APIs.
Since I already have reported to VD about out 6.5 API list so I will review it tomorrow if it is ok.

**Comment by rabbitfor** [comment]
Could you rebase the patch? The base branch has been reset.

**Comment by huayongxu** [comment]
> Could you rebase the patch? The base branch has been reset.

Done.

**Comment by huayongxu** [comment]
> It seems that this patch is including not only crash fix but also renaming WebContext APIs.
> Since I already have reported to VD about out 6.5 API list so I will review it tomorrow if it is ok.

Old APIs are reserved still in the latest patch.

**Review by rabbitfor — APPROVED** [review]
LGTM

**Pull request merged**
