### PR TITLE
[NUI] Add manual test for webview.

### PR DESCRIPTION
**Pull request by huayongxu**
### API Changes ###

 - ACR:

### CODE REVIEW

**Review by elishateng — APPROVED** [review]
LGTM

**Review by xiaowei-guan — APPROVED** [review]
LGTM

**Review by wanchao-xu — APPROVED** [review]
Looks good to me

**Review by xuelian-bai — APPROVED** [review]
looks good to me

**Review by wb0716 — APPROVED** [review]
Good for me

**Review by hyue7 — APPROVED** [review]
looks good

**Review by xuelian-bai — APPROVED** [review]
looks good to me

**Review by dongsug-song — APPROVED** [review]
apporved

**Pull request merged**
