### PR TITLE
[NUI] Fixed svace issue for API8

### PR DESCRIPTION
**Pull request by zhouleonlei**
### Description of Change ###
 Fixed svace issue for API8

### CODE REVIEW

**Review by AdunFang — APPROVED** [review]
It is OK.

**Review by AchoWang — APPROVED** [review]
Looks good to me.

**Review by zg2nets — APPROVED** [review]
Looks Good

**Review by huayongxu — APPROVED** [review]
looks good to me.

**Review by elishateng — APPROVED** [review]
LGTM

**Pull request merged**
