### PR TITLE
[NUI] Rename functions, variables, etc related to policy decision.

### PR DESCRIPTION
**Pull request by huayongxu**
### Description of Change ###

Originally new window policy is not needed, actually response policy is needed.
This patch is to rename functions related to policy decision.
The patch related to csharp-binder :
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/257751/

### API Changes ###

 - ACR:

### CODE REVIEW

**Review by zg2nets — APPROVED** [review]
lgtm

**Comment by rabbitfor** [comment]
Please add `[NUI]` prefix in the commit message

**Comment by dongsug-song** [comment]
@huayongxu 
Hello, 
Could you write the description even briefly?
Could you update dali-csharp-binder's patch on this PR? and as you know, dali-csharp-binder patch should be merged prior to this PR. Otherwise there can be a runtime exception which blocks the TizenFX release by auto test hurdle.

**Comment by huayongxu** [comment]
> @huayongxu
> Hello,
> Could you write the description even briefly?
> Could you update dali-csharp-binder's patch on this PR? and as you know, dali-csharp-binder patch should be merged prior to this PR. Otherwise there can be a runtime exception which blocks the TizenFX release by auto test hurdle.

Done.

**Review by dongsug-song — APPROVED** [review]
looks good to me

**Pull request merged**
