### PR TITLE
Remove unused reference 

### PR DESCRIPTION
**Pull request by elishateng**
### Description of Change ###

1. Remove unused reference 

### API Changes ###

 - ACR:

### CODE REVIEW

**Review by xiaowei-guan — APPROVED** [review]
LGTM

**Review by AchoWang — APPROVED** [review]
Looks good to me.

**Review by zg2nets — APPROVED** [review]
lgtm

**Review by wanchao-xu — APPROVED** [review]
Looks good to me

**Review by xuelian-bai — APPROVED** [review]
looks good to me

**Review by wb0716 — APPROVED** [review]
Good for me

**Review by dongsug-song — APPROVED** [review]
apporved

**Pull request merged**
