### PR TITLE
[NUI] Add XAML TCs

### PR DESCRIPTION
**Pull request by zhouleonlei**
### Description of Change ###
Add XAML TCs

### API Changes ###

 - ACR:

### CODE REVIEW

**Review by huayongxu — APPROVED** [review]
lgtm

**Review by AdunFang — APPROVED** [review]
It is OK.

**Review by zg2nets — APPROVED** [review]
lgtm

**Review by elishateng — APPROVED** [review]
LGTM

**Review by dongsug-song — APPROVED** [review]
looks good to me

**Pull request merged**
