### PR TITLE
[NUI.WindowSystem] Introduce the new KVM service feature

### PR DESCRIPTION
**Pull request by juns-kim**
## Description of Change ##
Introduce the new KVM service feature and Add tests for the feature

The KVM service is software KVM(Keyboard Video Mouse) service that enable to control the other platform (such as android, windows...) or controlled by other platform like as Synergy or Barrier.

please refer the below link
https://code.sec.samsung.net/confluence/display/WSI/Multi+Platform+CnP+DnD

### Internal APIs ###
Added:
 - KVMService class
 - public void PerformDrop()
 - public void SetSecondarySelction()
 - public void UnetSecondarySelction()

### CODE REVIEW

**Comment by dongsug-song** [comment]
@juns-kim 
Hello,
if you don't mind, could you explain more about the KVM?
if any confluence guide is there, please let us know the link?
thank you.

**Comment by JoogabYun** [comment]
@juns-kim 
해당 패치 업데이트 부탁드립니다. MCF app 개발시 별도의 dll설치를 안하도록 이 패치가 포함되어야 할 것 같습니다.

**Comment by juns-kim** [comment]
@dongsug-song 
The KVM service is software KVM(Keyboard Video Mouse) service that enable to control the other platform (such as android, windows...) or controlled by other platform like as Synergy or Barrier.

please refer the below link
https://code.sec.samsung.net/confluence/display/WSI/Multi+Platform+CnP+DnD

**Comment by JoogabYun** [comment]
@juns-kim 
적어주신 이런 내용이 커멘트 말고 Description란에 포함되면 좋겠습니다.

The KVM service is software KVM(Keyboard Video Mouse) service that enable to control the other platform (such as android, windows...) or controlled by other platform like as Synergy or Barrier.

그리고 SetSecondarySelction  api 만 보면  secondary selection이 무엇을 의미하는지 잘 모르겠습니다. 
이해할 수 있게 조금만 더 구체적으로 설명을 달아주시면 좋겠습니다.

**Comment by JoogabYun** [comment]
아 SetSecondarySelction 이건 보조창을 선택하는 거군요 이해했습니다.
"Requests to set KVM window as secondary selection window."

**Review by JoogabYun — APPROVED** [review]

**Review by dongsug-song — COMMENTED** [review]
approved

**Pull request merged**
