### PR TITLE
[NUI][Xaml] Support nest type in Xaml

### PR DESCRIPTION
**Pull request by AdunFang**
### Description of Change ###

Support nest type in xaml

Sample:

`  <l:XamlPage-TestView Size="300,200" BackgroundColor="Red"/>`

C# code:

```
    public partial class XamlPage : View
    {
        public class TestView : View
        {

        }
        ......
    }
```

### API Changes ###

 - ACR:

### CODE REVIEW

**Review by wb0716 — APPROVED** [review]
Good for me

**Review by xiaowei-guan — APPROVED** [review]
LGTM

**Review by zhouleonlei — APPROVED** [review]
LGTM

**Review by elishateng — APPROVED** [review]
LGTM

**Review by AchoWang — APPROVED** [review]
Looks good to me.

**Review by dongsug-song — APPROVED** [review]
looks good to me

**Pull request merged**
