### PR TITLE
[NUI] Fix build errors for NUISample

### PR DESCRIPTION
**Pull request by zhouleonlei**
### Description of Change ###
 Fix build errors for NUISample

### API Changes ###

 - ACR:

### CODE REVIEW

**Review by AchoWang — APPROVED** [review]
LGTM

**Review by AdunFang — APPROVED** [review]
It is OK

**Review by zg2nets — APPROVED** [review]
looks good to me

**Review by huayongxu — APPROVED** [review]
lgtm

**Review by rabbitfor — APPROVED** [review]
LGTM

**Pull request merged**
