### PR TITLE
[NUI] Add Template(public) TCs.

### PR DESCRIPTION
**Pull request by AchoWang**
### Description of Change ###
Add public\Template\ TCs.

### API Changes ###

 - ACR:

### CODE REVIEW

**Review by zhouleonlei — APPROVED** [review]
LGTM

**Review by elishateng — APPROVED** [review]
LGTM

**Review by AdunFang — APPROVED** [review]
It is OK.

**Review by dongsug-song — APPROVED** [review]
looks good to me

**Pull request merged**
