### PR TITLE
[NUI] Add GetBrightness()

### PR DESCRIPTION
**Pull request by JoogabYun**
### API Changes ###

 - ACR:

### CODE REVIEW

**Comment by dongsug-song** [comment]
could you share the link of the dali-csharp-binder patch related?

**Comment by JoogabYun** [comment]
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-adaptor/+/260567/
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/260569/
아직 리뷰 중입니다.

**Review by hinohie — APPROVED** [review]
Looks good to me. But need to merge dali csharp binder before merge it.

**Comment by JoogabYun** [comment]
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-adaptor/+/260567/
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/260569/
관련 패치 모두 머지되었습니다. 

리뷰 및 머지 부탁드립니다.

**Review by dongsug-song — APPROVED** [review]
looks good to me

**Pull request merged**
