### PR TITLE
[XamlBuild] Correct the code format

### PR DESCRIPTION
**Pull request by AdunFang**
### API Changes ###

 - ACR:

### CODE REVIEW

**Review by elishateng — APPROVED** [review]
LGTM

**Comment by xuelian-bai** [comment]
looks good to me

**Review by zhouleonlei — APPROVED** [review]
lgtm

**Review by AchoWang — APPROVED** [review]
Looks good to me.

**Review by xiaowei-guan — APPROVED** [review]
LGTM

**Review by zg2nets — APPROVED** [review]
lgtm

**Review by everLEEst — APPROVED** [review]
cool.

**Pull request merged**
