### PR TITLE
[NUI] Refactor dispose pattern to reduce duplication

### PR DESCRIPTION
**Pull request by elishateng**
### API Changes ###

 - ACR: http://suprem.sec.samsung.net/jira/browse/TCSACR-291

### CODE REVIEW

**Comment by dongsug-song** [comment]
@elishateng 
Hello,
"ACR Required" tag was attached.
please update the comment with TCSACR link, otherwise this PR can not be merged.
thank you.

**Comment by elishateng** [comment]
> @elishateng
> Hello,
> "ACR Required" tag was attached.
> please update the comment with TCSACR link, otherwise this PR can not be merged.
> thank you.

Hello, Mr. SSong, 
I have created a ACR (http://suprem.sec.samsung.net/jira/browse/TCSACR-291) for this.

**Comment by dongsug-song** [comment]
@elishateng 
Hello,
is there a certain reason to open "ReleaseSwigCPtr()" method?
I don't think it is needed for users.
Why don't we make them as hidden or internal?
Also, the this kinds of words such as "swig", "IntPtr", "CPtr", it is recommended not to show in public.
what do you think about? (I don't think ACR is required...)
please let me get your idea.
thank you.

**Comment by elishateng** [comment]
> @elishateng
> Hello,
> is there a certain reason to open "ReleaseSwigCPtr()" method?
> I don't think it is needed for users.
> Why don't we make them as hidden or internal?
> Also, the this kinds of words such as "swig", "IntPtr", "CPtr", it is recommended not to show in public.
> what do you think about? (I don't think ACR is required...)
> please let me get your idea.
> thank you.

Hello, Mr. SSong, I think you're right. We don't need to make them as public. I'll make them as hidden.

**Comment by dongsug-song** [comment]
@elishateng 
Hello,
TizenAPI-Bot tells the following APIs are violating ABI compatibility.
it needs to make them as hidden APIs.
also please update the TCSACR. (this ACR and patch should be matched)
please check the below.
thank you.

+ /// <since_tizen> 6 </since_tizen>
+ System.Boolean Tizen.NUI.Disposable::swigCMemOwn

- /// <since_tizen> 3 </since_tizen>
- System.Boolean Tizen.NUI.BaseComponents.TableView/CellPosition::swigCMemOwn

- /// <since_tizen> 3 </since_tizen>
- System.Boolean Tizen.NUI.RelativeVector4::swigCMemOwn

- /// <since_tizen> 6 </since_tizen>
- System.Void Tizen.NUI.Disposable::.ctor()

- /// <since_tizen> 3 </since_tizen>
- System.Void Tizen.NUI.Animatable::Dispose(Tizen.NUI.DisposeTypes)

- /// <since_tizen> 3 </since_tizen>
- System.Void Tizen.NUI.BaseComponents.TextLabel::Dispose(Tizen.NUI.DisposeTypes)

- /// <since_tizen> 4 </since_tizen>
- System.Void Tizen.NUI.WatchTime::Dispose(Tizen.NUI.DisposeTypes)


- /// <since_tizen> 3 </since_tizen>
- System.Void Tizen.NUI.Degree::Dispose(Tizen.NUI.DisposeTypes)

- /// <since_tizen> 3 </since_tizen>
- System.Void Tizen.NUI.Texture::Dispose(Tizen.NUI.DisposeTypes)

- /// <since_tizen> 3 </since_tizen>
- System.Void Tizen.NUI.PropertyMap::Dispose(Tizen.NUI.DisposeTypes)

- /// <since_tizen> 3 </since_tizen>
- System.Void Tizen.NUI.Rotation::Dispose(Tizen.NUI.DisposeTypes)

- /// <since_tizen> 3 </since_tizen>
- System.Void Tizen.NUI.Position2D::Dispose(Tizen.NUI.DisposeTypes)

- /// <since_tizen> 3 </since_tizen>
- System.Void Tizen.NUI.Size2D::Dispose(Tizen.NUI.DisposeTypes)

- /// <since_tizen> 3 </since_tizen>
- System.Void Tizen.NUI.Renderer::Dispose(Tizen.NUI.DisposeTypes)

- /// <since_tizen> 3 </since_tizen>
- System.Void Tizen.NUI.PropertyArray::Dispose(Tizen.NUI.DisposeTypes)

- /// <since_tizen> 3 </since_tizen>
- System.Void Tizen.NUI.TypeInfo::Dispose(Tizen.NUI.DisposeTypes)

- /// <since_tizen> 3 </since_tizen>
- System.Void Tizen.NUI.BaseComponents.TableView/CellPosition::Dispose(Tizen.NUI.DisposeTypes)

- /// <since_tizen> 3 </since_tizen>
- System.Boolean Tizen.NUI.AlphaFunction::swigCMemOwn

- /// <since_tizen> 3 </since_tizen>
- System.Boolean Tizen.NUI.PropertyValue::swigCMemOwn

- /// <since_tizen> 3 </since_tizen>
- System.Boolean Tizen.NUI.Radian::swigCMemOwn

- /// <since_tizen> 3 </since_tizen>
- System.Void Tizen.NUI.PaddingType::Dispose(Tizen.NUI.DisposeTypes)

- /// <since_tizen> 4 </since_tizen>
- System.Boolean Tizen.NUI.WatchTime::swigCMemOwn

- /// <since_tizen> 3 </since_tizen>
- System.Boolean Tizen.NUI.Position2D::swigCMemOwn

- /// <since_tizen> 3 </since_tizen>
- System.Void Tizen.NUI.ViewWrapper::Dispose(Tizen.NUI.DisposeTypes)

- /// <since_tizen> 3 </since_tizen>
- System.Void Tizen.NUI.WidgetViewManager::Dispose(Tizen.NUI.DisposeTypes)

- /// <since_tizen> 3 </since_tizen>
- System.Boolean Tizen.NUI.PropertyKey::swigCMemOwn

- /// <since_tizen> 3 </since_tizen>
- System.Void Tizen.NUI.PropertyBuffer::Dispose(Tizen.NUI.DisposeTypes)

- /// <since_tizen> 3 </since_tizen>
- System.Void Tizen.NUI.RelayoutContainer::Dispose(Tizen.NUI.DisposeTypes)

- /// <since_tizen> 3 </since_tizen>
- System.Boolean Tizen.NUI.Vector2::swigCMemOwn

- /// <since_tizen> 3 </since_tizen>
- System.Void Tizen.NUI.BaseComponents.FlexContainer::Dispose(Tizen.NUI.DisposeTypes)

- /// <since_tizen> 3 </since_tizen>
- System.Void Tizen.NUI.TapGesture::Dispose(Tizen.NUI.DisposeTypes)

- /// <since_tizen> 3 </since_tizen>
- System.Boolean Tizen.NUI.Key::swigCMemOwn

- /// <since_tizen> 3 </since_tizen>
- System.Void Tizen.NUI.KeyFrames::Dispose(Tizen.NUI.DisposeTypes)

- /// <since_tizen> 4 </since_tizen>
- System.Void Tizen.NUI.PropertyCondition::Dispose(Tizen.NUI.DisposeTypes)

- /// <since_tizen> 3 </since_tizen>
- System.Void Tizen.NUI.Vector3::Dispose(Tizen.NUI.DisposeTypes)

- /// <since_tizen> 3 </since_tizen>
- System.Boolean Tizen.NUI.Vector4::swigCMemOwn

- /// <since_tizen> 3 </since_tizen>
- System.Boolean Tizen.NUI.Vector3::swigCMemOwn

- /// <since_tizen> 3 </since_tizen>
- System.Boolean Tizen.NUI.Position::swigCMemOwn

- /// <since_tizen> 5 </since_tizen>
- System.Void Tizen.NUI.Size::Dispose(Tizen.NUI.DisposeTypes)

- /// <since_tizen> 3 </since_tizen>
- System.Void Tizen.NUI.PanGesture::Dispose(Tizen.NUI.DisposeTypes)

- /// <since_tizen> 3 </since_tizen>
- System.Void Tizen.NUI.Vector2::Dispose(Tizen.NUI.DisposeTypes)

- /// <since_tizen> 3 </since_tizen>
- System.Void Tizen.NUI.Radian::Dispose(Tizen.NUI.DisposeTypes)

- /// <since_tizen> 3 </since_tizen>
- System.Void Tizen.NUI.Sampler::Dispose(Tizen.NUI.DisposeTypes)

- /// <since_tizen> 3 </since_tizen>
- System.Void Tizen.NUI.Geometry::Dispose(Tizen.NUI.DisposeTypes)

- /// <since_tizen> 3 </since_tizen>
- System.Void Tizen.NUI.AlphaFunction::Dispose(Tizen.NUI.DisposeTypes)

- /// <since_tizen> 3 </since_tizen>
- System.Boolean Tizen.NUI.Color::swigCMemOwn

- /// <since_tizen> 3 </since_tizen>
- System.Boolean Tizen.NUI.Size2D::swigCMemOwn

- /// <since_tizen> 3 </since_tizen>
- System.Void Tizen.NUI.Rectangle::Dispose(Tizen.NUI.DisposeTypes)

- /// <since_tizen> 3 </since_tizen>
- System.Boolean Tizen.NUI.RelativeVector3::swigCMemOwn

- /// <since_tizen> 3 </since_tizen>
- System.Void Tizen.NUI.Path::Dispose(Tizen.NUI.DisposeTypes)

- /// <since_tizen> 3 </since_tizen>
- System.Boolean Tizen.NUI.RelayoutContainer::swigCMemOwn

- /// <since_tizen> 3 </since_tizen>
- System.Void Tizen.NUI.RelativeVector2::Dispose(Tizen.NUI.DisposeTypes)

- /// <since_tizen> 3 </since_tizen>
- System.Void Tizen.NUI.ScrollViewEffect::Dispose(Tizen.NUI.DisposeTypes)

- /// <since_tizen> 3 </since_tizen>
- System.Void Tizen.NUI.Layer::Dispose(Tizen.NUI.DisposeTypes)

- /// <since_tizen> 3 </since_tizen>
- System.Void Tizen.NUI.TransitionData::Dispose(Tizen.NUI.DisposeTypes)

- /// <since_tizen> 3 </since_tizen>
- System.Void Tizen.NUI.PropertyValue::Dispose(Tizen.NUI.DisposeTypes)

- /// <since_tizen> 3 </since_tizen>
- System.Boolean Tizen.NUI.Rotation::swigCMemOwn

- /// <since_tizen> 3 </since_tizen>
- System.Void Tizen.NUI.Shader::Dispose(Tizen.NUI.DisposeTypes)

- /// <since_tizen> 3 </since_tizen>
- System.Void Tizen.NUI.Key::Dispose(Tizen.NUI.DisposeTypes)

- /// <since_tizen> 3 </since_tizen>
- System.Void Tizen.NUI.Wheel::Dispose(Tizen.NUI.DisposeTypes)

- /// <since_tizen> 4 </since_tizen>
- System.Void Tizen.NUI.Container::Dispose(Tizen.NUI.DisposeTypes)

- /// <since_tizen> 3 </since_tizen>
- System.Void Tizen.NUI.Hover::Dispose(Tizen.NUI.DisposeTypes)

- /// <since_tizen> 4 </since_tizen>
- System.Void Tizen.NUI.Extents::Dispose(Tizen.NUI.DisposeTypes)

- /// <since_tizen> 3 </since_tizen>
- System.Void Tizen.NUI.Gesture::Dispose(Tizen.NUI.DisposeTypes)

- /// <since_tizen> 3 </since_tizen>
- System.Void Tizen.NUI.Position::Dispose(Tizen.NUI.DisposeTypes)

- /// <since_tizen> 3 </since_tizen>
- System.Boolean Tizen.NUI.Degree::swigCMemOwn

- /// <since_tizen> 4 </since_tizen>
- System.Void Tizen.NUI.Adaptor::Dispose(Tizen.NUI.DisposeTypes)

- /// <since_tizen> 4 </since_tizen>
- System.Void Tizen.NUI.Widget::Dispose(Tizen.NUI.DisposeTypes)

- /// <since_tizen> 4 </since_tizen>
- System.Boolean Tizen.NUI.Extents::swigCMemOwn

- /// <since_tizen> 3 </since_tizen>
- System.Boolean Tizen.NUI.RelativeVector2::swigCMemOwn

- /// <since_tizen> 3 </since_tizen>
- System.Void Tizen.NUI.BaseComponents.TableView::Dispose(Tizen.NUI.DisposeTypes)

- /// <since_tizen> 3 </since_tizen>
- System.Boolean Tizen.NUI.Rectangle::swigCMemOwn

- /// <since_tizen> 3 </since_tizen>
- System.Void Tizen.NUI.RelativeVector4::Dispose(Tizen.NUI.DisposeTypes)

- /// <since_tizen> 3 </since_tizen>
- System.Void Tizen.NUI.VisualBase::Dispose(Tizen.NUI.DisposeTypes)

- /// <since_tizen> 3 </since_tizen>
- System.Boolean Tizen.NUI.Hover::swigCMemOwn

- /// <since_tizen> 3 </since_tizen>
- System.Void Tizen.NUI.Touch::Dispose(Tizen.NUI.DisposeTypes)

- /// <since_tizen> 3 </since_tizen>
- System.Boolean Tizen.NUI.Wheel::swigCMemOwn

- /// <since_tizen> 3 </since_tizen>
- System.Void Tizen.NUI.RelativeVector3::Dispose(Tizen.NUI.DisposeTypes)

- /// <since_tizen> 3 </since_tizen>
- System.Boolean Tizen.NUI.PropertyArray::swigCMemOwn

- /// <since_tizen> 3 </since_tizen>
- System.Void Tizen.NUI.PropertyKey::Dispose(Tizen.NUI.DisposeTypes)

- /// <since_tizen> 4 </since_tizen>
- System.Boolean Tizen.NUI.Adaptor::swigCMemOwn

- /// <since_tizen> 3 </since_tizen>
- System.Void Tizen.NUI.Color::Dispose(Tizen.NUI.DisposeTypes)

- /// <since_tizen> 3 </since_tizen>
- System.Boolean Tizen.NUI.PaddingType::swigCMemOwn

- /// <since_tizen> 3 </since_tizen>
- System.Void Tizen.NUI.Vector4::Dispose(Tizen.NUI.DisposeTypes)

- /// <since_tizen> 3 </since_tizen>
- System.Void Tizen.NUI.TextureSet::Dispose(Tizen.NUI.DisposeTypes)

- /// <since_tizen> 3 </since_tizen>
- System.Boolean Tizen.NUI.PropertyMap::swigCMemOwn

- /// <since_tizen> 5 </since_tizen>
- System.Boolean Tizen.NUI.Size::swigCMemOwn

- /// <since_tizen> 3 </since_tizen>
- System.Void Tizen.NUI.PinchGesture::Dispose(Tizen.NUI.DisposeTypes)

- /// <since_tizen> 3 </since_tizen>
- System.Boolean Tizen.NUI.Gesture::swigCMemOwn

- /// <since_tizen> 3 </since_tizen>
- System.Void Tizen.NUI.LongPressGesture::Dispose(Tizen.NUI.DisposeTypes)

- /// <since_tizen> 4 </since_tizen>
- System.Void Tizen.NUI.PropertyNotification::Dispose(Tizen.NUI.DisposeTypes)

**Comment by elishateng** [comment]
> @elishateng
> Hello,
> TizenAPI-Bot tells the following APIs are violating ABI compatibility.
> it needs to make them as hidden APIs.
> also please update the TCSACR. (this ACR and patch should be matched)
> please check the below.
> thank you.
> 
> * /// <since_tizen> 6 </since_tizen>
> * System.Boolean Tizen.NUI.Disposable::swigCMemOwn
> 
> * /// <since_tizen> 3 </since_tizen>
> * System.Boolean Tizen.NUI.BaseComponents.TableView/CellPosition::swigCMemOwn
> * /// <since_tizen> 3 </since_tizen>
> * System.Boolean Tizen.NUI.RelativeVector4::swigCMemOwn
> * /// <since_tizen> 6 </since_tizen>
> * System.Void Tizen.NUI.Disposable::.ctor()
> * /// <since_tizen> 3 </since_tizen>
> * System.Void Tizen.NUI.Animatable::Dispose(Tizen.NUI.DisposeTypes)
> * /// <since_tizen> 3 </since_tizen>
> * System.Void Tizen.NUI.BaseComponents.TextLabel::Dispose(Tizen.NUI.DisposeTypes)
> * /// <since_tizen> 4 </since_tizen>
> * System.Void Tizen.NUI.WatchTime::Dispose(Tizen.NUI.DisposeTypes)
> * /// <since_tizen> 3 </since_tizen>
> * System.Void Tizen.NUI.Degree::Dispose(Tizen.NUI.DisposeTypes)
> * /// <since_tizen> 3 </since_tizen>
> * System.Void Tizen.NUI.Texture::Dispose(Tizen.NUI.DisposeTypes)
> * /// <since_tizen> 3 </since_tizen>
> * System.Void Tizen.NUI.PropertyMap::Dispose(Tizen.NUI.DisposeTypes)
> * /// <since_tizen> 3 </since_tizen>
> * System.Void Tizen.NUI.Rotation::Dispose(Tizen.NUI.DisposeTypes)
> * /// <since_tizen> 3 </since_tizen>
> * System.Void Tizen.NUI.Position2D::Dispose(Tizen.NUI.DisposeTypes)
> * /// <since_tizen> 3 </since_tizen>
> * System.Void Tizen.NUI.Size2D::Dispose(Tizen.NUI.DisposeTypes)
> * /// <since_tizen> 3 </since_tizen>
> * System.Void Tizen.NUI.Renderer::Dispose(Tizen.NUI.DisposeTypes)
> * /// <since_tizen> 3 </since_tizen>
> * System.Void Tizen.NUI.PropertyArray::Dispose(Tizen.NUI.DisposeTypes)
> * /// <since_tizen> 3 </since_tizen>
> * System.Void Tizen.NUI.TypeInfo::Dispose(Tizen.NUI.DisposeTypes)
> * /// <since_tizen> 3 </since_tizen>
> * System.Void Tizen.NUI.BaseComponents.TableView/CellPosition::Dispose(Tizen.NUI.DisposeTypes)
> * /// <since_tizen> 3 </since_tizen>
> * System.Boolean Tizen.NUI.AlphaFunction::swigCMemOwn
> * /// <since_tizen> 3 </since_tizen>
> * System.Boolean Tizen.NUI.PropertyValue::swigCMemOwn
> * /// <since_tizen> 3 </since_tizen>
> * System.Boolean Tizen.NUI.Radian::swigCMemOwn
> * /// <since_tizen> 3 </since_tizen>
> * System.Void Tizen.NUI.PaddingType::Dispose(Tizen.NUI.DisposeTypes)
> * /// <since_tizen> 4 </since_tizen>
> * System.Boolean Tizen.NUI.WatchTime::swigCMemOwn
> * /// <since_tizen> 3 </since_tizen>
> * System.Boolean Tizen.NUI.Position2D::swigCMemOwn
> * /// <since_tizen> 3 </since_tizen>
> * System.Void Tizen.NUI.ViewWrapper::Dispose(Tizen.NUI.DisposeTypes)
> * /// <since_tizen> 3 </since_tizen>
> * System.Void Tizen.NUI.WidgetViewManager::Dispose(Tizen.NUI.DisposeTypes)
> * /// <since_tizen> 3 </since_tizen>
> * System.Boolean Tizen.NUI.PropertyKey::swigCMemOwn
> * /// <since_tizen> 3 </since_tizen>
> * System.Void Tizen.NUI.PropertyBuffer::Dispose(Tizen.NUI.DisposeTypes)
> * /// <since_tizen> 3 </since_tizen>
> * System.Void Tizen.NUI.RelayoutContainer::Dispose(Tizen.NUI.DisposeTypes)
> * /// <since_tizen> 3 </since_tizen>
> * System.Boolean Tizen.NUI.Vector2::swigCMemOwn
> * /// <since_tizen> 3 </since_tizen>
> * System.Void Tizen.NUI.BaseComponents.FlexContainer::Dispose(Tizen.NUI.DisposeTypes)
> * /// <since_tizen> 3 </since_tizen>
> * System.Void Tizen.NUI.TapGesture::Dispose(Tizen.NUI.DisposeTypes)
> * /// <since_tizen> 3 </since_tizen>
> * System.Boolean Tizen.NUI.Key::swigCMemOwn
> * /// <since_tizen> 3 </since_tizen>
> * System.Void Tizen.NUI.KeyFrames::Dispose(Tizen.NUI.DisposeTypes)
> * /// <since_tizen> 4 </since_tizen>
> * System.Void Tizen.NUI.PropertyCondition::Dispose(Tizen.NUI.DisposeTypes)
> * /// <since_tizen> 3 </since_tizen>
> * System.Void Tizen.NUI.Vector3::Dispose(Tizen.NUI.DisposeTypes)
> * /// <since_tizen> 3 </since_tizen>
> * System.Boolean Tizen.NUI.Vector4::swigCMemOwn
> * /// <since_tizen> 3 </since_tizen>
> * System.Boolean Tizen.NUI.Vector3::swigCMemOwn
> * /// <since_tizen> 3 </since_tizen>
> * System.Boolean Tizen.NUI.Position::swigCMemOwn
> * /// <since_tizen> 5 </since_tizen>
> * System.Void Tizen.NUI.Size::Dispose(Tizen.NUI.DisposeTypes)
> * /// <since_tizen> 3 </since_tizen>
> * System.Void Tizen.NUI.PanGesture::Dispose(Tizen.NUI.DisposeTypes)
> * /// <since_tizen> 3 </since_tizen>
> * System.Void Tizen.NUI.Vector2::Dispose(Tizen.NUI.DisposeTypes)
> * /// <since_tizen> 3 </since_tizen>
> * System.Void Tizen.NUI.Radian::Dispose(Tizen.NUI.DisposeTypes)
> * /// <since_tizen> 3 </since_tizen>
> * System.Void Tizen.NUI.Sampler::Dispose(Tizen.NUI.DisposeTypes)
> * /// <since_tizen> 3 </since_tizen>
> * System.Void Tizen.NUI.Geometry::Dispose(Tizen.NUI.DisposeTypes)
> * /// <since_tizen> 3 </since_tizen>
> * System.Void Tizen.NUI.AlphaFunction::Dispose(Tizen.NUI.DisposeTypes)
> * /// <since_tizen> 3 </since_tizen>
> * System.Boolean Tizen.NUI.Color::swigCMemOwn
> * /// <since_tizen> 3 </since_tizen>
> * System.Boolean Tizen.NUI.Size2D::swigCMemOwn
> * /// <since_tizen> 3 </since_tizen>
> * System.Void Tizen.NUI.Rectangle::Dispose(Tizen.NUI.DisposeTypes)
> * /// <since_tizen> 3 </since_tizen>
> * System.Boolean Tizen.NUI.RelativeVector3::swigCMemOwn
> * /// <since_tizen> 3 </since_tizen>
> * System.Void Tizen.NUI.Path::Dispose(Tizen.NUI.DisposeTypes)
> * /// <since_tizen> 3 </since_tizen>
> * System.Boolean Tizen.NUI.RelayoutContainer::swigCMemOwn
> * /// <since_tizen> 3 </since_tizen>
> * System.Void Tizen.NUI.RelativeVector2::Dispose(Tizen.NUI.DisposeTypes)
> * /// <since_tizen> 3 </since_tizen>
> * System.Void Tizen.NUI.ScrollViewEffect::Dispose(Tizen.NUI.DisposeTypes)
> * /// <since_tizen> 3 </since_tizen>
> * System.Void Tizen.NUI.Layer::Dispose(Tizen.NUI.DisposeTypes)
> * /// <since_tizen> 3 </since_tizen>
> * System.Void Tizen.NUI.TransitionData::Dispose(Tizen.NUI.DisposeTypes)
> * /// <since_tizen> 3 </since_tizen>
> * System.Void Tizen.NUI.PropertyValue::Dispose(Tizen.NUI.DisposeTypes)
> * /// <since_tizen> 3 </since_tizen>
> * System.Boolean Tizen.NUI.Rotation::swigCMemOwn
> * /// <since_tizen> 3 </since_tizen>
> * System.Void Tizen.NUI.Shader::Dispose(Tizen.NUI.DisposeTypes)
> * /// <since_tizen> 3 </since_tizen>
> * System.Void Tizen.NUI.Key::Dispose(Tizen.NUI.DisposeTypes)
> * /// <since_tizen> 3 </since_tizen>
> * System.Void Tizen.NUI.Wheel::Dispose(Tizen.NUI.DisposeTypes)
> * /// <since_tizen> 4 </since_tizen>
> * System.Void Tizen.NUI.Container::Dispose(Tizen.NUI.DisposeTypes)
> * /// <since_tizen> 3 </since_tizen>
> * System.Void Tizen.NUI.Hover::Dispose(Tizen.NUI.DisposeTypes)
> * /// <since_tizen> 4 </since_tizen>
> * System.Void Tizen.NUI.Extents::Dispose(Tizen.NUI.DisposeTypes)
> * /// <since_tizen> 3 </since_tizen>
> * System.Void Tizen.NUI.Gesture::Dispose(Tizen.NUI.DisposeTypes)
> * /// <since_tizen> 3 </since_tizen>
> * System.Void Tizen.NUI.Position::Dispose(Tizen.NUI.DisposeTypes)
> * /// <since_tizen> 3 </since_tizen>
> * System.Boolean Tizen.NUI.Degree::swigCMemOwn
> * /// <since_tizen> 4 </since_tizen>
> * System.Void Tizen.NUI.Adaptor::Dispose(Tizen.NUI.DisposeTypes)
> * /// <since_tizen> 4 </since_tizen>
> * System.Void Tizen.NUI.Widget::Dispose(Tizen.NUI.DisposeTypes)
> * /// <since_tizen> 4 </since_tizen>
> * System.Boolean Tizen.NUI.Extents::swigCMemOwn
> * /// <since_tizen> 3 </since_tizen>
> * System.Boolean Tizen.NUI.RelativeVector2::swigCMemOwn
> * /// <since_tizen> 3 </since_tizen>
> * System.Void Tizen.NUI.BaseComponents.TableView::Dispose(Tizen.NUI.DisposeTypes)
> * /// <since_tizen> 3 </since_tizen>
> * System.Boolean Tizen.NUI.Rectangle::swigCMemOwn
> * /// <since_tizen> 3 </since_tizen>
> * System.Void Tizen.NUI.RelativeVector4::Dispose(Tizen.NUI.DisposeTypes)
> * /// <since_tizen> 3 </since_tizen>
> * System.Void Tizen.NUI.VisualBase::Dispose(Tizen.NUI.DisposeTypes)
> * /// <since_tizen> 3 </since_tizen>
> * System.Boolean Tizen.NUI.Hover::swigCMemOwn
> * /// <since_tizen> 3 </since_tizen>
> * System.Void Tizen.NUI.Touch::Dispose(Tizen.NUI.DisposeTypes)
> * /// <since_tizen> 3 </since_tizen>
> * System.Boolean Tizen.NUI.Wheel::swigCMemOwn
> * /// <since_tizen> 3 </since_tizen>
> * System.Void Tizen.NUI.RelativeVector3::Dispose(Tizen.NUI.DisposeTypes)
> * /// <since_tizen> 3 </since_tizen>
> * System.Boolean Tizen.NUI.PropertyArray::swigCMemOwn
> * /// <since_tizen> 3 </since_tizen>
> * System.Void Tizen.NUI.PropertyKey::Dispose(Tizen.NUI.DisposeTypes)
> * /// <since_tizen> 4 </since_tizen>
> * System.Boolean Tizen.NUI.Adaptor::swigCMemOwn
> * /// <since_tizen> 3 </since_tizen>
> * System.Void Tizen.NUI.Color::Dispose(Tizen.NUI.DisposeTypes)
> * /// <since_tizen> 3 </since_tizen>
> * System.Boolean Tizen.NUI.PaddingType::swigCMemOwn
> * /// <since_tizen> 3 </since_tizen>
> * System.Void Tizen.NUI.Vector4::Dispose(Tizen.NUI.DisposeTypes)
> * /// <since_tizen> 3 </since_tizen>
> * System.Void Tizen.NUI.TextureSet::Dispose(Tizen.NUI.DisposeTypes)
> * /// <since_tizen> 3 </since_tizen>
> * System.Boolean Tizen.NUI.PropertyMap::swigCMemOwn
> * /// <since_tizen> 5 </since_tizen>
> * System.Boolean Tizen.NUI.Size::swigCMemOwn
> * /// <since_tizen> 3 </since_tizen>
> * System.Void Tizen.NUI.PinchGesture::Dispose(Tizen.NUI.DisposeTypes)
> * /// <since_tizen> 3 </since_tizen>
> * System.Boolean Tizen.NUI.Gesture::swigCMemOwn
> * /// <since_tizen> 3 </since_tizen>
> * System.Void Tizen.NUI.LongPressGesture::Dispose(Tizen.NUI.DisposeTypes)
> * /// <since_tizen> 4 </since_tizen>
> * System.Void Tizen.NUI.PropertyNotification::Dispose(Tizen.NUI.DisposeTypes)

Hello, Mr. SSong, actually Dispose and swigCMemOwn apis don't removed, they are just moved into Disposable/BaseHandle class. so they should be refactory apis. I updated the ACR, please have a look.

**Comment by dongsug-song** [comment]
http://suprem.sec.samsung.net/jira/browse/TCSACR-291 is accepted, so I merge.

**Pull request merged**
