### PR TITLE
[NUI][ATSPI] Modify Accessbility for picker components

### PR DESCRIPTION
**Pull request by lwc0917**
### Description of Change ###
picker components does not need value interface.
picker works like container so it does not need highlightable.

### API Changes ###
no changes

### CODE REVIEW

**Review by kimcinoo — APPROVED** [review]
Looks good to me
It would be good if @lukasz oleksak have a look this PR

**Comment by dongsug-song** [comment]
@kimcinoo 
Hello, when Mr. lukasz gets the reviewer privilege, please add him as a reviewer to process this PR.
thank you.

**Review by lol-github — COMMENTED** [review]
LGTM, DatePicker and TimePicker are just containers and they do not support any attributes that could be mapped to Value interface, so they shouldn't implement Value interface.

Re. Picker, it is also a container (list) of items but this items  seams to simulate range of discrete   values there are currentValue and max/min value attributes which could map to Value interface.

**Review by huiyueun — APPROVED** [review]
LGTM

**Pull request merged**
