### PR TITLE
[NUI] Update TCs of  NUI.Devel.

### PR DESCRIPTION
**Pull request by AchoWang**
### Description of Change ###
Update TCs of  NUI.Devel.

### API Changes ###

 - ACR:

### CODE REVIEW

**Review by zg2nets — APPROVED** [review]

**Review by zhouleonlei — APPROVED** [review]
LGTM

**Review by huayongxu — COMMENTED** [review]
lgtm

**Review by wb0716 — APPROVED** [review]
Good for me

**Review by dongsug-song — APPROVED** [review]
looks good to me

**Pull request merged**
