### PR TITLE
[Tizen.Security] Enhancements of API description

### PR DESCRIPTION
**Pull request by j-wlostowski**
Enhance documentation description according to guidelines.

### CODE REVIEW

**Comment by j-wlostowski** [comment]
@yl33 are you aware who's responsible for this module, and might be able to review this?

**Comment by yl33** [comment]
@TomaszSwierczek is in charge of this module now.

**Comment by TomaszSwierczek** [comment]
@j-wlostowski , can you add me as reviewer then so I can score this change finally & some others in the tizenfx repo too?

**Comment by j-wlostowski** [comment]
@yl33 I was trying to add TomaszSwierczek as a reviewer, but apparently I can't. Can you approve this yourself, please? These are just simple documentation changes.

**Review by yl33 — APPROVED** [review]
It seems that @TomaszSwierczek is a module owner but doesn't have access right now. I'll review it instead.

**Review by TomaszSwierczek — APPROVED** [review]

**Pull request merged**
