### PR TITLE
[NUI] NUI Integration - nui_1.2.83 version

### PR DESCRIPTION
**Pull request by huiyueun**
### Description of Change ###
NUI Integration - nui_1.2.83 version

### CODE REVIEW

**Comment by WonyoungChoi** [comment]
Could you share the ACR links for changed or added APIs?

**Comment by huiyueun** [comment]
* ACR List
[NUI] Update Widget / NUIWidgetApplication 
    -> http://suprem.sec.samsung.net/jira/browse/TCSACR-119
[NUI] Remove some unused APIs. 
    -> http://suprem.sec.samsung.net/jira/browse/TCSACR-108

below list is need ACR. I have added 'EditorBrowsable(EditorBrowsableState.Never)' keyword.
[NUI] add EnableShiftSelection in TextField,TextEditor
 TextEditor.cs - EnableShiftSelection
 TextField.cs  - EnableShiftSelection
 TextLabel.cs  - TextDirection
 
[NUI] add Reload() to reload image forcely
[NUI] Support for animated GIF (#34)
 ImageView.cs - Reload(), Play(), Pause(), Stop()

[NUI] Add ImageLoading and PixelBuffer for TextureSet
 +ImageLoading.cs
 +PixelBuffer.cs
 
[NUI] Support for animated GIF (#34)
  NUIConstants.cs - LoopCount
  VisualMaps.cs - LoopCount
 
[NUI] Nui release 1.2.82 (#45)
  TextLabel.cs - VerticalLineAlignment
  NUIConstants.cs - VerticalLineAlignment(Top,Center,Bottom)

**Comment by huiyueun** [comment]
http://suprem.sec.samsung.net/jira/browse/TCSACR-130

**Comment by huiyueun** [comment]
@WonyoungChoi 안녕하세요, 
ACR진행이 필요한 API에 대해서는 EditorBrowsableState.Never 키워드를 붙였습니다.
tizen-tizen_4.0 branch synk를 위해 우선 머지 진행후, ACR진행 이후에 키워드 없애는 패치를 작성하여도 될까요??

**Comment by WonyoungChoi** [comment]
@huiyueun Yes, you can merge this PR without ACR if there is no public API changes. However this PR is for master branch, if you want to apply to tizen_4.0 branch of the tizen gerrit, you should make a PR for API4 branch.

**Pull request merged**
