### PR TITLE
[NUI][EXaml] Support Array in EXaml

### PR DESCRIPTION
**Pull request by AdunFang**
### Description of Change ###

Fix JIRA https://code.sec.samsung.net/jira/browse/GRE-2307
Relate to https://github.com/nui-dali/Tizen.NUI.XamlBuild/pull/20

1. Support Array in EXaml.
2. Rewrite the method of load examl, now user can put .xaml files every where.

### API Changes ###

 - ACR:

### CODE REVIEW

**Review by AchoWang — APPROVED** [review]
Looks good to me.

**Review by zhouleonlei — APPROVED** [review]
LGTM

**Review by wb0716 — APPROVED** [review]
Good for me

**Review by elishateng — APPROVED** [review]
LGTM

**Review by huayongxu — APPROVED** [review]
lgtm

**Review by zhouleonlei — APPROVED** [review]
LGTM

**Review by elishateng — APPROVED** [review]
LGTM

**Review by zg2nets — APPROVED** [review]
lgtm

**Review by dongsug-song — APPROVED** [review]
looks good to me

**Pull request merged**
