### PR TITLE
[NUI] Add webview settings apis

### PR DESCRIPTION
**Pull request by zhouleonlei**
### Description of Change ###
Add webview settings apis, relate to dali-csharp-binder patch below:
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/255229

### API Changes ###

 - ACR:

### CODE REVIEW

**Review by wb0716 — APPROVED** [review]
Good for me

**Review by elishateng — APPROVED** [review]
LGTM

**Review by AchoWang — APPROVED** [review]
Looks good to me.

**Review by dongsug-song — APPROVED** [review]
could you check the following guide?
https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1065?view=vs-2019
https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/property?redirectedfrom=MSDN
https://stackoverflow.com/questions/1488472/best-practices-throwing-exceptions-from-properties

for this time, I approve this.
but from next time. property getter should not throw an exception.
please check and re-design property for next time.
thank you.

**Comment by zhouleonlei** [comment]
> could you check the following guide?
> https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1065?view=vs-2019
> https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/property?redirectedfrom=MSDN
> https://stackoverflow.com/questions/1488472/best-practices-throwing-exceptions-from-properties
> 
> for this time, I approve this.
> but from next time. property getter should not throw an exception.
> please check and re-design property for next time.
> thank you.

Hello Mr.Song
Thanks

> could you check the following guide?
> https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1065?view=vs-2019
> https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/property?redirectedfrom=MSDN
> https://stackoverflow.com/questions/1488472/best-practices-throwing-exceptions-from-properties
> 
> for this time, I approve this.
> but from next time. property getter should not throw an exception.
> please check and re-design property for next time.
> thank you.

Hello Mr.Song:
Fixed.
Thanks for your guide

**Comment by zhouleonlei** [comment]
> could you check the following guide?
> https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1065?view=vs-2019
> https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/property?redirectedfrom=MSDN
> https://stackoverflow.com/questions/1488472/best-practices-throwing-exceptions-from-properties
> 
> for this time, I approve this.
> but from next time. property getter should not throw an exception.
> please check and re-design property for next time.
> thank you.

Hello Mr.Song:
Fixed.
Thanks for your guide

**Review by huiyueun — APPROVED** [review]
LGTM

**Pull request merged**
