### PR TITLE
[NUI] Frame callback refactoring

### PR DESCRIPTION
**Pull request by bshsqa**
- Remove FrameCallback.cs and Interop.FrameCallback.cs
 - Rename FrameCallbackInterface to FrameUpdateCallbackInterface

### CODE REVIEW

**Comment by dongsug-song** [comment]
@bshsqa 
Hello, 
could you confirm that this PR is really required to be included in tizen_6.0 (API8) ?
if not required for API8, could you please move this PR to DevelNUI ?
thank you.

**Comment by bshsqa** [comment]
@dongsug-song 
Hello, yes it is needed to be merged to API8.
Thank you.

**Review by AdunFang — APPROVED** [review]
It is OK.

**Review by dongsug-song — APPROVED** [review]
These are all hiden-API changes and it seems that no side effect and no bug would occur.
Looks good to me.

**Pull request merged**
