### PR TITLE
[NUI] Apply CornerRadius to WidgetView

### PR DESCRIPTION
**Pull request by tscholb**
### Description of Change ###

The CornerRadius function previously supported in View has been modified to also apply to WidgetView.
For this behavior, WidgetView has an internal visual and its structure is changed.
In this case,  WidgetView no longer generates shaders and rendering directly.
    
I've added a sample for testing the corner radius.
You can use it as follows:
widgetView.CornerRadius = 22;

https://review.tizen.org/gerrit/#/c/platform/core/uifw/widget-viewer-dali/+/302475/

### API Changes ###

 - ACR:

### CODE REVIEW

**Review by hinohie — APPROVED** [review]

**Comment by dongsug-song** [comment]
@tscholb 
Hello,
please add some descrition and if possible, please add sample code or sample APP.
thank you.

**Review by jaehyun0cho — APPROVED** [review]
LGTM

**Comment by dongsug-song** [comment]
@tscholb 
from next time, please add some description and add the dali patch link which has some dependency.
thank you.

**Comment by tscholb** [comment]
okay, i updated the description

**Pull request merged**
