### PR TITLE
[NUI] Add direction & displacement into ScrollOutOfBound event.

### PR DESCRIPTION
**Pull request by huayongxu**
### Description of Change ###
This patch is to trigger ScrollOutOfBound event as pan gesture state,
and add pan direction & displacement into ScrollOutOfBound event.
Bound of ScrollOutOfBoundEventArgs is removed, because displacement
can be used for checking Top/Bottom.

### API Changes ###
none

### CODE REVIEW

**Review by AchoWang — APPROVED** [review]
Looks good to me.

**Comment by dongsug-song** [comment]
@huayongxu 
Hello
could you add some test case or sample app to verify this?
also hidden API's interface has been changed so detail and explanation are required for user.
please add some usage.
thank you.

**Review by zhouleonlei — APPROVED** [review]
LGTM

**Comment by huayongxu** [comment]
> @huayongxu
> Hello
> could you add some test case or sample app to verify this?
> also hidden API's interface has been changed so detail and explanation are required for user.
> please add some usage.
> thank you.

I updated sample and verified.

**Review by AchoWang — APPROVED** [review]
Looks good to me.

**Comment by dongsug-song** [comment]
@huayongxu 
Hello, could you make same PR in API8 (tizen_6.0) ?
thank you.

**Review by AdunFang — COMMENTED** [review]
It is OK.

**Pull request merged**
