### PR TITLE
[NUI] Add xaml, examl and xamlbing testcases

### PR DESCRIPTION
**Pull request by elishateng**
### Description of Change ###

1. Add xaml, examl and xamlbing testcases

### API Changes ###

 - ACR:

### CODE REVIEW

**Review by AdunFang — APPROVED** [review]
It is OK.

**Review by AchoWang — APPROVED** [review]
Looks good to me.

**Review by zhouleonlei — APPROVED** [review]
LGTM

**Review by dongsug-song — APPROVED** [review]
looks good to me

**Pull request merged**
