### PR TITLE
[NUI] Revert the legacy Autofill code

### PR DESCRIPTION
**Pull request by Seoyeon2Kim**
### Description of Change ###
- NUI Autofill code was not removed together with dali ones.
- Now, all related codes should be deleted because there's no use case anywhere and they don't have their internal implementation.

### API Changes ###
- N/A

### CODE REVIEW

**Review by dongsug-song — APPROVED** [review]
approved

**Review by jaehyun0cho — APPROVED** [review]
LGTM

**Review by tscholb — APPROVED** [review]
LGTM :)

**Review by JoogabYun — APPROVED** [review]

**Review by rabbitfor — APPROVED** [review]
:)

**Pull request merged**
