### PR TITLE
[NUI][SVACE] Fix SVACE issues

### PR DESCRIPTION
**Pull request by AchoWang**
### API Changes ###

 - ACR:

### CODE REVIEW

**Review by wb0716 — APPROVED** [review]
Good for me

**Review by zhouleonlei — APPROVED** [review]
lgtm

**Review by wanchao-xu — APPROVED** [review]
lgtm

**Review by zg2nets — COMMENTED** [review]
please add [SVACE] tag in title. (ex: [NUI][SVACE] resolve API10 svace issue ...)

**Review by dongsug-song — APPROVED** [review]
looks good to me

**Pull request merged**
