### PR TITLE
[NUI] Use IsSet replace changedPropertiesSet

### PR DESCRIPTION
**Pull request by elishateng**
### Description of Change ###

1. Use IsSet to replace changedPropertiesSet

### API Changes ###

 - ACR: None

### CODE REVIEW

**Review by AchoWang — APPROVED** [review]
Looks good to me.

**Review by wanchao-xu — APPROVED** [review]
Looks good to me

**Review by xiaowei-guan — APPROVED** [review]
LGTM

**Review by AdunFang — APPROVED** [review]
It is OK.

**Review by huayongxu — APPROVED** [review]
lgtm

**Review by zhouleonlei — APPROVED** [review]
lgtm

**Review by AchoWang — APPROVED** [review]
Looks good to me.

**Review by dongsug-song — APPROVED** [review]
approve

**Pull request merged**
