### PR TITLE
[NUI] Fix XamlLoader testcase error

### PR DESCRIPTION
**Pull request by elishateng**
### Description of Change ###

1.Fix XamlLoader testcase error

### API Changes ###

 - ACR:

### CODE REVIEW

**Review by zhouleonlei — APPROVED** [review]
LGTM

**Review by AchoWang — APPROVED** [review]
Looks good to me.

**Review by wb0716 — APPROVED** [review]
Good for me

**Review by dongsug-song — APPROVED** [review]
looks good to me

**Comment by dongsug-song** [comment]
@elishateng 
Hello, 
please resolve this conflict. 
thank you.

**Review by dongsug-song — APPROVED** [review]
looks good to me

**Pull request closed without merging**
