### PR TITLE
[NUI][EXaml] Support Dictionary

### PR DESCRIPTION
**Pull request by AdunFang**
### API Changes ###

 - ACR:

### CODE REVIEW

**Review by wanchao-xu — APPROVED** [review]
Looks good to me

**Review by huayongxu — APPROVED** [review]
lgtm

**Comment by xuelian-bai** [comment]
looks good to me

**Review by zhouleonlei — APPROVED** [review]
lgtm

**Review by wb0716 — APPROVED** [review]
Good for me

**Review by dongsug-song — APPROVED** [review]
approved

**Review by AchoWang — COMMENTED** [review]
Looks good to me.

**Pull request merged**
