### PR TITLE
[NUI] Add Utility(internal) TCs.

### PR DESCRIPTION
**Pull request by AchoWang**
### Description of Change ###
Add Utility(internal) TCs.

### API Changes ###

 - ACR:

### CODE REVIEW

**Review by zhouleonlei — APPROVED** [review]
LGTM

**Review by wb0716 — APPROVED** [review]
Good for me

**Review by zg2nets — APPROVED** [review]
looks good！

**Review by elishateng — APPROVED** [review]
LGTM

**Review by AdunFang — APPROVED** [review]
It is OK.

**Review by dongsug-song — APPROVED** [review]
looks good to me

**Pull request merged**
