### PR TITLE
[NUI] Update WebView TCs.

### PR DESCRIPTION
**Pull request by huayongxu**
### API Changes ###

 - ACR:

### CODE REVIEW

**Review by zg2nets — APPROVED** [review]
good job

**Review by wb0716 — APPROVED** [review]
Good for me

**Review by wanchao-xu — APPROVED** [review]
Looks good to me

**Review by AchoWang — APPROVED** [review]
Looks good to me.

**Review by dongsug-song — APPROVED** [review]
approved

**Review by xiaowei-guan — COMMENTED** [review]
LGTM

**Review by hyue7 — COMMENTED** [review]
looks good

**Pull request merged**
