### PR TITLE
[NUI] Add file comment and end empty line

### PR DESCRIPTION
**Pull request by elishateng**
### Description of Change ###

1. Add file comment and end empty line
2. Remove unused reference from xamlbuild.

### API Changes ###

 - ACR:

### CODE REVIEW

**Review by AdunFang — APPROVED** [review]
It is OK.

**Review by zhouleonlei — APPROVED** [review]
lgtm

**Review by dongsug-song — APPROVED** [review]
looks good to me

**Comment by dongsug-song** [comment]
build test was done by this failures :
<html>
<body>


Package Name | Package Path | Build Status
-- | -- | --
csapi-tv-security | //TIZEN/[MAIN]/[ONEPROD_Prj]/[INT]/DOTNET/Csapi/csapi-tv-security/...@9768794 | Failed
csapi-tv-service-magicinfo | //TIZEN/[MAIN]/[ONEPROD_Prj]/[INT]/DOTNET/Csapi/csapi-tv-service-magicinfo/...@9819016 | Failed



locally GBS building tested was done with this PR.

_info: finished building csapi-tv-security
info: updating local repo
info: *** Build Status Summary ***
=== Total succeeded built packages: (1) ===_

...

_info: finished building csapi-tv-service-magicinfo
info: updating local repo
info: *** Build Status Summary ***
=== Total succeeded built packages: (1) ===_

**Review by AchoWang — COMMENTED** [review]
Looks good to me.

**Pull request merged**
