### PR TITLE
[NUI] Fix issue that NUI will crash when load the boolean of "False" of EXaml. (Fix Jira 2295)

### PR DESCRIPTION
**Pull request by AdunFang**
### API Changes ###

 - ACR:

### CODE REVIEW

**Review by AchoWang — APPROVED** [review]
Looks good to me.

**Review by zhouleonlei — APPROVED** [review]
LGTM

**Comment by zg2nets** [comment]
You'd better to describe the issue instead of "Jira 2295"

**Review by dongsug-song — APPROVED** [review]
looks good to me

**Pull request merged**
