### PR TITLE
[XamlBuild] Fix issue of project which hasn't debug symbol

### PR DESCRIPTION
**Pull request by AdunFang**
### Description of Change ###

Fix issue of project which hasn't debug symbol.

### API Changes ###

 - ACR:

### CODE REVIEW

**Review by zg2nets — APPROVED** [review]
looks good~

**Review by wanchao-xu — APPROVED** [review]
Looks good to me

**Review by zhouleonlei — APPROVED** [review]
lgtm

**Comment by xuelian-bai** [comment]
looks good to me

**Review by wb0716 — APPROVED** [review]
Good  for me

**Review by dongsug-song — APPROVED** [review]
looks good to me
I have tested GBS build with this patch in local ubuntu.
it has been built successfully.

**Pull request merged**
