### PR TITLE
[NUI] Avoid creating BindablePropertyContext for the special cases

### PR DESCRIPTION
**Pull request by rabbitfor**
Signed-off-by: Jiyun Yang <ji.yang@samsung.com>

### API Changes ###

 - ACR:

### CODE REVIEW

**Comment by dongsug-song** [comment]
@everLEEst @AdunFang 
Hello,
could you review this? it's related to BindableProperty so I think your reviews will be helpful.
thank you.

**Review by everLEEst — COMMENTED** [review]
LGTM but I think it need to check @AdunFang again.
as my understand,
we are planning to do this,
so only make BindablePropertyContexxt when it really binded something.

@AdunFang 
can you plase check it once?

**Review by AdunFang — APPROVED** [review]
It is OK.

**Review by dongsug-song — APPROVED** [review]
looks good to me

**Pull request merged**
