### PR TITLE
[NUI] Add Layouting(public) TCs.

### PR DESCRIPTION
**Pull request by AchoWang**
### Description of Change ###
Add public/Layouting/* TCs.

### API Changes ###

 - ACR:

### CODE REVIEW

**Review by elishateng — APPROVED** [review]
LGTM

**Review by zhouleonlei — APPROVED** [review]
LGTM

**Review by huayongxu — APPROVED** [review]
lgtm

**Review by wb0716 — APPROVED** [review]
Gd for me

**Review by AdunFang — APPROVED** [review]
It is OK.

**Review by dongsug-song — APPROVED** [review]
looks good to me

**Pull request merged**
