### PR TITLE
[NUI] Add ImageList property

### PR DESCRIPTION
**Pull request by huiyueun**
Signed-off-by: huiyu.eun <huiyu.eun@samsung.com>

### API Changes ###

 - ACR:

### CODE REVIEW

**Review by dasg34 — CHANGES_REQUESTED** [review]
`Framework Design Guidelines` don't recommend using `List<T>` in public APIs.

https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/guidelines-for-collections
>❌ DO NOT use ArrayList or List<T> in public APIs.
These types are data structures designed to be used in internal implementation, not in public APIs. List<T> is optimized for performance and power at the cost of cleanness of the APIs and flexibility. For example, if you return List<T>, you will not ever be able to receive notifications when client code modifies the collection. Also, List<T> exposes many members, such as BinarySearch, that are not useful or applicable in many scenarios. The following two sections describe types (abstractions) designed specifically for use in public APIs.

I think you can use `IList<T>` instead of `List<T>`.

**Comment by dongsug-song** [comment]
@dasg34 
Hello, this patch is fixed by your review.
I think it's good to go.
could you review again?
thank you.

**Review by hyunjushin — APPROVED** [review]
API reviewed

**Review by dasg34 — APPROVED** [review]
👍

**Pull request merged**
