### PR TITLE
[NUI] Fix fitting mode issue of ImageView

### PR DESCRIPTION
**Pull request by elishateng**
### Description of Change ###

1. Fix fitting mode issue of ImageView

### API Changes ###

 - ACR:

### CODE REVIEW

**Review by zhouleonlei — APPROVED** [review]
LGTM

**Review by AchoWang — APPROVED** [review]
Looks good to me.

**Review by huayongxu — APPROVED** [review]
lgtm.

**Review by AdunFang — APPROVED** [review]
It is OK.

**Pull request merged**
