### PR TITLE
[NUI] Fix a build warning CA1717

### PR DESCRIPTION
**Pull request by Seoyeon2Kim**
Signed-off-by: Seoyeon Kim <seoyeon2.kim@samsung.com>

### Description of Change ###
- Only FlagsAttribute enums should have plural names
 https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1717

- Some enums cannot be fixed because they're already public APIs,
 so added suppress messages for CA1717 build warning.
- Some enums are already used as hidden APIs,
 so added Obsolete tags and made a fixed version as singular name.
- Tizen.NUI.Components.ControlStates enum should be marked with the FlagsAttribute.

### API Changes ###
- N/A

### CODE REVIEW

**Comment by huiyueun** [comment]
LGTM

**Comment by rabbitfor** [comment]
> Some enums cannot be fixed because they're already public APIs,
so added suppress messages for CA1717 build warning.

For the public APIs, are you planning to add new APIs to replace them and proceed ACR?

**Comment by Seoyeon2Kim** [comment]
> > Some enums cannot be fixed because they're already public APIs,
> > so added suppress messages for CA1717 build warning.
> 
> For the public APIs, are you planning to add new APIs to replace them and proceed ACR?

Oh I couldn't think about it. I'll add new APIs and proceed  ACR in other PR.
Thank you for notifying it.

**Review by rabbitfor — APPROVED** [review]
LGTM

**Pull request merged**
