### PR TITLE
[NUI][Xaml] Support different params in Vector Converter

### PR DESCRIPTION
**Pull request by AdunFang**
### API Changes ###

 - ACR:

### CODE REVIEW

**Review by wb0716 — COMMENTED** [review]
Good for me

**Review by zg2nets — APPROVED** [review]
lgtm

**Review by wb0716 — APPROVED** [review]

**Review by elishateng — APPROVED** [review]
LGTM

**Review by zhouleonlei — APPROVED** [review]
LGTM

**Review by dongsug-song — APPROVED** [review]
looks good to me

**Pull request merged**
