### PR TITLE
[NUI] Remove StyleCop CA1715 warning messages

### PR DESCRIPTION
**Pull request by jaehyun0cho**
Since T, U, R are commonly used as generic type parameter names and not
to do ACR, StyleCop CA1715 warning messages in DaliEventHandler.cs are
removed.

### API Changes ###

 - ACR:

### CODE REVIEW

**Comment by jaehyun0cho** [comment]
To rename VertexType to TVertexType, ACR is required because it causes API change.
Therefore, VertexType is not changed in this patch.

**Review by dasg34 — APPROVED** [review]

**Comment by jaehyun0cho** [comment]
@WonyoungChoi 
Hello. I have a question about the tag "ACR Required" here.
The tag "ACR Required" is added because the publicly opened API's parameter names are changed.
Could you please let me know if ACR is required for this case?
Thank you.

**Review by AdunFang — APPROVED** [review]
It is OK.

**Review by hyunjushin — APPROVED** [review]

**Comment by hyunjushin** [comment]
Please suppress warning for VertexType.

**Comment by dongsug-song** [comment]
@jaehyun0cho 
Hello, 
unfortunately I think this needs TCSACR. 
could you check this ACR ( https://code.sec.samsung.net/jira/browse/TCSACR-322 )?
it just changes parameter name (not type) but it required PM's Single approval.
could you please check further for yourself.
thank you.

**Comment by hyunjushin** [comment]
@jaehyun0cho  please add [EditorBrowsable(EditorBrowsableState.Never)] on DevelNUI branch. When this patch merged to master, you can remove it and get ACR review.

**Comment by dongsug-song** [comment]
@jaehyun0cho 
Hello,
please do not upload ACR-PR in DevelNUI branch.
here is a tip to handle ACR-PR here, I hope this helps.
thank you.

- Add-ACR : 
  1) the ACR-PR should be processed in master branch only.
  2) so, make API as hidden by adding `[EditorBrowsable(EditorBrowsableState.Never)]` attribute, then in DevelNUI branch API-Checker will pass. (No "ACR Required" tag)
  3) after the patch is merged into master branch by regular integration work, you can make new PR in master branch by removing `[EditorBrowsable(EditorBrowsableState.Never)]` attribute to proceed ACR.
  4) if the ACR is urgent, you can upload PR on master branch directly. that PR will be merged on DevelNUI branch by rebasing during the regular integration work.

- Deprecate-ACR : 
  1) the ACR-PR should be processed in master branch only.
  2) so, add some mark on the API by writing some comments like `//ToDo : will raise deprecated-ACR, [Obsolete("This has been deprecated in APIxxx and will be removed in APIxxx+2. The xxx variable is not used anymore and the xxx is replaced by xxx! Please use xxx instead!")`
  3) by step 2), the PR on DevelNUI will pass. (No "ACR Required" tag)
  4) after the patch is merged into master branch by regular integration work, you can make new PR in master branch by adding `[Obsolete("blah blah")]` tag in order to proceed ACR.
  5) if the ACR is urgent, you can upload PR on master branch directly. that PR will be merged on DevelNUI branch by rebasing during the regular integration work.

**Comment by jaehyun0cho** [comment]
@dongsug-song 
I think it is not necessary to fix single-character type parameters for CA1715 if ACR/Deprecate are required.

The following guide also provides a way not to analyze single-character type parameters for CA1715.
https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1715#single-character-type-parameters

What do you think about not analyzing single-character type parameters for CA1715 by modifying .editorconfig file?

**Comment by rabbitfor** [comment]
Hi @jaehyun0cho 
if current code does require ACR for CA1715, then I think it is ok to supress warnings for them.

```C#
[SuppressMessage("Microsoft.Naming", "CA1715: IdentifiersShouldHaveCorrectPrefix")]
public delegate R DaliEventHandlerWithReturnType<T, U, R>(T source, U e);
```

**Comment by dongsug-song** [comment]
@jaehyun0cho 
Hello,
please check @rabbitfor 's comment above and suppress the warning~
Thank you.

**Comment by dongsug-song** [comment]
@jaehyun0cho 
Hello, 
please resolve the conflicts. otherwise please upload new PR and close this PR.
thank you.

**Comment by dongsug-song** [comment]
@jaehyun0cho 
Hello,
please upload the ACR PR on master branch.
thank you.

- Add-ACR : 
  1) the ACR-PR should be processed in master branch only.
  2) so, make API as hidden by adding `[EditorBrowsable(EditorBrowsableState.Never)]` attribute, then in DevelNUI branch API-Checker will pass. (No "ACR Required" tag)
  3) after the patch is merged into master branch by regular integration work, you can make new PR in master branch by removing `[EditorBrowsable(EditorBrowsableState.Never)]` attribute to proceed ACR.
  4) if the ACR is urgent, you can upload PR on master branch directly. that PR will be merged on DevelNUI branch by rebasing during the regular integration work.

- Deprecate-ACR : 
  1) the ACR-PR should be processed in master branch only.
  2) so, add some mark on the API by writing some comments like `//ToDo : will raise deprecated-ACR, [Obsolete("This has been deprecated in APIxxx and will be removed in APIxxx+2. The xxx variable is not used anymore and the xxx is replaced by xxx! Please use xxx instead!")`
  3) by step 2), the PR on DevelNUI will pass. (No "ACR Required" tag)
  4) after the patch is merged into master branch by regular integration work, you can make new PR in master branch by adding `[Obsolete("blah blah")]` tag in order to proceed ACR.
  5) if the ACR is urgent, you can upload PR on master branch directly. that PR will be merged on DevelNUI branch by rebasing during the regular integration work.

**Comment by jaehyun0cho** [comment]
As @rabbitfor suggested, SuppressMessage is used.
Thank you.

**Pull request merged**
