### PR TITLE
[NUI] Removed unused getCPtr apis

### PR DESCRIPTION
**Pull request by elishateng**
### Description of Change ###

1. Removed unused getCPtr apis
2. Reduce code duplication

### API Changes ###

 - ACR:

### CODE REVIEW

**Comment by dongsug-song** [comment]
@elishateng 
Hello, Mr. Teng
if we remove this kind of getCPtr() method, what is the alternative API?
do you think these ? : GetManagedBaseHandleFromNativePtr(), GetManagedBaseHandleFromRefObject().
(sometimes, I use this kind of getCPtr API as internal purpose, so I am just asking.)

**Comment by elishateng** [comment]
> @elishateng
> Hello, Mr. Teng
> if we remove this kind of getCPtr() method, what is the alternative API?
> do you think these ? : GetManagedBaseHandleFromNativePtr(), GetManagedBaseHandleFromRefObject().
> (sometimes, I use this kind of getCPtr API as internal purpose, so I am just asking.)

Hello, Mr. SSong, Currently removed apis are just its reference is 0. so it should be ok. After [PR-1112](https://github.com/Samsung/TizenFX/pull/1112) merged, I think we can just use BaseHandle/Disposable getCPtr api.

**Comment by dongsug-song** [comment]
@elishateng 
Hello, please fix the merge conflict.

**Comment by dongsug-song** [comment]
no more review done, so merged.

**Pull request merged**
