### PR TITLE
[NUI] Fix build errors of NUI.Devel based on API10.

### PR DESCRIPTION
**Pull request by AchoWang**
### API Changes ###

 - ACR:

### CODE REVIEW

**Comment by xuelian-bai** [comment]
looks good to me

**Review by huayongxu — COMMENTED** [review]
lgtm

**Review by xiaowei-guan — APPROVED** [review]
LGTM

**Review by zhouleonlei — APPROVED** [review]
LGTM

**Review by AdunFang — APPROVED** [review]
It is OK.

**Review by dongsug-song — APPROVED** [review]
looks good to me

**Pull request merged**
