### PR TITLE
[NUI] Replace PropertyMap with Dictionary in HitTest.

### PR DESCRIPTION
**Pull request by huayongxu**
### Description of Change ###

And update some comments.

### API Changes ###

 - ACR:

### CODE REVIEW

**Comment by xuelian-bai** [comment]
looks good to me

**Review by AchoWang — APPROVED** [review]
Looks good to me.

**Review by elishateng — APPROVED** [review]
LGTM

**Review by zhouleonlei — APPROVED** [review]
LGTM

**Comment by dongsug-song** [comment]
@huayongxu 
Hello, please resolve the conflict, then I will merge this.
thank you.

**Comment by huayongxu** [comment]
> @huayongxu
> Hello, please resolve the conflict, then I will merge this.
> thank you.

Done.

**Review by dongsug-song — APPROVED** [review]
looks good to me

**Pull request merged**
