### PR TITLE
[XamlBuild] Fix extents convert issue

### PR DESCRIPTION
**Pull request by elishateng**
### Description of Change ###

1. Fix extents convert issue.

### API Changes ###

 - ACR: None.

### CODE REVIEW

**Review by hyue7 — APPROVED** [review]
looks good

**Review by zg2nets — APPROVED** [review]
lgtm

**Comment by dongsug-song** [comment]
@elishateng 
The master branch and the DevelopNUI branch sync did not match, so I was forced to hard reset the DevelopNUI branch. (I'm sorry for the inconvenience.)
please solve the code conflict, or close this PR and upload a new PR.
Thank you.

**Comment by elishateng** [comment]
> @elishateng The master branch and the DevelopNUI branch sync did not match, so I was forced to hard reset the DevelopNUI branch. (I'm sorry for the inconvenience.) please solve the code conflict, or close this PR and upload a new PR. Thank you.

Oh. Sorry, I just update it, please review it again.

**Comment by elishateng** [comment]
> @elishateng The master branch and the DevelopNUI branch sync did not match, so I was forced to hard reset the DevelopNUI branch. (I'm sorry for the inconvenience.) please solve the code conflict, or close this PR and upload a new PR. Thank you.

Hi, Mr. SSong, could you please review it again ?

**Review by everLEEst — APPROVED** [review]
great! my mistake. sorry.

**Comment by elishateng** [comment]
> great! my mistake. sorry.

It's ok, thank you~

**Pull request merged**
