### PR TITLE
[NUI] Fix equals issue of Selector

### PR DESCRIPTION
**Pull request by elishateng**
### Description of Change ###

1. Fix equals issue of Selector

### API Changes ###

 - ACR:

### CODE REVIEW

**Review by wb0716 — APPROVED** [review]
Good for me

**Review by xiaowei-guan — APPROVED** [review]
LGTM

**Review by AdunFang — APPROVED** [review]
It is OK.

**Review by zhouleonlei — APPROVED** [review]
lgtm

**Comment by xuelian-bai** [comment]
looks good to me

**Review by huayongxu — COMMENTED** [review]
lgtm

**Review by AchoWang — APPROVED** [review]
Looks good to me.

**Review by Seoyeon2Kim — APPROVED** [review]
LGTM, but @dongsug-song should check this PR.

**Pull request merged**
