### PR TITLE
[NUI] Fix issue that default value of BindableProperty is incorrect.

### PR DESCRIPTION
**Pull request by huayongxu**
### API Changes ###

 - ACR:

### CODE REVIEW

**Review by rabbitfor — COMMENTED** [review]
IMHO, changing default value to `0.0f` from `true` for float types is reasonable. But I don't understand for others. Does it need?

**Comment by huayongxu** [comment]
> IMHO, changing default value to `0.0f` from `true` for float types is reasonable. But I don't understand for others. Does it need?

I updated this patch.
default value of vector remains null still.

**Review by rabbitfor — APPROVED** [review]

**Review by zg2nets — COMMENTED** [review]
lgtm

**Review by zg2nets — COMMENTED** [review]
lgtm

**Review by xiaowei-guan — COMMENTED** [review]
LGTM

**Review by AchoWang — COMMENTED** [review]
Looks good to me.

**Review by zhouleonlei — COMMENTED** [review]
LGTM

**Pull request merged**
