### PR TITLE
[NUI] Update TCs of NUI.Devel.

### PR DESCRIPTION
**Pull request by AchoWang**
### Description of Change ###
Update TCs of NUI.Devel.

### API Changes ###

 - ACR:

### CODE REVIEW

**Review by zg2nets — APPROVED** [review]
it‘s good！

**Review by zhouleonlei — APPROVED** [review]
LGTM

**Review by AdunFang — APPROVED** [review]
It is OK.

**Review by dongsug-song — APPROVED** [review]
looks good to me

**Pull request merged**
