### PR TITLE
[NUI] Add Utility(public) TCs.

### PR DESCRIPTION
**Pull request by AchoWang**
### Description of Change ###
Add public\Utility\ TCs.

### API Changes ###

 - ACR:

### CODE REVIEW

**Review by AdunFang — APPROVED** [review]
It is OK.

**Review by wb0716 — COMMENTED** [review]
Good for me

**Review by elishateng — APPROVED** [review]
LGTM

**Review by dongsug-song — APPROVED** [review]
looks good to me

**Pull request merged**
