### PR TITLE
[NUI][EXaml] Support ResourcePath in Xaml

### PR DESCRIPTION
**Pull request by AdunFang**
### Description of Change ###

Fix JIRA: https://code.sec.samsung.net/jira/browse/GRE-2334
now user can set the relative path to Url in Xaml

sample:
`<ImageView x:Name="imageView" ResourceUrl="{ResourcePath FilePath=images/a.jpg}" />`

when the xaml is loaded, the path "Tizen.Applications.Application.Current.DirectoryInfo.Resource + "images/a.jpg"" will be set to the ResourceUrl.

### API Changes ###

 - ACR:

### CODE REVIEW

**Review by zhouleonlei — APPROVED** [review]
LGTM

**Review by elishateng — APPROVED** [review]
LGTM

**Review by AchoWang — APPROVED** [review]
Looks good to me.

**Review by zg2nets — APPROVED** [review]
lgtm

**Review by rabbitfor — COMMENTED** [review]
Hi Mr.Fang.
Could you add a new extension with a new name "ResourcePath"?
HQ discussed the name and we thought "ApplicationResourcePath" is too long.
(Since "ApplicationResourcePath" is used in other applications so please do not remove it.)

**Comment by AdunFang** [comment]
> Hi Mr.Fang.
> Could you add a new extension with a new name "ResourcePath"?
> HQ discussed the name and we thought "ApplicationResourcePath" is too long.
> (Since "ApplicationResourcePath" is used in other applications so please do not remove it.)

Has been Done.

**Review by dongsug-song — APPROVED** [review]
looks good to me

**Pull request merged**
