### PR TITLE
[NUI] Fix TC build errors & update TCs.

### PR DESCRIPTION
**Pull request by AchoWang**
### Description of Change ###
1. Fix build erros of internal/Transition , public/Theme , public/Window.
2. Fix block TCs and add new TCs.
3. Remove TCs that API were obsoleted.

### API Changes ###

 - ACR:

### CODE REVIEW

**Review by zhouleonlei — APPROVED** [review]
LGTM

**Review by huayongxu — APPROVED** [review]
lgtm

**Review by zg2nets — COMMENTED** [review]
lgtm

**Review by zg2nets — APPROVED** [review]

**Review by elishateng — APPROVED** [review]
LGTM

**Review by AdunFang — APPROVED** [review]
It is OK.

**Review by dongsug-song — APPROVED** [review]
looks good to me

**Pull request merged**
