### PR TITLE
[Storage] Add new enum and new methods

### PR DESCRIPTION
**Pull request by hyotaekshim**
Change-Id: Ic5af889a8bcc40b3667081e0ec8088df697006ee
Signed-off-by: pr.jung <pr.jung@samsung.com>

### Description of Change ###

- Add ExtendedInternal on StorageArea
- Add StorageDevice enumerations
- Add SetChangedEvent and UnsetChangedEvent on StorageManager class for storage_set_changed_cb and storage_unset_changed_cb apis

### Bugs Fixed ###

- N/A

### API Changes ###

Added:
 - ExtendedInternal = Interop.Storage.StorageArea.ExtendedInternal,
 - public enum StorageDevice
    { 
        ExternalSDCard = Interop.Storage.StorageDevice.ExternalSDCard,
        ExternalUSBMassStorage = Interop.Storage.StorageDevice.ExternalUSBMassStorage,
        ExtendedInternalStorage = Interop.Storage.StorageDevice.ExtendedInternalStorage,
    }   
 - public static void SetChangedEvent(StorageArea type, EventHandler handler)
 - public static void UnsetChangedEvent(StorageArea type, EventHandler handler)

### Behavioral Changes ###

N/A (All features are added)

### CODE REVIEW

**Comment by WonyoungChoi** [comment]
Please share the link of the ACR about changing these APIs.

**Comment by prjung** [comment]
ACR is now on progress.

**Comment by prjung** [comment]
What is PR template?

**Comment by WonyoungChoi** [comment]
@prjung Please see the description of this pull request. Put correct information into each section (Description of Change, Bug Fixes, API Changes, Behavior Changes)

**Comment by prjung** [comment]
I modified the description of this pull request.

**Comment by WonyoungChoi** [comment]
@hyotaekshim , @prjung  if available, please merge this pr.

**Pull request merged**
