### PR TITLE
[NUI][NUI.Devel] Fix build errors of NUI.Devel.

### PR DESCRIPTION
**Pull request by AchoWang**
### Description of Change ###
Because nui codes were updated, so some cases  related "Any" occurred build errors.
Fix errors following latest codes.

### API Changes ###

 - ACR:

### CODE REVIEW

**Review by wb0716 — APPROVED** [review]
Good for me

**Review by wanchao-xu — APPROVED** [review]
Looks good to me

**Review by zhouleonlei — APPROVED** [review]
lgtm

**Review by xiaowei-guan — APPROVED** [review]
LGTM

**Review by hinohie — APPROVED** [review]
Oops. Sorry for this. Looks Good To Me.

**Comment by xuelian-bai** [comment]
looks good to me

**Review by zg2nets — APPROVED** [review]
looks good！

**Pull request merged**
