### PR TITLE
[NUI] Fix null pointer svace issue

### PR DESCRIPTION
**Pull request by zhouleonlei**
### Description of Change ###

http://168.219.243.174:12000/sb2/main/review#PRJID=1&WGID=38820

### API Changes ###

 - ACR:

### CODE REVIEW

**Review by dongsug-song — APPROVED** [review]

**Review by dongsug-song — APPROVED** [review]
looks good to me

**Review by elishateng — COMMENTED** [review]
LGTM

**Review by xiaowei-guan — COMMENTED** [review]
LGTM

**Review by AchoWang — COMMENTED** [review]
Looks good to me.

**Review by wb0716 — COMMENTED** [review]
Good for me

**Review by AdunFang — COMMENTED** [review]
It is OK.

**Review by huayongxu — COMMENTED** [review]
lgtm

**Pull request merged**
