### PR TITLE
[NUI] Add EnableFrameCache in LottieAnimationView

### PR DESCRIPTION
**Pull request by tscholb**
### Description of Change ###

https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-adaptor/+/300511/
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-toolkit/+/300510/
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-extension/+/300509/
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/302105/

### API Changes ###

 - ACR:

### CODE REVIEW

**Review by hinohie — APPROVED** [review]
Approve. But please rebasr this commit.

**Comment by hinohie** [comment]
And please add some description for relative DALi patches/for trace history

**Review by dongsug-song — APPROVED** [review]
looks good to me.
from next time, please remove `@` in comments. 
`/// <summary>
        /// @brief Whether to animated image visual uses fixed cache or not.
        /// @details type Propert
`
I don't know the purpose of `@`.
maybe, you can use `<remark> </remark>` tag. 
thank you.

**Comment by tscholb** [comment]
> looks good to me. from next time, please remove `@` in comments. `/// <summary> /// @brief Whether to animated image visual uses fixed cache or not. /// @details type Propert ` I don't know the purpose of `@`. maybe, you can use `<remark> </remark>` tag. thank you.

Thank you :)

**Pull request merged**
