### PR TITLE
[NUI] remove unused Xamarin style classes

### PR DESCRIPTION
**Pull request by dasg34**
NUI doesn't support Xamarin style classes.

Instead, use `Tizen.NUI.BaseComponents.ViewStyle`.

### API Changes ###

 - ACR:

### CODE REVIEW

**Comment by dasg34** [comment]
ping

**Comment by dasg34** [comment]
Can we remove unused classes?

**Review by rabbitfor — APPROVED** [review]
LGTM. But I think it needs to check if the `Style` is not used at all (VD) before merging it.

**Comment by rabbitfor** [comment]
@AdunFang Can you review this?

**Review by huayongxu — APPROVED** [review]
looks good to me.

**Review by hyunjushin — CHANGES_REQUESTED** [review]
Please re-push this patch into DevelNUI branch.

**Comment by dasg34** [comment]
See https://github.com/Samsung/TizenFX/pull/2184 instead.

**Pull request closed without merging**
