### PR TITLE
[NUI] Fix Null pointer svace issue

### PR DESCRIPTION
**Pull request by zhouleonlei**
### Description of Change ###

http://168.219.243.174:12000/sb2/main/review#PRJID=1&WGID=38820

### API Changes ###

 - ACR:

### CODE REVIEW

**Review by dongsug-song — APPROVED** [review]
looks good to me

**Review by elishateng — APPROVED** [review]
LGTM

**Review by xiaowei-guan — APPROVED** [review]
LGTM

**Review by AchoWang — APPROVED** [review]
Looks good to me.

**Review by wb0716 — APPROVED** [review]
Good for me

**Review by Seoyeon2Kim — APPROVED** [review]

**Review by zg2nets — APPROVED** [review]
lgtm

**Comment by Seoyeon2Kim** [comment]
This PR also needs to resolve the conflicts.

**Review by huayongxu — APPROVED** [review]
lgtm

**Pull request closed without merging**
