### PR TITLE
[NUI] Fix scroll  build error

### PR DESCRIPTION
**Pull request by zhouleonlei**
### Description of Change ###
Fix scroll  build error

### CODE REVIEW

**Review by zg2nets — APPROVED** [review]
Looks good to me！

**Review by AchoWang — APPROVED** [review]
Looks good to me.

**Review by AdunFang — APPROVED** [review]
It is OK.

**Review by elishateng — APPROVED** [review]
LGTM

**Review by huayongxu — APPROVED** [review]
looks good to me.

**Pull request merged**
