### PR TITLE
[NUI][NUI.Devel] Update TCs of NUI.Devel.

### PR DESCRIPTION
**Pull request by AchoWang**
### Description of Change ###
1. Fixed failed TCs.
2. Add new TCs.

### API Changes ###

 - ACR:

### CODE REVIEW

**Review by AdunFang — APPROVED** [review]
It is OK.

**Review by zhouleonlei — APPROVED** [review]
lgtm

**Review by xuelian-bai — APPROVED** [review]
looks good to me

**Review by zg2nets — APPROVED** [review]
lgtm

**Review by wanchao-xu — APPROVED** [review]
Looks good to me

**Review by wb0716 — APPROVED** [review]
Good for me

**Review by xiaowei-guan — APPROVED** [review]
LGTM

**Review by elishateng — APPROVED** [review]
LGTM

**Pull request closed without merging**
