### PR TITLE
[NUI][XamlBuild] Support use root node inheirt nest type

### PR DESCRIPTION
**Pull request by AdunFang**
### Description of Change ###
Support use root node inheirt nest type

Sample
xaml:
`<l:CustomForNestView-CustomView x:Class="Tizen.NUI.Examples.NestedTypeTestPage"`

c#:
`public partial class NestedTypeTestPage : CustomForNestView.CustomView`

### API Changes ###

 - ACR:

### CODE REVIEW

**Review by zhouleonlei — APPROVED** [review]
lgtm

**Review by huayongxu — APPROVED** [review]
lgtm

**Review by zg2nets — APPROVED** [review]
lgtm

**Review by xiaowei-guan — APPROVED** [review]
LGTM

**Review by elishateng — APPROVED** [review]
LGTM

**Review by AchoWang — APPROVED** [review]
Looks good to me.

**Review by dongsug-song — APPROVED** [review]
looks good to me

**Comment by myroot** [comment]
https://stackoverflow.com/questions/4269896/creating-an-instance-of-a-nested-class-in-xaml/51006566

**Pull request merged**
