### PR TITLE
[EXaml] Support use static value as argument

### PR DESCRIPTION
**Pull request by AdunFang**
### API Changes ###

 - ACR:

### CODE REVIEW

**Review by zg2nets — APPROVED** [review]
lgtm

**Review by xuelian-bai — APPROVED** [review]
looks good to me

**Review by xiaowei-guan — APPROVED** [review]
LGTM

**Review by elishateng — APPROVED** [review]
LGTM

**Review by wanchao-xu — APPROVED** [review]
Looks good to me

**Review by wb0716 — APPROVED** [review]
Good for me

**Review by AchoWang — APPROVED** [review]
Looks good to me.

**Comment by dongsug-song** [comment]
@AdunFang 
Hello,
The TizenFX master branch has been changed for API11(tizen_7.5).
So the DevelNUI branch also did a hard reset with the master branch to sync this.
I think you need to rebase this PR or re-upload the new PR.
I am sorry for the inconvenience.

**Pull request closed without merging**
