### PR TITLE
[NUI] Change menu icon based on the latest Icon UX

### PR DESCRIPTION
**Pull request by jaehyun0cho**
### API Changes ###

 - ACR:

### CODE REVIEW

**Review by taehyub — APPROVED** [review]
LGTM :)

**Review by Seoyeon2Kim — CHANGES_REQUESTED** [review]
LGTM

**Review by Seoyeon2Kim — APPROVED** [review]
LGTM!!!!

**Comment by Seoyeon2Kim** [comment]
> LGTM

Ignore this one please! :(

**Pull request merged**
