### PR TITLE
Fix SVACE issues.

### PR DESCRIPTION
**Pull request by huayongxu**
### API Changes ###

 - ACR:

### CODE REVIEW

**Review by wb0716 — APPROVED** [review]
Good for me

**Review by zg2nets — APPROVED** [review]
Good

**Review by xuelian-bai — APPROVED** [review]
looks good to me

**Review by hyue7 — APPROVED** [review]

**Review by dongsug-song — APPROVED** [review]
approved

**Review by AchoWang — COMMENTED** [review]
Looks good to me.

**Review by xiaowei-guan — COMMENTED** [review]
LGTM

**Pull request merged**
