### PR TITLE
[NUI][API8] Binding TextFitChanged event + Add TextMapHelper for TextFit

### PR DESCRIPTION
**Pull request by hinohie**
This patch is backpropagate patch of #3770 and #3764

This patch required below dali codes :
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-toolkit/+/269448/
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/269454/

Signed-off-by: Eunki, Hong <eunkiki.hong@samsung.com>

### CODE REVIEW

**Review by JoogabYun — APPROVED** [review]

**Review by wonrst — APPROVED** [review]
It works fine on tizen 6.0

**Review by everLEEst — APPROVED** [review]
Looks good to me. sorry for approved yet it is nomerge taged..

**Review by Seoyeon2Kim — APPROVED** [review]
As Sanghyun mentioned, please remove "No Merge" tag.

**Comment by hinohie** [comment]
We got some feedback that this patch (actually, TextFit structer and TextMapHelper) is too heavy to attach in API8.
Close now, but can reopen if someone need to use it.

**Pull request closed without merging**
