### PR TITLE
[NUI] Fixed Svace issues

### PR DESCRIPTION
**Pull request by zhouleonlei**
### Description of Change ###
Fixed Svace issues

### CODE REVIEW

**Review by AchoWang — APPROVED** [review]
Looks good to me.

**Review by huayongxu — APPROVED** [review]
lgtm

**Review by elishateng — APPROVED** [review]
LGTM

**Review by zg2nets — APPROVED** [review]
LGTM

**Review by AdunFang — COMMENTED** [review]
It is OK.

**Pull request merged**
