### PR TITLE
Add xaml loaded and XNames 

### PR DESCRIPTION
**Pull request by elishateng**
### Description of Change ###

1. Add XamlLoaded event for NUIApplication
2. Add XNames for Element

### API Changes ###

 - ACR:

### CODE REVIEW

**Review by wb0716 — APPROVED** [review]
Good for me

**Review by xiaowei-guan — APPROVED** [review]
LGTM

**Review by huayongxu — COMMENTED** [review]
lgtm

**Review by zhouleonlei — APPROVED** [review]
LGTM

**Review by AchoWang — APPROVED** [review]
Looks good to me.

**Review by xuelian-bai — APPROVED** [review]
looks good to me

**Review by AdunFang — APPROVED** [review]
It is OK.

**Review by dongsug-song — APPROVED** [review]
looks good to me.
from next time, please add sample app or code snip as an example to show how it can be used.

**Pull request merged**
