### PR TITLE
[NUI] Fix svace issue

### PR DESCRIPTION
**Pull request by zhouleonlei**
### API Changes ###

 - ACR:

### CODE REVIEW

**Review by elishateng — APPROVED** [review]
LGTM

**Review by huayongxu — COMMENTED** [review]
lgtm

**Review by AdunFang — APPROVED** [review]
It is OK.

**Comment by Seoyeon2Kim** [comment]
Could you describe what SVACE issue is in detail?
Also, please resolve the conflict.

**Comment by zhouleonlei** [comment]
WID:10286392 Value background, which was dereferenced in method call background.Find(), is compared with null
These codes have been deleted in lastest API9 version.
I will close it

**Pull request closed without merging**
