### PR TITLE
[NUI] Add Images(public) TCs.

### PR DESCRIPTION
**Pull request by AchoWang**
### Description of Change ###
Add TCs for public/Images/* .

### API Changes ###

 - ACR:

### CODE REVIEW

**Review by elishateng — APPROVED** [review]
LGTM

**Review by huayongxu — APPROVED** [review]
lgtm

**Review by zg2nets — APPROVED** [review]
looks good~

**Review by zhouleonlei — APPROVED** [review]
LGTM

**Review by AdunFang — APPROVED** [review]
It is OK.

**Review by dongsug-song — APPROVED** [review]
looks good to me

**Pull request merged**
