### PR TITLE
[NUI] Implement some new APIs of webcontext.

### PR DESCRIPTION
**Pull request by huayongxu**
This patch is to implement some new APIs of webcontext, such as
GetWebStorageOrigins, GetFormPasswordList, etc.

### API Changes ###

 - ACR:

### CODE REVIEW

**Review by zg2nets — COMMENTED** [review]
please add related patch link of dali-csharp-binder

**Comment by huayongxu** [comment]
This patch is related to the patch at csharp-binder side:
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/254840/

**Review by dongsug-song — APPROVED** [review]
looks good to me

**Review by zg2nets — APPROVED** [review]
lgtm!

**Pull request merged**
