### PR TITLE
[NUI] Fix GetProperty ambiguousmatch exception

### PR DESCRIPTION
**Pull request by elishateng**
### Description of Change ###

1. Fix GetProperty ambiguousmatch exception

### API Changes ###

 - ACR:

### CODE REVIEW

**Comment by xuelian-bai** [comment]
looks good to me

**Review by xiaowei-guan — APPROVED** [review]
LGTM

**Review by zhouleonlei — APPROVED** [review]
LGTM

**Review by AchoWang — APPROVED** [review]
Looks good to me.

**Review by AdunFang — APPROVED** [review]
It is OK.

**Review by AchoWang — APPROVED** [review]
Good,

**Review by dongsug-song — APPROVED** [review]
looks good to me

**Review by zg2nets — APPROVED** [review]
lgtm

**Review by Seoyeon2Kim — APPROVED** [review]

**Pull request merged**
