### PR TITLE
[NUI] fix tc fail for TextMapHelper

### PR DESCRIPTION
**Pull request by wonrst**
Property of InputFilter and Placeholder returns PropertyMap of index base.
So GetHiddenInputStruct() and GetPlaceholderStruct() can parse the index base map.

Signed-off-by: Bowon Ryu <bowon.ryu@samsung.com>

### CODE REVIEW

**Review by AchoWang — APPROVED** [review]
Looks good to me.

**Comment by AchoWang** [comment]
Hi， @wonrst 

I think you should check the TCs continue,  such as  in case TextMapHelperGetTextFitMap, 

"Assert.AreEqual(fontSizeType, "PointSize", "Should be equal!");    "    , will got failed too, 

I check the code, the first character will be lower-cased ( why ?)

so the true result is pointSize , but not PointSize, 

Thanks!

**Comment by AchoWang** [comment]
And case TextMapHelperGetTextFitStruct

Assert.AreEqual(FontSizeType.PixelSize, "PointSize", "Should be equal!");   =>  is not correct, 

ummm...
Anyway, please check them, thanks!

**Comment by wonrst** [comment]
> And case TextMapHelperGetTextFitStruct
> 
> Assert.AreEqual(FontSizeType.PixelSize, "PointSize", "Should be equal!"); => is not correct,
> 
> ummm... Anyway, please check them, thanks!

The issue case has been fixed. Thanks!

**Review by dongsug-song — APPROVED** [review]
looks good to me

**Pull request merged**
