### PR TITLE
[NUI][AT-SPI] Add AccessibilityInterface.Selection

### PR DESCRIPTION
**Pull request by aswigon**
### Description of Change ###

AT-SPI Selection interface
https://developer.gnome.org/libatspi/stable/libatspi-atspi-selection.html

**Note**: Currently labelled as draft until other PRs are merged (additional methods for the EditableText interface and ScrollToChild).

### Dependencies
- https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-adaptor/+/258913/
- https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/258915/

### API Changes ###

 - ACR: None

### CODE REVIEW

**Review by m-bialota — COMMENTED** [review]
Looks good to me.

**Comment by Seoyeon2Kim** [comment]
Dear @aswigon ,
Could you resolve the conflict today? 
Then, we can review this PR.

**Review by Seoyeon2Kim — APPROVED** [review]
Looks good to me for Selection interface.

**Comment by m-bialota** [comment]
The code looks OK to me.

**Review by m-bialota — APPROVED** [review]
Looks good to me

**Review by everLEEst — APPROVED** [review]
LGTM

**Pull request merged**
