### PR TITLE
[NUI] Fix wrong thumb position in Scrollbar.

### PR DESCRIPTION
**Pull request by elishateng**
### Description of Change ###
Fix wrong thumb position in Scrollbar.

### API Changes ###

 - ACR:

### CODE REVIEW

**Review by zhouleonlei — APPROVED** [review]
LGTM

**Review by zg2nets — APPROVED** [review]
looks good to me！

**Review by huayongxu — APPROVED** [review]
lgtm.

**Review by AdunFang — APPROVED** [review]
It is OK.

**Review by rabbitfor — APPROVED** [review]
LGTM

**Comment by dongsug-song** [comment]
@elishateng 
Hello, 
sorry, I couldn't merge this PR because, "Rebase and merge" button had been inactivated.
please fix or upload new same PR again.
thank you.

image

**Pull request merged**
