### PR TITLE
[NUI] Add Common(public) TCs.

### PR DESCRIPTION
**Pull request by AchoWang**
### Description of Change ###
Add TCs of public\Common.

### API Changes ###

 - ACR:

### CODE REVIEW

**Review by zhouleonlei — APPROVED** [review]
LGTM

**Review by AdunFang — APPROVED** [review]
It is OK.

**Review by wb0716 — APPROVED** [review]
Good

**Review by huayongxu — APPROVED** [review]
lgtm.

**Review by elishateng — APPROVED** [review]
LGTM

**Review by dongsug-song — APPROVED** [review]
LGTM

**Pull request merged**
