### PR TITLE
[NUI] Remove unused field in View

### PR DESCRIPTION
**Pull request by rabbitfor**
### Description of Change ###
This patch is to remove unused field in View. Since View is frequenstly used so it always need to be compact.

### API Changes ###

 - ACR:

### CODE REVIEW

**Review by hinohie — APPROVED** [review]
Oh.. good point

**Review by Seoyeon2Kim — APPROVED** [review]
LGTM~
Could you add a description and go to the next step?

**Review by everLEEst — APPROVED** [review]
LGTM

**Comment by rabbitfor** [comment]
> LGTM~ Could you add a description and go to the next step?

Thank you for your suggestion. I added description about the patch :)

**Pull request merged**
