### PR TITLE
[NUI] Fix tct fail issues

### PR DESCRIPTION
**Pull request by dongsug-song**
### Description of Change ###
[NUI] Fix tct fail issues

### API Changes ###
https://github.com/Samsung/TizenFX/pull/1983 : this PR has been merged without ACR accepted, so it is reverted.

### CODE REVIEW

**Review by huiyueun — APPROVED** [review]

**Comment by m-macias** [comment]
Dear @dongsug-song why has this pull request been merged and why does it changes even more than it says so in the description? #1983 does have the existing AND accepted ACR (TCSACR-372). Additionally you have reverted the #2001 changes that also have accepted ACR (TCSACR-375). Every revert action after that should require an ACR, however those changes has not been released yet so it could be simplified, but nonetheless I don't like this PR.

**Comment by dongsug-song** [comment]
@m-macias 
Hello,
I am sorry for bad description for this patch. 
I will update description now.
please refer to it later.
thank you.

**Comment by m-macias** [comment]
I see your reasoning for the #2001, although it was already accepted and in my opinion those issues should have been detected during the development of the API. Nonetheless it is has not been released so have a possibility to modify it. 

I still don't agree with the revert of the #1983, because it was accepted by the API Reviewer. The only fault was that the API developer has not included the necessary information in the pull request description. 
Maybe @WonyoungChoi could tell us his opinion. The author of #1983 asked me about the merge of those changes a few days earlier after it was accepted and there are multiple accepted pull requests that received "ACR Accepted" label after they have been merged on github.

**Comment by dongsug-song** [comment]
@m-macias 
I apologize my arbitrary behavior without your review
I will add https://github.com/Samsung/TizenFX/pull/1983 patch again soon.

**Pull request merged**
