### PR TITLE
[NUI] Rebase develnui (DevelNUI only patches --> master)

### PR DESCRIPTION
**Pull request by hinohie**
Signed-off-by: Eunki, Hong eunkiki.hong@samsung.com

### CODE REVIEW

**Comment by hinohie** [comment]
I'll remove "NO MERGE" tags after TCT test done.

**Comment by hinohie** [comment]
TCT test done.

**Review by Seoyeon2Kim — APPROVED** [review]
LGTM. So many files there are! lol

**Comment by everLEEst** [comment]
Looks good to me.

**Review by everLEEst — APPROVED** [review]

**Pull request merged**
