### PR TITLE
[NUI]First use own bindingcontext

### PR DESCRIPTION
**Pull request by elishateng**
### Description of Change ###

1. First use own bindingcontext,if not, then use inherit bindingcontext

### API Changes ###

 - ACR:

### CODE REVIEW

**Review by dongsug-song — APPROVED** [review]
approved

**Comment by myroot** [comment]
It change from original code you need to check side effect
https://github.com/xamarin/Xamarin.Forms/blob/70e57274a2a1a010795eb1f9d2e1d857d7bfb4eb/Xamarin.Forms.Core/BindableObject.cs#L30

**Comment by myroot** [comment]
If you have test set of binding features, please do test it and show the result

**Comment by elishateng** [comment]
> If you have test set of binding features, please do test it and show the result

Hi, This patch will be reverted in https://github.com/Samsung/TizenFX/pull/4298.

**Pull request merged**
