### PR TITLE
[EXaml] Support import xaml to ResourceDictionary in EXaml

### PR DESCRIPTION
**Pull request by AdunFang**
### Description of Change ###

Support import xaml to ResourceDictionary.
Sample:

```
<?xml version="1.0" encoding="UTF-8" ?>
<View x:Class="Tizen.NUI.Examples.TestStaticDynamicResourcePage"
  xmlns="http://tizen.org/Tizen.NUI/2018/XAML"
  xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml">

    <View.XamlResources>
        <ResourceDictionary x:Name="res1" Source="Resource.xaml"/>
    </View.XamlResources>

  <ImageView x:Name="img1" ResourceUrl="{StaticResource urlKey}" Position2D="{DynamicResource positionKey}" />
</View>
```

### API Changes ###

 - ACR:

### CODE REVIEW

**Review by wb0716 — APPROVED** [review]
Good for me

**Review by zhouleonlei — APPROVED** [review]
lgtm

**Review by xuelian-bai — APPROVED** [review]
looks good to me

**Review by huayongxu — APPROVED** [review]
lgtm

**Review by zg2nets — APPROVED** [review]
lgtm

**Review by elishateng — APPROVED** [review]
LGTM

**Review by wanchao-xu — APPROVED** [review]
Looks good to me

**Review by dongsug-song — APPROVED** [review]
approved

**Pull request merged**
