### PR TITLE
[NUI] Add sound feedback and fix scroll build errors

### PR DESCRIPTION
**Pull request by zhouleonlei**
### Description of Change ###
Add sound feedback and fix scroll build errors

### CODE REVIEW

**Review by AchoWang — APPROVED** [review]
Looks good to me.

**Review by AdunFang — APPROVED** [review]
It is OK.

**Review by elishateng — APPROVED** [review]
LGTM

**Review by huayongxu — APPROVED** [review]
lgtm.

**Review by dongsug-song — APPROVED** [review]
it has already been reviewed in DevelNUI
looks good to me

**Pull request merged**
