### PR TITLE
[NUI] fix svace issue

### PR DESCRIPTION
**Pull request by zhouleonlei**
### Description of Change ###

Add null pointer checking

### API Changes ###

 - ACR:

### CODE REVIEW

**Review by zg2nets — APPROVED** [review]
lgtm

**Review by huayongxu — APPROVED** [review]
lgtm

**Review by xuelian-bai — APPROVED** [review]
looks good to me

**Review by AdunFang — APPROVED** [review]
It is OK.

**Review by elishateng — APPROVED** [review]
LGTM

**Review by dongsug-song — APPROVED** [review]
looks good to me

**Pull request merged**
