### PR TITLE
[NUI] Fix CA2000 issues for Visual

### PR DESCRIPTION
**Pull request by zhouleonlei**
### Description of Change ###
Fix CA2000 issues for Visual

### API Changes ###

 - ACR:

### CODE REVIEW

**Review by huayongxu — APPROVED** [review]
lgtm.

**Review by AdunFang — APPROVED** [review]
It is OK.

**Review by rabbitfor — APPROVED** [review]
LGTM

**Review by elishateng — COMMENTED** [review]
LGTM

**Pull request merged**
