### PR TITLE
[NUI] Fix SVACE issue.

### PR DESCRIPTION
**Pull request by huayongxu**
### API Changes ###

 - ACR:

### CODE REVIEW

**Review by AchoWang — APPROVED** [review]
Looks good to me.

**Review by elishateng — APPROVED** [review]
LGTM

**Review by hyue7 — APPROVED** [review]

**Review by wb0716 — APPROVED** [review]
Good for me

**Review by wanchao-xu — APPROVED** [review]
Looks good to me

**Review by hinohie — APPROVED** [review]

**Review by xuelian-bai — APPROVED** [review]
looks good to me

**Review by xiaowei-guan — APPROVED** [review]
LGTM

**Review by xiaowei-guan — COMMENTED** [review]
LGTM

**Pull request merged**
