### PR TITLE
[NUI] Fix svace issue

### PR DESCRIPTION
**Pull request by zhouleonlei**
### Description of Change ###

Null pointer checking

### API Changes ###

 - ACR:

### CODE REVIEW

**Review by xiaowei-guan — APPROVED** [review]
LGTM

**Review by elishateng — APPROVED** [review]
LGTM

**Review by AchoWang — APPROVED** [review]
Looks good to me.

**Review by xuelian-bai — APPROVED** [review]
looks good to me

**Review by wb0716 — APPROVED** [review]
Good for me

**Review by dongsug-song — APPROVED** [review]
looks good to me

**Pull request merged**
