### PR TITLE
[NUI] Fix svace issue

### PR DESCRIPTION
**Pull request by zhouleonlei**
### API Changes ###

 - ACR:

### CODE REVIEW

**Review by elishateng — APPROVED** [review]
LGTM

**Review by huayongxu — COMMENTED** [review]
lgtm

**Review by AdunFang — APPROVED** [review]
It is OK.

**Comment by xuelian-bai** [comment]
looks good to me

**Review by dongsug-song — APPROVED** [review]
looks good to me

**Pull request merged**
