### PR TITLE
[NUI] Add EditableBrowsable.Never for CurrentLoadedXaml

### PR DESCRIPTION
**Pull request by elishateng**
### Description of Change ###

1. Add EditableBrowsable.Never for CurrentLoadedXaml

### API Changes ###

 - ACR:

### CODE REVIEW

**Review by huayongxu — APPROVED** [review]
lgtm

**Review by xuelian-bai — APPROVED** [review]
looks good to me

**Review by AdunFang — APPROVED** [review]
It is OK.

**Review by zhouleonlei — APPROVED** [review]
LGTM

**Review by AchoWang — APPROVED** [review]
Looks good to me.

**Review by zg2nets — APPROVED** [review]
lgtm

**Review by Seoyeon2Kim — APPROVED** [review]

**Review by wb0716 — COMMENTED** [review]
Good for me

**Review by AdunFang — COMMENTED** [review]
It is OK

**Review by xiaowei-guan — COMMENTED** [review]
LGTM

**Review by xuelian-bai — COMMENTED** [review]
looks good to me

**Pull request merged**
