### PR TITLE
[NUI] Fix some typo and grammar mistake

### PR DESCRIPTION
**Pull request by bshsqa**
Signed-off-by: seungho <sbsh.baek@samsung.com>

### CODE REVIEW

**Review by hinohie — APPROVED** [review]
Fine. LGTM

**Review by tscholb — APPROVED** [review]

**Review by tscholb — COMMENTED** [review]
LGTM

**Review by Seoyeon2Kim — APPROVED** [review]
Approved to fix typo.

**Comment by dkdk-ryu** [comment]
LGTM.

**Pull request merged**
