### PR TITLE
[NUI] Fix svace issue

### PR DESCRIPTION
**Pull request by zhouleonlei**
### API Changes ###

 - ACR:

### CODE REVIEW

**Review by wb0716 — APPROVED** [review]
Good for me

**Review by AdunFang — APPROVED** [review]
It is OK.

**Comment by xuelian-bai** [comment]
looks good to me

**Review by xiaowei-guan — APPROVED** [review]
LGTM

**Review by zg2nets — APPROVED** [review]
lgtm

**Review by AchoWang — APPROVED** [review]
Looks good to me.

**Review by Seoyeon2Kim — APPROVED** [review]
Approved. This PR is to fix svace issue, null check :)

**Review by elishateng — APPROVED** [review]
LGTM

**Pull request merged**
