### PR TITLE
[NUI] Remove build warning - CA1055

### PR DESCRIPTION
**Pull request by huiyueun**
CA1055: URI return values should not be strings
https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1055

Signed-off-by: huiyu.eun <huiyu.eun@samsung.com>

### API Changes ###

 - ACR:

### CODE REVIEW

**Comment by bshsqa** [comment]
Patch is good. But if it can, it is better to remove the method.

**Comment by dongsug-song** [comment]
@huiyueun 
could you resolve the conflicts above?
then I will review and merge.
thank you.

**Comment by huiyueun** [comment]
I've modified conflict

**Review by dongsug-song — APPROVED** [review]
looks good to me

**Pull request merged**
