### PR TITLE
[NUI] Fix Svace issues

### PR DESCRIPTION
**Pull request by AdunFang**
### Description of Change ###

Fix Svace issues.

### API Changes ###

 - ACR:

### CODE REVIEW

**Review by AchoWang — APPROVED** [review]
Looks good to me.

**Review by zg2nets — APPROVED** [review]
It's good!

**Review by elishateng — APPROVED** [review]
LGTM

**Review by zhouleonlei — APPROVED** [review]
LGTM

**Comment by huiyueun** [comment]
I'm just wondering what kind of svace does this modification deal with.

**Review by dongsug-song — APPROVED** [review]
looks good to me

**Pull request merged**
