### PR TITLE
[NUI] Refine codes to reduce code duplicaton

### PR DESCRIPTION
**Pull request by elishateng**
### Description of Change ###

1. Optimize enum code snippets;
2. Refactor InputMethodContext.EventData, InputMethodContext.CallbackData and ScrollView.SnapEvent to inherit Disposable class.

### API Changes ###

 - ACR: http://suprem.sec.samsung.net/jira/browse/TCSACR-292

### CODE REVIEW

**Comment by dongsug-song** [comment]
@elishateng 
Hello,
because of the following changed APIs, "ACR Required" tag seems to be attached.
please check.
thank you.


  /// <since_tizen> 5 </since_tizen>
  Tizen.NUI.InputMethodContext/EventData

  /// <since_tizen> 5 </since_tizen>
  Tizen.NUI.InputMethodContext/CallbackData

- /// <since_tizen> 5 </since_tizen>
- System.Void Tizen.NUI.InputMethodContext/CallbackData::Dispose()

- /// <since_tizen> 5 </since_tizen>
- System.Void Tizen.NUI.InputMethodContext/EventData::Dispose()

- /// <since_tizen> 5 </since_tizen>
- System.Void Tizen.NUI.InputMethodContext/EventData::Finalize()

- /// <since_tizen> 5 </since_tizen>
- System.Void Tizen.NUI.InputMethodContext/CallbackData::Finalize()

- /// <since_tizen> 5 </since_tizen>
- System.Boolean Tizen.NUI.InputMethodContext/EventData::disposed

- /// <since_tizen> 5 </since_tizen>
- System.Boolean Tizen.NUI.InputMethodContext/CallbackData::disposed

**Comment by hyunjushin** [comment]
Please update ACR. We can [Delete] only deprecated APIs before two earlier versions.

**Comment by dongsug-song** [comment]
@elishateng 
Hello, Mr. Teng
as you know, we can not REMOVE APIs before DEPRECATE.
first we DEPRECATE by ACR, second maintain this Deprecated API for next two versions and then we REMOVE that API.
please chekc the Ms. Shin's comment in the TCSACR.
thank you.

**Comment by elishateng** [comment]
> @elishateng
> Hello, Mr. Teng
> as you know, we can not REMOVE APIs before DEPRECATE.
> first we DEPRECATE by ACR, second maintain this Deprecated API for next two versions and then we REMOVE that API.
> please chekc the Ms. Shin's comment in the TCSACR.
> thank you.

Hello, Mr. SSong, 
I think I just refactor these apis.

**Comment by dongsug-song** [comment]
http://suprem.sec.samsung.net/jira/browse/TCSACR-292 is accepted, so I merge.

**Pull request merged**
