### PR TITLE
[NUI][XamlBuild] 1.Support DP value, 2.Support DataTemplate in EXaml

### PR DESCRIPTION
**Pull request by AdunFang**
### Description of Change ###
Sync https://github.com/Samsung/TizenFX/pull/4005 from API9.

### API Changes ###

 - ACR:

### CODE REVIEW

**Review by zhouleonlei — APPROVED** [review]
lgtm

**Review by huayongxu — APPROVED** [review]
lgtm

**Review by elishateng — APPROVED** [review]
LGTM

**Comment by dongsug-song** [comment]
@AdunFang 
Hello, thank you for the fix.
but could you mention here that any test or verification has been done?
from next time, could you add some test case or sample APP to verify.

and, how about this?
https://github.com/Samsung/TizenFX/pull/4004
this patch also seems to be related to DataTemplate issue.
if this is useless, please close it for yourself.
thank you.

**Review by zg2nets — APPROVED** [review]
lgtm

**Review by dongsug-song — APPROVED** [review]
looks good to me

**Pull request merged**
