### PR TITLE
[Tizen][API10] Add WebView APIs for fullscreen, text found, etc.

### PR DESCRIPTION
**Pull request by huayongxu**
### API Changes ###

 - ACR:

### CODE REVIEW

**Review by xiaowei-guan — APPROVED** [review]
LGTM

**Review by elishateng — APPROVED** [review]
LGTM

**Review by AchoWang — APPROVED** [review]
Looks good to me.

**Review by xuelian-bai — APPROVED** [review]
looks good to me

**Comment by zhouhao02** [comment]
looks good to me

**Review by wb0716 — APPROVED** [review]
Good for me

**Review by dongsug-song — APPROVED** [review]
looks good to me
(please add a description for every patch)

**Review by wanchao-xu — COMMENTED** [review]
Looks good to me

**Pull request merged**
