### PR TITLE
[NUI][EXaml] Support FactoryMethod in EXaml (JIRE 2305)

### PR DESCRIPTION
**Pull request by AdunFang**
### Description of Change ###

Associated with the link https://github.com/nui-dali/Tizen.NUI.XamlBuild/pull/8。

Support factory method, so that user can create object by singleton method.

Sample
Xaml:
```
<?xml version="1.0" encoding="UTF-8" ?>
<View x:Class="Tizen.NUI.Examples.XFactoryMethodPage"
  xmlns="http://tizen.org/Tizen.NUI/2018/XAML"
  xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
  BackgroundColor="White">

  <WidgetView x:FactoryMethod="CreateWidgetView">
    <x:Arguments>
      <x:String>widget-efl.example</x:String>
      <x:String></x:String>
      <x:Int32>450</x:Int32>
      <x:Int32>700</x:Int32>
      <x:Single>-1</x:Single>
    </x:Arguments>
  </WidgetView>
</View>
```

C#:
User can define the method CreateWidgetView in the type of object which need to be created
```
    public class WidgetView : View
    {
        public static WidgetView CreateWidgetView(string widgetId, string contentInfo, int width, int height, float updatePeriod)
        {
            //return WidgetViewManager.Instance.AddWidget(widgetId, contentInfo, width, height, updatePeriod);
            return new WidgetView(widgetId, contentInfo, width, height, updatePeriod);
        }
```

or user can define the method CreateWidgetView in the type whose suffix is "Extension", this code can be added anywhere
```
namespace Tizen.NUI
{
    public static class WidgetViewExtension
    {
        public static WidgetView CreateWidgetView(string widgetId, string contentInfo, int width, int height, float updatePeriod)
        {
            return WidgetViewManager.Instance.AddWidget(widgetId, contentInfo, width, height, updatePeriod);
        }
    }
}
```

### API Changes ###

 - ACR:

### CODE REVIEW

**Review by elishateng — APPROVED** [review]
LGTM

**Review by zhouleonlei — APPROVED** [review]
LGTM

**Review by AchoWang — APPROVED** [review]
Looks good to me.

**Comment by dongsug-song** [comment]
@AdunFang 
Hello, 
I have question. in your explanation, you said that **_"or user can define the method CreateWidgetView in the type whose suffix is "Extension", this code can be added anywhere"_**. the word of "Extension" is reserved? if so, we can not add WidgetViewExtension class which has other functionality in the future? 
I was confused.

**Comment by AdunFang** [comment]
> @AdunFang
> Hello,
> I have question. in your explanation, you said that **_"or user can define the method CreateWidgetView in the type whose suffix is "Extension", this code can be added anywhere"_**. the word of "Extension" is reserved? if so, we can not add WidgetViewExtension class which has other functionality in the future?
> I was confused.

**Comment by AdunFang** [comment]
> @AdunFang
> Hello,
> I have question. in your explanation, you said that **_"or user can define the method CreateWidgetView in the type whose suffix is "Extension", this code can be added anywhere"_**. the word of "Extension" is reserved? if so, we can not add WidgetViewExtension class which has other functionality in the future?
> I was confused.

Hi, Mr. Song
The XXXExtension is the grammar of C # definition, it let user can add method to type.
For example:

```
using Tizen.NUI.Test1;
using Tizen.NUI.Test2;

namespace Tizen.NUI
{
    public class A
    {
    }
}

namespace Tizen.NUI.Test1
{
    public static class AExtension
    {
        public static void TestAddedMethod1(this A a, int p)
        {
        }
    }
}

namespace Tizen.NUI.Test2
{
    public static class AExtension
    {
        public static void TestAddedMethod2(this A a, int p)
        {

        }
    }
}

namespace Tizen.NUI.Examples
{
    public class XamlPageDemo : NUIApplication
    {
        public void OnPrevCreate()
        {
            var a = new A();
            a.TestAddedMethod1(1);
            a.TestAddedMethod2(2);
            XamlPage.PreLoad(this);
        }
    }
}
```

So I think user defined an extension class does not affect other code.

**Comment by dongsug-song** [comment]
@AdunFang 
OK. Thank you for your explanation~

**Review by dongsug-song — APPROVED** [review]
looks good to me

**Pull request merged**
