### PR TITLE
[NUI] Add Application(Internal & Public) TCs.

### PR DESCRIPTION
**Pull request by AchoWang**
### Description of Change ###
1. Add Application(Internal & Public) TCs.
2. Fix some other issues for /public/common/Property*.

### API Changes ###

 - ACR:

### CODE REVIEW

**Review by elishateng — APPROVED** [review]
LGTM

**Review by zhouleonlei — APPROVED** [review]
LGTM

**Review by huayongxu — APPROVED** [review]
lgtm.

**Review by zg2nets — APPROVED** [review]
looks good to me, but please do not use "other issues", plz write specific issue next tim.

**Pull request merged**
