### PR TITLE
Revert "Remove ReleaseFunction enum at PixelData (#3436)"

### PR DESCRIPTION
**Pull request by JSUYA**
This reverts commit c2951987b9232e1fe24c8d2d98334fbb3ed03327.

### API Changes ###

 - ACR: no

### CODE REVIEW

**Review by hinohie — APPROVED** [review]
Looks god to me. I'll fix legacy case soon

**Review by dongsug-song — APPROVED** [review]
revert patch, looks good to me

**Comment by dongsug-song** [comment]
@JSUYA 
please submit the same patch in DevelNUI.

**Comment by JSUYA** [comment]
> @JSUYA
> please submit the same patch in DevelNUI.

I uploaded dali-csharp-binder patch, to the tizen Branch.
Therefore, devel/master and DevelNUI patches will handle @hinohie

**Comment by hinohie** [comment]
> > @JSUYA
> > please submit the same patch in DevelNUI.
> 
> I uploaded dali-csharp-binder patch, to the tizen Branch.
> Therefore, devel/master and DevelNUI patches will handle @hinohie

I'll upload master -> DevelNUI sync patch, and after, upload fix code

**Pull request merged**
