### PR TITLE
[NUI] Fix NUI and wearable svace issues

### PR DESCRIPTION
**Pull request by zhouleonlei**
### Description of Change ###
Fix NUI and wearable svace issues

### API Changes ###

 - ACR:

### CODE REVIEW

**Review by wb0716 — APPROVED** [review]

**Review by AchoWang — APPROVED** [review]
Looks  good to me.

**Review by zg2nets — APPROVED** [review]
looks good！

**Review by huayongxu — APPROVED** [review]
lgtm.

**Review by elishateng — APPROVED** [review]
LGTM

**Review by elishateng — APPROVED** [review]
LGTM

**Review by AdunFang — APPROVED** [review]
It is OK.

**Review by huiyueun — APPROVED** [review]

**Pull request merged**
