### PR TITLE
[NUI][AT-SPI] Add API for blocking automatic Bridge initialization

### PR DESCRIPTION
**Pull request by aswigon**
### Description of Change ###

Dependencies:
- https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-adaptor/+/256959/ (merged)
- https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-adaptor/+/258012/ (merged)
- https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/257536/ (merged)

This is meant to be used by applications that start before DBus is available.

```
static void Main(string[] args)
{
    Accessibility.BridgeDisableAutoInit();
    // Rest of application code
}


// When DBus is available
Accessibility.BridgeEnableAutoInit();
```

### API Changes ###

 - ACR: None

### CODE REVIEW

**Review by Seoyeon2Kim — COMMENTED** [review]
Looks good to me, but I'll approve this PR after all dali patches related to Bridge initialization are merged.

**Comment by dongsug-song** [comment]
@aswigon 
Hello,
The dali patches seem not to be review and merged yet. so I put the **\*\*NO MERGE\*\*** label on this PR now.
You can remove **\*\*NO MERGE\*\*** label for yourself when this PR is ready to be reviewed and merged.
(**\*\*NO MERGE\*\*** label has no restriction to submit PR or to edit this patch. Just for notification and marking)
Thank you.

**Comment by aswigon** [comment]
Ready to merge (DALi dependencies have been merged).

**Review by Seoyeon2Kim — APPROVED** [review]
Looks good to me.
All dali patches are merged now, so this PR is ready to merge.

**Pull request merged**
