### PR TITLE
[NUI][AT-SPI] Apply AccessibilityHidden to Switch

### PR DESCRIPTION
**Pull request by aswigon**
### Description of Change ###

The AT-SPI subtree of `Switch` can be optimized to a single leaf node, i.e. from:

```
[[:1.12:0xb8f74838],[toggle button],[toolkit=nui(dali)],[(class=Switch)(automationId=toggleButton1)],[20,650,182,44],[Toggle1],[(ENABLED)(FOCUSABLE)(SENSITIVE)(SHOWING)(VISIBLE)(HIGHLIGHTED)(HIGHLIGHTABLE)],[]]
  [[:1.12:0xb8d238e0],[image],[toolkit=nui(dali)],[(class=ImageView)],[20,650,84,44],[],[(ENABLED)(SENSITIVE)(SHOWING)(VISIBLE)],[]]
    [[:1.12:0xb8d241e8],[image],[toolkit=nui(dali)],[(class=ImageView)],[20,650,44,44],[],[(ENABLED)(SENSITIVE)(SHOWING)(VISIBLE)],[]]
```

to

```
[[:1.17:0xb8a957d0],[toggle button],[toolkit=nui(dali)],[(class=Switch)(automationId=toggleButton1)],[20,650,182,44],[Toggle1],[(ENABLED)(FOCUSABLE)(SENSITIVE)(SHOWING)(VISIBLE)(HIGHLIGHTED)(HIGHLIGHTABLE)],[]]
```

because its children are useless to clients such as Screen Reader anyway.

### API Changes ###

 - ACR: None

### CODE REVIEW

**Review by lol-github — APPROVED** [review]
LGTM, these are only decorative elements, hence can be hidden and make a tree more compact.

**Review by Seoyeon2Kim — APPROVED** [review]
LGTM, thanks!

**Review by jaehyun0cho — APPROVED** [review]
LGTM

**Review by everLEEst — APPROVED** [review]
Looks good to me.

**Comment by Seoyeon2Kim** [comment]
"With that PR the Switch control uses 33% of the original memory usage on Screen Reader side (1 tree node instead of 3)"

**Pull request merged**
