### PR TITLE
[NUI]Revert temporary patch that fix DA build error

### PR DESCRIPTION
**Pull request by dasg34**
This reverts commit 44c1dfe00c765eb794e5d85a19d7b2518e9e6444 and
commit ef7737bd45966655c0b557dd8d091291fdb7cb5c.

### API Changes ###

 - ACR:

### CODE REVIEW

**Comment by dasg34** [comment]
@rabbitfor Please merge this patch if there is no error in DA build~

**Comment by huiyueun** [comment]
Please put '[NUI]' in the title.

**Comment by dongsug-song** [comment]
@AdunFang 
Hello, 
could you please check if this patch resolve the fhub build error?
please confirm in your side then we can merge this.
thank you.

**Review by AdunFang — APPROVED** [review]
It is OK.

**Pull request merged**
