### PR TITLE
[NUI] Add Common(Public) TCs

### PR DESCRIPTION
**Pull request by AchoWang**
### Description of Change ###
/public/Common/Extents.cs
/public/Common/TypeInfo.cs
/public/Common/Property*.cs

### API Changes ###

 - ACR:

### CODE REVIEW

**Review by wb0716 — APPROVED** [review]
Good for me

**Review by elishateng — APPROVED** [review]
LGTM

**Review by huayongxu — APPROVED** [review]
lgtm

**Review by AdunFang — APPROVED** [review]
It is OK.

**Pull request merged**
