### PR TITLE
Fix NUIApplication svace issue 

### PR DESCRIPTION
**Pull request by elishateng**
### Description of Change ###

1. Fix NUIApplication svace issue  (DF230418-00755)

### API Changes ###

 - ACR: None

### CODE REVIEW

**Review by huayongxu — APPROVED** [review]
lgtm

**Review by huayongxu — APPROVED** [review]
lgtm

**Review by AchoWang — APPROVED** [review]
Looks good to me.

**Review by hyue7 — APPROVED** [review]

**Review by zg2nets — APPROVED** [review]
Good Job~

**Review by zg2nets — APPROVED** [review]
Good Job~

**Review by dongsug-song — APPROVED** [review]
approved

**Pull request merged**
