### PR TITLE
[NUI][TCSACR-588] Deprecated Scrollable and ScrollViewEffect classes

### PR DESCRIPTION
**Pull request by dongsug-song**
### Description of Change ###
Deprecate unnecessary and unused classes. (based on https://github.sec.samsung.net/NUI/home/issues/16 )

- public APIs

Scrollable
ScrollViewEffect

Additionally, I would like to remove other unused classes that are not part of the public API (hidden or internal APIs). 
These are not ACR targets, but I am documenting them here to maintain history.
**_Therefore, please review only the two classes above for ACR, and ignore the following classes._**

- hidden APIs

CubeTransitionEffect.cs
ItemView.cs
ItemViewBindableProperty.cs
ScrollView.cs
ScrollViewBindableProperty.cs
ScrollViewEvent.cs
ScrollViewPagePathEffect.cs
Interop.CubeTransitionEffect.cs
Interop.ItemView.cs

- internal APIs

ScrollViewSnapStartedSignal.cs
SnapType.cs

### API Changes ###
https://jira.sec.samsung.net/browse/TCSACR-588

## please note the following!
The dll name of Tizen.NUI.Samples has been changed as "NuiSample.dll". Therefore, please modify the file "launch.json" as shown below and start the nui ubuntu backend VisualStudio Code debug. Thank you.

"program": "${workspaceFolder}/bin/Debug/**[your dotnet framework in Ubuntu]**/NuiSample.dll"

my sample =>
            "name": ".NET Core Launch (console)",
            "type": "coreclr",
            "request": "launch",
            "preLaunchTask": "build",
            "program": "${workspaceFolder}/bin/Debug/net6.0/NuiSample.dll",

### CODE REVIEW

**Comment by wiertel** [comment]
This change is confusing. The title says classes are being removed but I see a lot of simple refactoring, cleaning. Some file moved. A bot is listing removed methods but I don't see them being touched in this PR. I will figure it out, but please confirm that this is actually the PR that removes Scrollable API.

**Comment by dongsug-song** [comment]
> This change is confusing. The title says classes are being removed but I see a lot of simple refactoring, cleaning. Some file moved. A bot is listing removed methods but I don't see them being touched in this PR. I will figure it out, but please confirm that this is actually the PR that removes Scrollable API.

Hello, Thank you very much for checking. you are absolutely right. I will modify the ACR and also this patch, so please hold your review. thank you.

**Comment by dongsug-song** [comment]
@wiertel 
Hello, I have revised this patch.
please review again. 
Thank you in advance.

**Review by wiertel — APPROVED** [review]
Deprecation is fine.

**Review by hinohie — APPROVED** [review]
ACR Approved

**Pull request merged**
