### PR TITLE
[NUI][TEST] Fix StyleGuide examples

### PR DESCRIPTION
**Pull request by Seoyeon2Kim**
Signed-off-by: Seoyeon Kim <seoyeon2.kim@samsung.com>

### Description of Change ###
- `MenuItem` : Need to call Dispose() for all items when the app disposes
- `ScrollableBase` : All items should get focused
- `Switch` : Feedback property is only for mobile target

### API Changes ###
- N/A

### CODE REVIEW

**Review by dongsug-song — APPROVED** [review]
approved

**Review by jaehyun0cho — APPROVED** [review]
LGTM

**Comment by dongsug-song** [comment]
@Seoyeon2Kim 
"This branch cannot be rebased due to conflicts" error msg
=> by this, can not be merged, please resolve the conflict.

**Comment by Seoyeon2Kim** [comment]
Dear @dongsug-song , 
I tried to check what the conflict is, but there wasn't. So, I merged this one.
If there's something wrong, please let me know!

**Pull request merged**
