### PR TITLE
[NUI] Fix GetProperty ambiguousmatch exception

### PR DESCRIPTION
**Pull request by elishateng**
### Description of Change ###

1. Fix GetProperty ambiguousmatch exception

### API Changes ###

 - ACR:

### CODE REVIEW

**Review by zhouleonlei — APPROVED** [review]
lgtm

**Review by AdunFang — APPROVED** [review]
It is OK.

**Review by dongsug-song — APPROVED** [review]
looks good to me

**Review by AchoWang — COMMENTED** [review]
Looks good to me.

**Pull request merged**
