### PR TITLE
[NUI] Fix svace issue

### PR DESCRIPTION
**Pull request by zhouleonlei**
### Description of Change ###

Add null pointer checking

### API Changes ###

 - ACR:

### CODE REVIEW

**Comment by xuelian-bai** [comment]
looks good to me

**Review by AdunFang — APPROVED** [review]
It is OK.

**Review by huayongxu — APPROVED** [review]
lgtm

**Review by elishateng — APPROVED** [review]
LGTM

**Review by zg2nets — APPROVED** [review]
lgtm

**Review by dongsug-song — APPROVED** [review]
looks good to me

**Pull request merged**
