### PR TITLE
[NUI][NUI.Devel] Update nui line coverage TCs.

### PR DESCRIPTION
**Pull request by AchoWang**
### Description of Change ###
Main change:
1. Fix build errors.
2. Fix failed cases.
3. Correct incorrect usage， such as RenderTaskList ， GaussianBlurView and so on.
4. Add privileges for DebugLogging, BorderWindow and so on.
5. Add some new cases.
6. Fix warning issues.

### API Changes ###

 - ACR:

### CODE REVIEW

**Review by zg2nets — APPROVED** [review]
lgtm

**Review by AdunFang — APPROVED** [review]
It is OK.

**Review by wb0716 — APPROVED** [review]
Good for me

**Review by wanchao-xu — APPROVED** [review]
Looks good to me

**Review by dongsug-song — APPROVED** [review]
approved

**Pull request merged**
