### PR TITLE
[NUI] Fix CA2000 issue in DefaultTheme(Dispose object before losing scope)

### PR DESCRIPTION
**Pull request by AchoWang**
### Description of Change ###
Fix CA2000 issue in DefaultTheme

### API Changes ###

 - ACR:

### CODE REVIEW

**Review by zhouleonlei — APPROVED** [review]
LGTM

**Review by zhouleonlei — APPROVED** [review]
LGTM

**Review by AdunFang — APPROVED** [review]
It is OK.

**Review by elishateng — APPROVED** [review]
LGTM

**Pull request merged**
