### PR TITLE
[NUI] Fix errors of NUI line coverage TCs.

### PR DESCRIPTION
**Pull request by AchoWang**
### Description of Change ###
Fix errors of NUI line coverage TCs.

### API Changes ###

 - ACR:

### CODE REVIEW

**Review by dongsug-song — APPROVED** [review]
looks good to me

**Review by zg2nets — COMMENTED** [review]
lgtm

**Review by xiaowei-guan — COMMENTED** [review]
good

**Review by huayongxu — COMMENTED** [review]
lgtm

**Review by wb0716 — COMMENTED** [review]
Good for me

**Pull request merged**
