### PR TITLE
[NUI][AT-SPI] Introduce AtspiEvents

### PR DESCRIPTION
**Pull request by kimcinoo**
The AtspiEvents can be used for the event mask to suppress
specific event.

This is the second version to provide AtspiEvents.
The first version is
https://github.com/Samsung/TizenFX/pull/4019

Dependency:
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/272794/
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-adaptor/+/272184/

### CODE REVIEW

**Comment by dongsug-song** [comment]
@kimcinoo 
does this PR have to merged after the first patch (https://github.com/Samsung/TizenFX/pull/4019) has been merged?

@aswigon @Seoyeon2Kim 
Hello, please review this pr also. it seems to be related to https://github.com/Samsung/TizenFX/pull/4019
and I could see active reviews of yours there.

**Comment by dongsug-song** [comment]
> @dongsug-song No. If this PR is approved and merged then I will abandon #4019

Thank you for the answer, but could you upload some sample App or test case for the newly added apis?

**Review by lol-github — APPROVED** [review]
LGTM

**Review by everLEEst — APPROVED** [review]
Looks good to me :)

**Comment by kimcinoo** [comment]
> > @dongsug-song No. If this PR is approved and merged then I will abandon #4019
> 
> Thank you for the answer, but could you upload some sample App or test case for the newly added apis?

A sample to test API was added. Please review and merge if there is not a problem.

**Pull request merged**
