### PR TITLE
[NUI] Unregister callbacks when passed argument is null.

### PR DESCRIPTION
**Pull request by huayongxu**
### API Changes ###

 - ACR:

### CODE REVIEW

**Review by AchoWang — APPROVED** [review]
Looks good to me

**Review by wb0716 — APPROVED** [review]
Good for me

**Review by wanchao-xu — APPROVED** [review]
Looks good to me

**Review by xiaowei-guan — APPROVED** [review]
LGTM

**Review by hyue7 — APPROVED** [review]

**Review by elishateng — APPROVED** [review]
LGTM

**Review by dongsug-song — APPROVED** [review]
approved

**Review by xiaowei-guan — COMMENTED** [review]
LGTM

**Pull request merged**
