### PR TITLE
[NUI] Fix svace issues

### PR DESCRIPTION
**Pull request by elishateng**
### Description of Change ###

1. Fix svace issues

### API Changes ###

 - ACR: None

### CODE REVIEW

**Review by zg2nets — APPROVED** [review]
lgtm

**Review by wb0716 — APPROVED** [review]
Good for me

**Review by hyue7 — APPROVED** [review]

**Review by xiaowei-guan — APPROVED** [review]
LGTM

**Review by AchoWang — APPROVED** [review]
Looks good to me.

**Review by dongsug-song — APPROVED** [review]
approved

**Pull request merged**
