### PR TITLE
[NUI] Fix svace issues

### PR DESCRIPTION
**Pull request by zhouleonlei**
### Description of Change ###

Null pointer checking

### API Changes ###

 - ACR:

### CODE REVIEW

**Review by xiaowei-guan — APPROVED** [review]

**Review by huayongxu — APPROVED** [review]
lgtm

**Comment by xuelian-bai** [comment]
looks good to me

**Review by xiaowei-guan — APPROVED** [review]
LGTM

**Review by wb0716 — APPROVED** [review]
Good for me

**Review by AchoWang — APPROVED** [review]
Looks good to me.

**Review by elishateng — APPROVED** [review]
LGTM

**Review by zg2nets — APPROVED** [review]
lgtm

**Review by everLEEst — APPROVED** [review]
Looks Good to me.

**Review by AdunFang — COMMENTED** [review]
It is OK.

**Pull request merged**
