### PR TITLE
[NUI] Make webcontext/cookiemanager static.

### PR DESCRIPTION
**Pull request by huayongxu**
### Description of Change ###

The related patch at csharp-binder side:
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/277709/

### API Changes ###

 - ACR:

### CODE REVIEW

**Comment by myroot** [comment]
The orignal ewk API can create a new web context and it could be used for a new web view.

a default web context could be provide as static but some webview can use another web context instead of default web context.
so you should not assumed that all webview has same web context

**Comment by huayongxu** [comment]
This patch is to fix the issue 
https://github.sec.samsung.net/dotnet/NUIBackend/issues/169
web context is shared among web views, is not created by web view itself.
when web engine(chromium-efl) is integrated into dali-extension,  default context is a singleton actually,

**Comment by myroot** [comment]
> web context is shared among web views, is not created by web view itself.

It is a default behavior. as default WebView use a default web context. but original EWK API provide to create web view with a new web context.
http://ewebkit.github.io/ewebkit-doc/ewebkit2/html/d6/daf/ewk__view_8h.html#aa06060a9c00fa46acd92095de688ed61

And I asked the web team to add these API to C#.

**Comment by myroot** [comment]
Anyway, currently NUI WebView API is not support to create WebContext, so this changes acceptable. 
But in the future, this structure should be refactored to allow multiple web context

**Review by zg2nets — APPROVED** [review]
looks good to me

**Review by elishateng — APPROVED** [review]
LGTM

**Review by AchoWang — APPROVED** [review]
Looks good to me.

**Review by dongsug-song — APPROVED** [review]
approved

**Pull request merged**
