### PR TITLE
[NUI] Support bind a property without BindableProperty

### PR DESCRIPTION
**Pull request by AdunFang**
### API Changes ###

 - ACR:

### CODE REVIEW

**Comment by xuelian-bai** [comment]
looks good to me

**Review by zg2nets — APPROVED** [review]
lgtm

**Review by huayongxu — APPROVED** [review]
lgtm

**Review by elishateng — APPROVED** [review]
LGTM

**Review by wb0716 — COMMENTED** [review]
Good for me

**Review by AchoWang — COMMENTED** [review]
Looks good to me.

**Pull request closed without merging**
