### PR TITLE
[NUI] Fix SVACE issue

### PR DESCRIPTION
**Pull request by dongsug-song**
### Description of Change ###

[NUI] Fix SVACE issue
https://analysishub.sec.samsung.net/dm/tizen/sb2/main/review#PRJID=1284&WGID=711497

### API Changes ###
nothing

### CODE REVIEW

**Review by taehyub — APPROVED** [review]
LGTM

**Review by jaehyun0cho — COMMENTED** [review]
I think that source? is not required because it is not null.

**Comment by dongsug-song** [comment]
> I think that source? is not required because it is not null.

Thank you for review.
could you teach me why the `source` never become null?

**Comment by jaehyun0cho** [comment]
> > I think that source? is not required because it is not null.
> 
> Thank you for review. could you teach me why the `source` never become null?

In the following case, if source == null is true, then it returns.
So source is not null when source?.DirtyProperties == null and source?.DirtyProperties?.Count == 0 is checked.
In the same way, source?.DirtyProperties is not null when source?.DirtyProperties?.Count == 0 is checked.
```
if (source == null || source?.DirtyProperties == null || source?.DirtyProperties?.Count == 0)
```

**Comment by dongsug-song** [comment]
> > > I think that source? is not required because it is not null.
> > 
> > 
> > Thank you for review. could you teach me why the `source` never become null?
> 
> In the following case, if source == null is true, then it returns. So source is not null when source?.DirtyProperties == null and source?.DirtyProperties?.Count == 0 is checked. In the same way, source?.DirtyProperties is not null when source?.DirtyProperties?.Count == 0 is checked.
> 
> ```
> if (source == null || source?.DirtyProperties == null || source?.DirtyProperties?.Count == 0)
> ```

thank you for kind explanation.
I have fixed as you mentioned.
thank you again

**Review by jaehyun0cho — APPROVED** [review]
LGTM

**Pull request merged**
