### PR TITLE
[NUI] Add public theme TCs

### PR DESCRIPTION
**Pull request by zhouleonlei**
### Description of Change ###
Add public theme TCs

### API Changes ###

 - ACR:

### CODE REVIEW

**Review by elishateng — APPROVED** [review]
LGTM

**Review by wb0716 — APPROVED** [review]
Good for me

**Review by zg2nets — APPROVED** [review]
looks good

**Review by elishateng — APPROVED** [review]
LGTM

**Review by dongsug-song — APPROVED** [review]
looks good to me

**Pull request merged**
