### PR TITLE
[NUI] Fix crash issue when favicon is null.

### PR DESCRIPTION
**Pull request by huayongxu**
### API Changes ###

 - ACR:

### CODE REVIEW

**Review by rabbitfor — APPROVED** [review]
LGTM. Please also make PR for API8 branch too.

**Review by zg2nets — COMMENTED** [review]
lgtm

**Review by zg2nets — COMMENTED** [review]
lgtm

**Review by xiaowei-guan — COMMENTED** [review]
LGTM

**Review by AchoWang — COMMENTED** [review]
Looks good to me.

**Review by zhouleonlei — COMMENTED** [review]
LGTM

**Pull request merged**
