### PR TITLE
[NUI] Add manually set api10 20220530

### PR DESCRIPTION
**Pull request by elishateng**
### Description of Change ###

1. Make context as manually set in SetValue function of BindableObject.
2. Revert first use own binding context changes.

### API Changes ###

 - ACR: None

### CODE REVIEW

**Review by xiaowei-guan — APPROVED** [review]
LGTM

**Review by zhouleonlei — APPROVED** [review]
lgtm

**Review by AdunFang — APPROVED** [review]
It is OK.

**Review by AchoWang — APPROVED** [review]
Looks good to me.

**Review by zg2nets — APPROVED** [review]
looks good~

**Review by dongsug-song — APPROVED** [review]
approved

**Pull request merged**
