### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by JoonghyunCho**
### Description of Change ###

Test checkers

### CODE REVIEW

**Comment by JoonghyunCho** [comment]
Can one of the admins verify this patch?

**Comment by JoonghyunCho** [comment]
Can one of the admins verify this patch?

**Comment by JoonghyunCho** [comment]
Can one of the admins verify this patch?

**Comment by JoonghyunCho** [comment]
Can one of the admins verify this patch?

**Comment by JoonghyunCho** [comment]
Can one of the admins verify this patch?

**Comment by wantfire** [comment]
Is your patch deleting just one blank line? Right?

**Comment by JoonghyunCho** [comment]
Can one of the admins verify this patch?

**Pull request closed without merging**
