### PR TITLE
[NUI] Fix dispose xaml elements

### PR DESCRIPTION
**Pull request by elishateng**
### Description of Change ###

1. Fix dispose xaml elements.
```
<A x:Name ... >
    <A.B>
        <C x:Name="xxx"  .../>
    </A.B>
</A>
```
In this case, if node C is not the direct child of node A, then node C can't be disposed in DisposeXamlElements function, due to the IsCreateByXaml  property of the parent of node C is false.
   

### API Changes ###

 - ACR: None.

### CODE REVIEW

**Review by AchoWang — APPROVED** [review]
Looks good to me.

**Review by xuelian-bai — APPROVED** [review]
looks good to me

**Review by zg2nets — APPROVED** [review]
lgtm

**Review by wanchao-xu — APPROVED** [review]
Looks good to me

**Review by wb0716 — APPROVED** [review]
Good for me

**Review by dongsug-song — APPROVED** [review]
approved

**Review by xiaowei-guan — COMMENTED** [review]
LGTM

**Pull request merged**
