### PR TITLE
Revert "[NUI] Fix tct fail issues (#2012)"

### PR DESCRIPTION
**Pull request by dongsug-song**
### Description of Change ###
Revert "[NUI] Fix tct fail issues (#2012)"
- This reverts commit 1f3c2b0ed05f80f6c3985eefcd0ee3c72f2f7987.
- This requires sync release with https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/243855/
- All revert patches in https://github.com/Samsung/TizenFX/pull/2012 are recovered if this is merged
- TCSACR-375 has been accepted

### API Changes ###
https://code.sec.samsung.net/jira/browse/TCSACR-375

### CODE REVIEW

**Comment by dongsug-song** [comment]
@m-macias 
Hello, please review this.
Thank you.

**Review by AdunFang — APPROVED** [review]
It's OK,
won't cause the build error of FH.NUI.

**Comment by dongsug-song** [comment]
@m-macias
Hello, could approve this?
if you don't mind, please proceed immediately. 
NUI release is pending for now.
Thank you.

**Comment by m-macias** [comment]
I am sorry, I didn't receive any notice. I approve those changes, because they revert the API to the state that was approved during the ACR process. I am thankful that the issues related to #1983 and #2001 were resolved successfully.

**Pull request merged**
