### PR TITLE
[NUI] Add Transition (internal / public) TCs.

### PR DESCRIPTION
**Pull request by AchoWang**
### Description of Change ###
Add TCs for internal(public) / Transition. 

### API Changes ###

 - ACR:

### CODE REVIEW

**Review by elishateng — APPROVED** [review]
LGTM

**Review by zhouleonlei — APPROVED** [review]
LGTM

**Review by wb0716 — APPROVED** [review]
GLGTM

**Review by AdunFang — APPROVED** [review]
It is OK.

**Pull request closed without merging**
