### PR TITLE
[NUI] Add Xaml line info for bindable object

### PR DESCRIPTION
**Pull request by elishateng**
### Description of Change ###

1. Add Xaml line info for bindable object.

### API Changes ###

 - ACR:

### CODE REVIEW

**Review by huayongxu — APPROVED** [review]
lgtm

**Review by wb0716 — APPROVED** [review]
Good for me

**Review by xuelian-bai — APPROVED** [review]
looks good to me

**Review by AdunFang — APPROVED** [review]
It is OK.

**Review by zhouleonlei — APPROVED** [review]
LGTM

**Review by AchoWang — COMMENTED** [review]
Looks good to me.

**Review by zg2nets — APPROVED** [review]
lgtm

**Review by xiaowei-guan — APPROVED** [review]
LGTM

**Review by zg2nets — APPROVED** [review]
lgtm

**Review by dongsug-song — APPROVED** [review]
looks good to me

**Pull request merged**
