### PR TITLE
[NUI][Xaml] Fix issue of call SetBinding in c# code

### PR DESCRIPTION
**Pull request by elishateng**
### Description of Change ###

1. Fix issue of call SetBinding in c# code (Same with the patch https://github.com/Samsung/TizenFX/pull/4056)

### API Changes ###

 - ACR:

### CODE REVIEW

**Comment by xuelian-bai** [comment]
looks good to me

**Review by AdunFang — APPROVED** [review]
It is OK.

**Review by zhouleonlei — APPROVED** [review]
lgtm

**Review by AchoWang — APPROVED** [review]
Looks good to me.

**Review by everLEEst — APPROVED** [review]
Looks good to me.

**Review by huayongxu — APPROVED** [review]
lgtm

**Comment by dongsug-song** [comment]
@elishateng 
Hello, 
the related patch of https://github.com/Samsung/TizenFX/pull/4056/files looks be changed and has more files changed.
please check further. 
thank you.

**Pull request merged**
