### PR TITLE
[NUI] Fix to make null assigning to ResourceUrl possible

### PR DESCRIPTION
**Pull request by dongsug-song**
### Description of Change ###
[NUI] Fix to make null assigning to ResourceUrl possible

### API Changes ###
N/A

### CODE REVIEW

**Comment by dongsug-song** [comment]
this is the fix to allow null assigning on ResourceUrl property

**Comment by myroot** [comment]
I think this PR make not allow null assign. 
becuase, Can't store a null value into ResourceUrl
``` c#
obj.ResourceUrl = null;
var shuldbeTrue = obj.ResourceUrl == null;
//shuldebeTrue is false
```

**Comment by dongsug-song** [comment]
thank you for reviewing, but this ResourceUrl null assigning has been allowed form tizen_4.0 by requesting of VD. this is kind of action to reset ResourceUrl then ImageView discards previous picture shown to show nothing finally.

**Comment by myroot** [comment]
How about update `propertyChanged` callback of `ResourceUrl` and `UpdateImage` method to handle null

**Pull request merged**
