### PR TITLE
[NUI] remove redundant private field in View class

### PR DESCRIPTION
**Pull request by dasg34**
No logical changes.

### API Changes ###

 - ACR:

### CODE REVIEW

**Review by huiyueun — APPROVED** [review]

**Review by Seoyeon2Kim — COMMENTED** [review]
Just my curiosity :
To compare the stored value with the new one is not needed anymore?

**Comment by dasg34** [comment]
> 
> 
> Just my curiosity :
> To compare the stored value with the new one is not needed anymore?

To compare the stored value with the new one is here.
https://github.com/Samsung/TizenFX/pull/2513/files#diff-3a6cc61b4675d29e45559f8549a9f1de25b398206cbf83a891760c83e1c9cd0cR2006-R2007

`value` is new one and `widthPolicy` is stored value.

**Comment by Seoyeon2Kim** [comment]
> > Just my curiosity :
> > To compare the stored value with the new one is not needed anymore?
> 
> To compare the stored value with the new one is here.
> https://github.com/Samsung/TizenFX/pull/2513/files#diff-3a6cc61b4675d29e45559f8549a9f1de25b398206cbf83a891760c83e1c9cd0cR2006-R2007
> 
> `value` is new one and `widthPolicy` is stored value.

Oh I missed the lines!
Thanks, and approved this PR.

**Review by Seoyeon2Kim — APPROVED** [review]
LGTM!

**Pull request merged**
