### PR TITLE
[NUI] Update NUI.Devel to fix block and crash issues.

### PR DESCRIPTION
**Pull request by AchoWang**
### Description of Change ###
Update NUI.Devel to fix block and crash issues.

### API Changes ###

 - ACR:

### CODE REVIEW

**Review by zhouleonlei — APPROVED** [review]
LGTM

**Review by xiaowei-guan — APPROVED** [review]
LGTM

**Review by elishateng — APPROVED** [review]
LGTM

**Review by dongsug-song — APPROVED** [review]
looks good to me

**Review by wb0716 — COMMENTED** [review]
Good for me

**Review by XuWanchaoS — COMMENTED** [review]
looks good to me

**Pull request merged**
