### PR TITLE
[NUI][XamlBuild] Support DateTime

### PR DESCRIPTION
**Pull request by AdunFang**
### Description of Change ###
Support DateTime.

### API Changes ###

 - ACR:

### CODE REVIEW

**Comment by xuelian-bai** [comment]
looks good to me

**Review by wanchao-xu — APPROVED** [review]
Looks good to me

**Review by AchoWang — APPROVED** [review]
Looks good to me.

**Review by wb0716 — APPROVED** [review]
Good for me

**Review by dongsug-song — APPROVED** [review]
looks good to me

**Pull request merged**
