### PR TITLE
[NUI] suppress CA1801 build warnings from auto-generated SWIG code

### PR DESCRIPTION
**Pull request by id213sin**
### Description of Change ###

Suppress CA1801 build warnings from auto-generated SWIG code.

### CODE REVIEW

**Review by Seoyeon2Kim — COMMENTED** [review]
Is this PR to add attributes which suppress a message, "unused parameters"?
(https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1801)

**Comment by id213sin** [comment]
@Seoyeon2Kim 
Yes. Actually, this patch is not fixing the warning messages. This patch only suppresses the warning messages using the attributes.
I'll update the title of the commit.

**Comment by id213sin** [comment]
> Is this PR to add attributes which suppress a message, "unused parameters"?
> (https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1801)

@Seoyeon2Kim
Yes. Actually, this patch is not fixing the warning messages. This patch only suppresses the warning messages using the attributes.
I'll update the title of the commit.

When SWIG generates java code, it automatically puts @SuppressWarnings("unused") at "futureUse" parameter.
So, I've also put the similar code.

**Review by Seoyeon2Kim — APPROVED** [review]
Approved this PR, but I think other guys must review this.
@dongsug-song , @huiyueun  Could you review this PR please?

**Comment by id213sin** [comment]
@all
Ping!
Could you give me some comments or could you approve the patch if there is no issue?

**Review by AdunFang — APPROVED** [review]
It is OK.

**Comment by dongsug-song** [comment]
@id213sin 
Hello,
yes, they are auto-generated codes. As you know only during the initial time of NUI development, SWIG is utilized and currently manual c# binding is done usually.
As you know, the goal of this removing warning task is to make clean code and improve readibility. 
I don't think it's good idea to suppress warning. of course, if the code fix is very hard and dangerous remove warning is better way. but for this case, I think it's not very hard and code fix has meaning in terms of clean code.
could you check again?
thank you.

**Comment by id213sin** [comment]
> @id213sin
> Hello,
> yes, they are auto-generated codes. As you know only during the initial time of NUI development, SWIG is utilized and currently manual c# binding is done usually.
> As you know, the goal of this removing warning task is to make clean code and improve readibility.
> I don't think it's good idea to suppress warning. of course, if the code fix is very hard and dangerous remove warning is better way. but for this case, I think it's not very hard and code fix has meaning in terms of clean code.
> could you check again?
> thank you.

Thank you for comment.
Actually, my first patch for removing this warning message was removing unused parameter "futureUse" and fix other codes.
It was easy to fix. But, I found this comment at top of those files.
//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

So, I didn't change actual code. To avoid code conflict situation when we upgrade code by merging newly auto-generated code by SWIG. I'm not sure whether we need to upgrade this binding code or not, in the future. But, I thought there is no actual benefit to modify this kind of auto-generated code. And many other projects also keep the same unused parameter, too.

But, if you still think removing this code improve readability a lot, I'll abandon this patch and upload other patch.

**Comment by dongsug-song** [comment]
@id213sin 
Hello,
I fully understand what you meant. and I truly agree with your concern and perspective for maintaining and upgrading.
But we need to get high score for SAM and currently we never use SWIG anymore. and if you see the whole codes briefly, many parts have been re-written as manual binding style and auto-binding generates bad styled codes even though it's convenient. 
when you remove the SWIG code you can remove the warning message that you mentioned. 
I hope you understand the situation and I can say that we have gone too far to come back to SWIG. ㅠ_ㅠ

**Comment by id213sin** [comment]
> @id213sin
> Hello,
> I fully understand what you meant. and I truly agree with your concern and perspective for maintaining and upgrading.
> But we need to get high score for SAM and currently we never use SWIG anymore. and if you see the whole codes briefly, many parts have been re-written as manual binding style and auto-binding generates bad styled codes even though it's convenient.
> when you remove the SWIG code you can remove the warning message that you mentioned.
> I hope you understand the situation and I can say that we have gone too far to come back to SWIG. ㅠ_ㅠ

@dongsug-song 
Thank you for your kind explanation! :+1: 
I understand the situation now. I'll close this PR and upload another patch to fix the code.

**Comment by id213sin** [comment]
New PR is uploaded for this issue.
Please, check the following PR.
https://github.com/Samsung/TizenFX/pull/2315

**Pull request closed without merging**
