### PR TITLE
[NUI] Fix the problems of ScriptUI

### PR DESCRIPTION
**Pull request by AdunFang**
### Description of Change ###

Fix the problems of ScriptUI.
1. The dynamci resource don't working on TextLabel.
2. The dynamci resource don't working on Size2D.
3. Support the Rotation animation on XAML.

### Bugs Fixed ###

- Provide links to bugs here

### API Changes ###

If you have the ACR for changing APIs, put the link of the ACR:
 - ACR: 

If you don't have the ACR, List all API changes here (or just put None), example:

Added:
 - SafeBundleHandle Bundle.SafeBundleHandle { get; } // Property
 - void Bundle.AddItem(string key, string value);

Changed:
 - object Bundle.ReceiveItem(string key) => object Bundle.GetItem(string key);

### Behavioral Changes ###

Describe any non-bug related behavioral changes that may change how users app behaves when upgrading to this version of the codebase.

### CODE REVIEW

**Comment by WonyoungChoi** [comment]
run ABI Checker

**Comment by WonyoungChoi** [comment]
@AdunFang @dongsug-song Please close or rebase this pull request.

**Comment by WonyoungChoi** [comment]
Please rebase this PR or close if not needed more.

**Comment by dongsug-song** [comment]
this is very old patch. not be updated so far.

**Pull request closed without merging**
