### PR TITLE
[NUI][XamlBuild] Support classmodifier in xaml

### PR DESCRIPTION
**Pull request by elishateng**
### Description of Change ###

Support class modifier in xaml.

For example:
xx.xaml: 
\<View x:Class="namespace.MyView" x:ClassModifier="NotPublic"\>
   ...
\</View \>

xx.xaml.cs: 
internal partial MyView : View()
{}

### API Changes ###

 - ACR: None (It won't affect previously function)

### CODE REVIEW

**Review by xiaowei-guan — APPROVED** [review]
LGTM

**Review by zg2nets — APPROVED** [review]
lgtm

**Review by AchoWang — APPROVED** [review]
Looks good to me.

**Review by AchoWang — APPROVED** [review]
Looks good to me.

**Comment by dongsug-song** [comment]
@elishateng 
Hello, please resolve the conflict

**Review by AdunFang — APPROVED** [review]
It is OK.

**Review by dongsug-song — APPROVED** [review]
looks good to me

**Comment by elishateng** [comment]
> @elishateng Hello, please resolve the conflict

Hi, Mr. SSong, resolved.

**Pull request merged**
