### PR TITLE
[NUI] Add Animation(Internal) TCs

### PR DESCRIPTION
**Pull request by AchoWang**
### Description of Change ###
[NUI] Add Animation(internal) TCs

### API Changes ###

 - ACR:

### CODE REVIEW

**Review by wb0716 — APPROVED** [review]
Good for me

**Review by huayongxu — APPROVED** [review]
lgtm.

**Review by elishateng — APPROVED** [review]
LGTM

**Review by zhouleonlei — APPROVED** [review]
LGTM

**Review by dongsug-song — APPROVED** [review]
looks good to me.
from next time, please attach all tizen TCT attributes on each test case.
e.g)
        [Test]
        [Category("P1")]
        [Description("AbsoluteLayout constructor test")]
        [Property("SPEC", "Tizen.NUI.AbsoluteLayout.AbsoluteLayout C")]
        [Property("SPEC_URL", "-")]
        [Property("CRITERIA", "CONSTR")]
        [Property("AUTHOR", "xxx, xxx@samsung.com")]

**Pull request merged**
