### PR TITLE
[NUI] Fix svace issue

### PR DESCRIPTION
**Pull request by zhouleonlei**
### Description of Change ###

https://analysishub.sec.samsung.net/dm/sr03/sb2/main/review#PRJID=124&WGID=7485

### API Changes ###

 - ACR:

### CODE REVIEW

**Comment by xuelian-bai** [comment]
looks good to me

**Review by elishateng — APPROVED** [review]
LGTM

**Review by AdunFang — APPROVED** [review]
It is OK.

**Review by huayongxu — COMMENTED** [review]
lgtm

**Review by AchoWang — APPROVED** [review]
Looks good to me.

**Review by zg2nets — APPROVED** [review]

**Review by dongsug-song — APPROVED** [review]
looks good to me

**Review by zg2nets — COMMENTED** [review]
lgtm

**Pull request merged**
