### PR TITLE
Correct the method names

### PR DESCRIPTION
**Pull request by AdunFang**
### API Changes ###

 - ACR:

### CODE REVIEW

**Review by wb0716 — APPROVED** [review]
Good for me

**Review by AchoWang — APPROVED** [review]
Looks good to me.

**Review by huayongxu — APPROVED** [review]
lgtm

**Review by zg2nets — APPROVED** [review]
lgtm

**Review by elishateng — APPROVED** [review]
LGTM

**Review by wanchao-xu — APPROVED** [review]
Looks good to me

**Comment by xuelian-bai** [comment]
looks good to me

**Review by everLEEst — APPROVED** [review]
LGTM.

**Pull request merged**
