### PR TITLE
[Packagemanager] Fix registering internal event callback

### PR DESCRIPTION
**Pull request by jeremy-jang**
### Description of Change ###
Do not invoke Interop.PackageManager.PackageManagerSetEvent().
This will unset all internal callback information and this may make user cannot
listen the package event completely.

### API Changes ###
N/A

### CODE REVIEW

**Comment by myroot** [comment]
You do better change this guard like `if any event handler was existed, it already registered native event handler, so we can return without registration` 
https://github.com/Samsung/TizenFX/blob/89a8609b76adac2fbbe89c863c290d011e05ef9a/src/Tizen.Applications.PackageManager/Tizen.Applications/PackageManager.cs#L1284-L1285
``` c#
if (s_installEventHandler != null || s_uninstallEventHandler != null || s_updateEventHandler != null || s_moveEventHandler != null || s_clearDataEventHandler != null)
    return;
```

**Comment by jeremy-jang** [comment]
> 
> 
> You do better change this guard like `if any event handler was existed, it already registered native event handler, so we can return without registration`
> 
> https://github.com/Samsung/TizenFX/blob/89a8609b76adac2fbbe89c863c290d011e05ef9a/src/Tizen.Applications.PackageManager/Tizen.Applications/PackageManager.cs#L1284-L1285
> 
> ```cs
> if (s_installEventHandler != null || s_uninstallEventHandler != null || s_updateEventHandler != null || s_moveEventHandler != null || s_clearDataEventHandler != null)
>     return;
> ```

The native event callback have to be registered if the event type is changed. This means that if the new type of event handler registered, we need to register the native event callback again.

**Comment by myroot** [comment]
> The native event callback have to be registered if the event type is changed. This means that if the new type of event handler registered, we need to register the native event callback again.

I can't find any information about this limitation, if it is true, you need to update native API document

https://docs.tizen.org/application/native/guides/app-management/package-manager/#monitor-package-events
https://docs.tizen.org/application/native/api/mobile/5.5/group__CAPI__PACKAGE__MANAGER__MODULE.html#gab32b6f7a5d10afb97d919cfc2f2fbe3a
https://docs.tizen.org/application/native/api/mobile/5.5/group__CAPI__PACKAGE__MANAGER__MODULE.html#gadbc6c45654d9227835d80a8a9dda3042

**Comment by jeremy-jang** [comment]
> 
> 
> > The native event callback have to be registered if the event type is changed. This means that if the new type of event handler registered, we need to register the native event callback again.
> 
> I can't find any information about this limitation, if it is true, you need to update native API document
> Or, fix native api implementation to resolve this limitation
> 
> https://docs.tizen.org/application/native/guides/app-management/package-manager/#monitor-package-events
> https://docs.tizen.org/application/native/api/mobile/5.5/group__CAPI__PACKAGE__MANAGER__MODULE.html#gab32b6f7a5d10afb97d919cfc2f2fbe3a
> https://docs.tizen.org/application/native/api/mobile/5.5/group__CAPI__PACKAGE__MANAGER__MODULE.html#gadbc6c45654d9227835d80a8a9dda3042

Ok, I will add a remark at native API document.

**Review by pjh9216 — APPROVED** [review]

**Pull request merged**
