### PR TITLE
[NUI] Update TCs of NUI.Devel.

### PR DESCRIPTION
**Pull request by AchoWang**
### Description of Change ###
1. Fix build errors base on latest codes.
2. Add new TCs  for Transition 、ApplicationAnimation、 GestureOptions.
3. Update resource file of EXaml.

### API Changes ###

 - ACR:

### CODE REVIEW

**Review by xiaowei-guan — APPROVED** [review]
LGTM

**Review by dongsug-song — APPROVED** [review]
looks good to me

**Review by wb0716 — COMMENTED** [review]
Good for me

**Review by zhouleonlei — COMMENTED** [review]
LGTM

**Review by AdunFang — COMMENTED** [review]
It is OK.

**Pull request merged**
