### PR TITLE
[NUI] Add xaml binding testcases

### PR DESCRIPTION
**Pull request by elishateng**
### Description of Change ###

1. Add xaml binding testcases

### API Changes ###

 - ACR:

### CODE REVIEW

**Comment by xuelian-bai** [comment]
looks good to me

**Review by wb0716 — APPROVED** [review]
Good for me

**Review by huayongxu — COMMENTED** [review]
lgtm

**Review by zhouleonlei — APPROVED** [review]
LGTM

**Review by AchoWang — APPROVED** [review]
Looks good to me.

**Review by dongsug-song — APPROVED** [review]
looks good to me

**Pull request merged**
