### PR TITLE
[NUI] remove margin, padding calculation for AbsoluteLayout child size

### PR DESCRIPTION
**Pull request by dasg34**
Since child position property and dali position property that decides
real position of controls are shared as same property(View.Position),
AbsoluteLayout cannot respect margin, padding for child position. so,
we don't need to calculate size with margin, padding.

### API Changes ###

 - ACR:

### CODE REVIEW

**Comment by dasg34** [comment]
Since Margin, Padding calculation is implemented in `LayoutGroup`,  you can reproduce the bug commit message said with the following code.
When you tried to click button, it will be moved continuously.
```
Window.Instance.WindowSize = new Size2D(500, 700);

View root = new View();
root.WidthSpecification = LayoutParamPolicies.WrapContent;
root.HeightSpecification = LayoutParamPolicies.WrapContent;
root.BackgroundColor = new Color(0.8f, 0.8f, 0.8f, 1.0f);
Window.Instance.GetDefaultLayer().Add(root);

LayoutGroup layoutGroup = new LayoutGroup();
root.Layout = layoutGroup;

Button btn = new Button();
btn.WidthSpecification = 300;
btn.Margin = new Extents(10, 0, 0, 0);
btn.HeightSpecification = 100;
btn.BackgroundColor = new Color(0.9f, 0.5f, 0.3f, 1.0f);
root.Add(btn);

Timer timer = new Timer(100);
timer.Tick += (object source, Timer.TickEventArgs e) =>
{
    layoutGroup.RequestLayout();
    return true;
};
timer.Start();
```

**Comment by dasg34** [comment]
> In web,
> They keep calculating margin and padding while using position:absolute.
> 
> I'm not sure ignoring margin and padding is good way.
> Do other Platform also ignore padding and margin in AbsoulteLayout too?

Xamarin supports margin, padding. also, i'd like to support margin, padding for NUI. but it is not possible because of the bug i said above.

**Comment by neostom432** [comment]
Can merge after resolving conflicts.

**Comment by dasg34** [comment]
Updated :)

**Pull request merged**
