### PR TITLE
[NUI] Update TCs of NUI.Devel.

### PR DESCRIPTION
**Pull request by AchoWang**
### Description of Change ###

Main changes:

1. Add TCs of BaseComponents(public) to improve line coverage.
2. Fix failed cases because of dispose exception.
3. Fix crash issue in TSFrameUpdateCallbackInterface (public/Common).
4. Remove unused cases.

### API Changes ###

 - ACR:

### CODE REVIEW

**Review by elishateng — APPROVED** [review]
LGTM

**Review by zhouleonlei — APPROVED** [review]
LGTM

**Review by wb0716 — APPROVED** [review]
Good for me

**Review by dongsug-song — APPROVED** [review]
looks good to me

**Review by huayongxu — COMMENTED** [review]
lgtm

**Pull request merged**
