### PR TITLE
[NUI][XamlBuild] Fix internal class generate error

### PR DESCRIPTION
**Pull request by elishateng**
### Description of Change ###

1. Fix internal class generate error

For example:
\<flc:ScrollView-ScrollItemLayout x:Name="xBannerLayout"/\>
xaml.g.cs:
public global::Tizen.TV.FLUX.Component.ScrollView-ScrollItemLayout xBannerLayout;
xBannerLayout = global::Tizen.NUI.Binding.NameScopeExtensions.FindByName<global::Tizen.TV.FLUX.Component.ScrollView-ScrollItemLayout>(this, "xBannerLayout");
-->
public global::Tizen.TV.FLUX.Component.ScrollView.ScrollItemLayout xBannerLayout;
xBannerLayout = global::Tizen.NUI.Binding.NameScopeExtensions.FindByName<global::Tizen.TV.FLUX.Component.ScrollView.ScrollItemLayout>(this, "xBannerLayout");

### API Changes ###

 - ACR: None (It won't affect previously function)

### CODE REVIEW

**Review by zhouleonlei — APPROVED** [review]
lgtm

**Review by AchoWang — APPROVED** [review]
Looks good to me.

**Review by huayongxu — APPROVED** [review]
lgtm

**Review by AdunFang — APPROVED** [review]
It is OK.

**Review by dongsug-song — APPROVED** [review]
looks good to me

**Pull request merged**
