### PR TITLE
[NUI] Add public & internal Xaml TCs (partial).

### PR DESCRIPTION
**Pull request by AchoWang**
### Description of Change ###
Add public & internal Xaml TCs (partial).

### API Changes ###

 - ACR:

### CODE REVIEW

**Review by zhouleonlei — APPROVED** [review]
LGTM

**Review by zg2nets — APPROVED** [review]
looks good!

**Review by elishateng — APPROVED** [review]
LGTM

**Comment by dongsug-song** [comment]
@AchoWang 
Hello, please fix the conflicts

**Comment by AchoWang** [comment]
> @AchoWang
> Hello, please fix the conflicts

Done.

**Review by dongsug-song — APPROVED** [review]
looks good to me

**Pull request closed without merging**
