### PR TITLE
[NUI][NUI.Components.Devel] Fix build errors of NUI.Components.Devel.

### PR DESCRIPTION
**Pull request by AchoWang**
Fix build errors of NUI.Components.Devel base on latest codes.

### API Changes ###

 - ACR:

### CODE REVIEW

**Review by AdunFang — APPROVED** [review]
It is OK.

**Review by wanchao-xu — APPROVED** [review]
Looks good to me

**Review by wb0716 — APPROVED** [review]

**Review by zg2nets — APPROVED** [review]
looks good to me~

**Review by xuelian-bai — APPROVED** [review]
looks good to me

**Review by elishateng — APPROVED** [review]
LGTM

**Review by xiaowei-guan — APPROVED** [review]
LGTM

**Review by hyue7 — APPROVED** [review]
looks good

**Review by zhouleonlei — APPROVED** [review]
lgtm

**Review by huayongxu — APPROVED** [review]
lgtm

**Comment by dongsug-song** [comment]
@AchoWang 
Hello,
The TizenFX master branch has been changed for API11(tizen_7.5).
So the DevelNUI branch also did a hard reset with the master branch to sync this.
I think you need to rebase this PR or re-upload the new PR.
I am sorry for the inconvenience.

**Comment by dongsug-song** [comment]
@AchoWang 
Hello,
The TizenFX master branch has been changed for API11(tizen_7.5).
So the DevelNUI branch also did a hard reset with the master branch to sync this.
I think you need to rebase this PR or re-upload the new PR.
I am sorry for the inconvenience.

**Pull request closed without merging**
