### PR TITLE
[NUI][XamlBuild] Fix Xaml issues reported by VD

### PR DESCRIPTION
**Pull request by AdunFang**
### Description of Change ###
Sync https://github.com/Samsung/TizenFX/pull/4046 from API9.

### API Changes ###

 - ACR:

### CODE REVIEW

**Review by AchoWang — APPROVED** [review]
Looks good to me.

**Review by elishateng — APPROVED** [review]
LGTM

**Review by huayongxu — APPROVED** [review]
lgtm

**Review by zhouleonlei — APPROVED** [review]
lgtm

**Comment by dongsug-song** [comment]
@AdunFang 
Hello, 
Thank you for the fix.
but could you write the description?
and could you add sample app or test case to verify this patch?
if this takes time, please upload code snip to show how it can be used or what the difference is.
thank you.

**Review by dongsug-song — APPROVED** [review]
looks good to me

**Pull request merged**
