### PR TITLE
[NUI] Fix failed & block & crash TCs of NUI.Devel(API10).

### PR DESCRIPTION
**Pull request by AchoWang**
### Description of Change ###
1. TCs failed in public/Theme, because lack of resource file.
2. Optimize some cases to fix block and crash issues.

### API Changes ###

 - ACR:

### CODE REVIEW

**Review by zg2nets — COMMENTED** [review]
lgtm

**Review by zg2nets — APPROVED** [review]

**Comment by xuelian-bai** [comment]
looks good to me

**Review by AdunFang — APPROVED** [review]
It is OK.

**Review by elishateng — APPROVED** [review]
LGTM

**Review by zhouleonlei — APPROVED** [review]
LGTM

**Review by dongsug-song — APPROVED** [review]
looks good to me

**Pull request merged**
