### PR TITLE
[NUI][XamlBuild] Remove the reference of Tizen.NUI.XamlBuild in NUITizenGallery

### PR DESCRIPTION
**Pull request by AdunFang**
### Description of Change ###
1. Remove the reference of Tizen.NUI.XamlBuild in NUITizenGallery.
2. Fix issue of Array.

### API Changes ###

 - ACR:

### CODE REVIEW

**Comment by xuelian-bai** [comment]
looks good to me

**Review by elishateng — APPROVED** [review]
LGTM

**Review by huayongxu — APPROVED** [review]
lgtm

**Review by zhouleonlei — APPROVED** [review]
lgtm

**Comment by dongsug-song** [comment]
@AdunFang 
Hello, 
could you upload this patch on DevelNUI also?

**Review by dongsug-song — APPROVED** [review]
looks good to me
please upload same patch on DevelNUI also.
thank you.

**Pull request merged**
