### PR TITLE
[NUI] Add TCs for NUI.Components.Devel.

### PR DESCRIPTION
**Pull request by AchoWang**
### Description of Change ###

Add testcases to improve line coverage rate of Tizen.NUI.Components.

### API Changes ###

 - ACR:

### CODE REVIEW

**Review by dongsug-song — APPROVED** [review]
looks good to me

**Review by huayongxu — COMMENTED** [review]
lgtm

**Review by zhouleonlei — COMMENTED** [review]
LGTM

**Comment by wb0716** [comment]
Good for me

**Review by wb0716 — COMMENTED** [review]
Good  for me

**Review by zg2nets — COMMENTED** [review]
lgtm

**Pull request merged**
