### PR TITLE
[NUI] Fix CA1066

### PR DESCRIPTION
**Pull request by dkdk-ryu**
CA1066:Implement IEquatable when overriding Equals

### API Changes ###

 - ACR:

### CODE REVIEW

**Comment by Seoyeon2Kim** [comment]
Dear @AdunFang  and @bshsqa ,
This PR is related to XmlName and LayoutLength. Could you check them?

**Comment by dongsug-song** [comment]
@m-macias 
Hello,
I have question about TCSACR for derived class's structural change.
could you check the class below changed in this PR?

public struct LayoutLength : IEquatable<LayoutLength>

that is public API and it is changed newly as inheriting IEquatable<T>.
in this case, TCSACR is required even though TizenAPI-bot has checked nothing ?
could you answer for us?
thank you.

**Comment by huiyueun** [comment]
looks good to me

**Comment by m-macias** [comment]
@dongsug-song ,
The addition of the interface changes the public API and would require a new ACR, however in this case those methods (i.e. Equals(...)) were already implemented so there is no real value for the TCSACR process. Additionally, currently those changes are targeting the DevelNUI branch which is not supported by the TCSACR process.

Thank you

**Review by dongsug-song — APPROVED** [review]
looks good to me

**Pull request merged**
