### PR TITLE
[NUI] Add xaml & xamlbinding testcases

### PR DESCRIPTION
**Pull request by elishateng**
### Description of Change ###

1. Add xaml & xamlbinding testcases

### API Changes ###

 - ACR:

### CODE REVIEW

**Review by zhouleonlei — APPROVED** [review]
LGTM

**Review by huayongxu — COMMENTED** [review]
lgtm

**Review by zg2nets — APPROVED** [review]
lgtm

**Review by dongsug-song — APPROVED** [review]
internal test case

**Pull request merged**
