### PR TITLE
[NUI] Add VerticalAlignment in TextEditor

### PR DESCRIPTION
**Pull request by wonrst**
editor.VerticalAlignment = VerticalAlignment.Top;
editor.VerticalAlignment = VerticalAlignment.Center;
editor.VerticalAlignment = VerticalAlignment.Bottom;

dali patches:
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-toolkit/+/273039/
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/273582/

Signed-off-by: Bowon Ryu <bowon.ryu@samsung.com>

### CODE REVIEW

**Review by Seoyeon2Kim — APPROVED** [review]
LGTM!

**Review by jaehyun0cho — APPROVED** [review]
LGTM

**Review by hinohie — APPROVED** [review]
Internal dali codes already merged. we can merge it now

**Review by everLEEst — APPROVED** [review]
Looks good to me.

**Pull request merged**
