### PR TITLE
[NUI] Make bindable properties in Style and View have same name and etc.

### PR DESCRIPTION
**Pull request by rabbitfor**
Signed-off-by: Jiyun Yang <ji.yang@samsung.com>

### Description of Change ###
* Remove TextFieldStyle's Selector.

### API Changes ###

 - ACR:

### CODE REVIEW

**Comment by dongsug-song** [comment]
@rabbitfor 
Thank you for big patch.
could you explain about this briefly?

**Review by everLEEst — COMMENTED** [review]
Thank you for this update.
I was also thinking it is weird that property on View is normally string or color or url and Style is Selector.
It looks good to me!
only one tiny worry. Changing style is not breaking any backward compatibility yet?

**Comment by rabbitfor** [comment]
> Thank you for this update.
> I was also thinking it is weird that property on View is normally string or color or url and Style is Selector.
> It looks good to me!
> only one tiny worry. Changing style is not breaking any backward compatibility yet?

Style is not open yet (Non ACR API). So I think it is OK to change.

**Comment by rabbitfor** [comment]
> @rabbitfor
> Thank you for big patch.
> could you explain about this briefly?

Regarding NUI `View`, there were 2 problems related with bindable properties.
1. Some APIs do not have same logic with its bindable property. For example, `Color`, `BackgroundColor` and etc. This leads to the wrong result when the user sets a value through the bindable property.
2. `Style` class should have same set of bindable properties with corresponding `View`, but some properties have different names. For example, View.BackgroundColorProperty and ViewStyle.BackgroundColorSelectorProperty. It looks weird and make it hard to understand.


This patch tries to fix them.
Note that, regarding problem 1, this patch fix only part of it.

**Comment by dongsug-song** [comment]
@rabbitfor 
Thank you for detailed explanation. 
I will merge this after the conflict is resolved. (please check the below error) 
thank you.

**Review by dongsug-song — APPROVED** [review]
looks good to me

**Pull request merged**
