### PR TITLE
[NUI] Fix build error of Devel.NUI.Tests

### PR DESCRIPTION
**Pull request by AchoWang**
### Description of Change ###
Application.AddResourceChangedCallback was removed , so remove related TCs.

### API Changes ###

 - ACR:

### CODE REVIEW

**Review by huayongxu — APPROVED** [review]
lgtm

**Review by wb0716 — APPROVED** [review]
Good for me

**Review by zhouleonlei — APPROVED** [review]
LGTM

**Review by zg2nets — APPROVED** [review]
looks good！

**Review by elishateng — APPROVED** [review]
LGTM

**Review by dongsug-song — APPROVED** [review]
looks good to me

**Pull request merged**
