### PR TITLE
[NUI] Fix svace issue

### PR DESCRIPTION
**Pull request by zhouleonlei**
### Description of Change ###

https://analysishub.sec.samsung.net/dm/sr03/sb2/main/review#PRJID=124&WGID=7576
https://analysishub.sec.samsung.net/dm/sr03/sb2/main/review#PRJID=124&WGID=7578

### API Changes ###

 - ACR:

### CODE REVIEW

**Review by xuelian-bai — APPROVED** [review]
looks good to me

**Review by AdunFang — APPROVED** [review]
It is OK.

**Review by AchoWang — APPROVED** [review]
Looks good to me.

**Review by dongsug-song — APPROVED** [review]
looks good to me

**Review by wb0716 — COMMENTED** [review]
Good for me

**Pull request merged**
