### PR TITLE
[NUI][Xaml] Change default value of XamlOptimization to 1 (use injection)

### PR DESCRIPTION
**Pull request by AdunFang**
…ion)

### API Changes ###

 - ACR:

### CODE REVIEW

**Review by xiaowei-guan — APPROVED** [review]
LGTM

**Review by wb0716 — APPROVED** [review]
Good for me

**Review by zg2nets — APPROVED** [review]
looks good

**Review by zhouleonlei — APPROVED** [review]
lgtm

**Review by wanchao-xu — APPROVED** [review]
Looks good to me

**Review by elishateng — APPROVED** [review]
LGTM

**Review by dongsug-song — APPROVED** [review]
approve

**Review by AdunFang — COMMENTED** [review]
It is OK.

**Pull request merged**
