### PR TITLE
[NUI] Add TCs for Public Events

### PR DESCRIPTION
**Pull request by zhouleonlei**
### Description of Change ###
Add TCs for Public Events

### API Changes ###

 - ACR:

### CODE REVIEW

**Review by huayongxu — APPROVED** [review]
lgtm

**Review by AdunFang — APPROVED** [review]
It is OK.

**Review by huiyueun — APPROVED** [review]
LGTM

**Review by elishateng — APPROVED** [review]
LGTM

**Review by zg2nets — APPROVED** [review]
gltm

**Pull request merged**
