### PR TITLE
[NUI][Tizen.NUI.Extension] Introduce DrawingCanvasView

### PR DESCRIPTION
**Pull request by patrykka**
Change-Id: I3967fee0e4322d645deb15d19796ceaf00c3f8cb

### API Changes ###

 - ACR:

### CODE REVIEW

**Comment by patrykka** [comment]
continue work from https://github.com/Samsung/TizenFX/pull/5258

**Comment by dongsug-song** [comment]
@patrykka 
While merging the DevelNUI branch into master branch, something became a problem and there was no choice but to do hard-reset.
I'm sorry for the inconvenience, but now you have to rebase or re-create your patch and submit it again.

**Comment by patrykka** [comment]
@dongsug-song Patch rebased

**Comment by dongsug-song** [comment]
The TizenFX master branch has been changed for API12(tizen_9.0).
So the DevelNUI branch also did a hard reset with the master branch to sync this.
I think you need to rebase this PR or re-upload the new PR.
I am sorry for the inconvenience.

**Comment by sung-su** [comment]
Hello @patrykka ,
Is there a design document for `DrawingCanvasView`?

**Pull request closed without merging**
