### PR TITLE
[NUI] Add a LoadContents API with byte array for WebView.

### PR DESCRIPTION
**Pull request by huayongxu**
### Description of Change ###

Related patch at csharp-binder:
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/290848/

### API Changes ###

 - ACR:

### CODE REVIEW

**Review by dongsug-song — APPROVED** [review]
approved

**Review by wanchao-xu — APPROVED** [review]
Loos good to me

**Review by xuelian-bai — APPROVED** [review]
looks good to me

**Review by wb0716 — APPROVED** [review]
Good for me

**Review by zg2nets — APPROVED** [review]
looks good~

**Pull request merged**
