### PR TITLE
[NUI][Xaml] Support Dictionary which has string key in Xaml

### PR DESCRIPTION
**Pull request by AdunFang**
### Description of Change ###

Support Dictionary which has string key in Xaml,
sample is:

```
<?xml version="1.0" encoding="UTF-8" ?>
<View x:Class="NUITizenGallery.SetPropertySample"
  xmlns="http://tizen.org/Tizen.NUI/2018/XAML"
  xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
  xmlns:l="clr-namespace:NUITizenGallery;"
  xmlns:scg="clr-namespace:System.Collections.Generic;assembly=mscorlib"
  BackgroundColor = "Cyan" SizeWidth="1920" SizeHeight="1080">

    <l:CustomButton>
        <l:CustomButton.ItemDividerPropertyMap> <!--ItemDividerPropertyMap is a Dictionary-->
            <scg:Dictionary x:TypeArguments="x:String,x:Object">
                <x:Int32 x:Key="key0">11</x:Int32>
                <x:Int32 x:Key="key1">111</x:Int32>
                <x:Int32 x:Key="key2">222</x:Int32>
            </scg:Dictionary>
        </l:CustomButton.ItemDividerPropertyMap>
    </l:CustomButton>
</View>
```

### API Changes ###

 - ACR:

### CODE REVIEW

**Comment by xuelian-bai** [comment]
looks good to me

**Review by wb0716 — APPROVED** [review]
Good for me

**Review by zg2nets — APPROVED** [review]
lgtm

**Review by elishateng — APPROVED** [review]
LGTM

**Review by dongsug-song — APPROVED** [review]
approved

**Review by huayongxu — COMMENTED** [review]
lgtm

**Pull request merged**
