### PR TITLE
Make sure scrollable shadow is shown only when scrolled vertically

### PR DESCRIPTION
**Pull request by huayongxu**
When the scrollable is scrolled horizontally, a background image
is shown accidentally.
This patch adds a check that scrollable shadow is shown only when
scrolled vertically, and adds a test case for ScrollableBase.

### API Changes ###

 - ACR:

### CODE REVIEW

**Comment by huayongxu** [comment]
the branch is not correct. so I close this PR.

**Review by AchoWang — APPROVED** [review]
Looks good to me.

**Review by dongsug-song — APPROVED** [review]
looks good to me

**Review by AdunFang — COMMENTED** [review]
It is OK.

**Pull request merged**
