### PR TITLE
[Build] Modify the TFM list set in vconf

### PR DESCRIPTION
**Pull request by JongHeonChoi**
### API Changes ###

 - ACR:

### CODE REVIEW

**Review by WonyoungChoi — APPROVED** [review]

**Comment by WonyoungChoi** [comment]
@JongHeonChoi  Please check https://github.com/Samsung/TizenFX/blob/9d0ed3e615638942e0940d52ac2b008637607495/packaging/500.tizenfx_upgrade.sh#L8 also. It is used in FOTA process.

**Review by flyofsky — APPROVED** [review]

**Review by flyofsky — APPROVED** [review]

**Review by sung-su — APPROVED** [review]

**Review by JoonghyunCho — APPROVED** [review]

**Comment by flyofsky** [comment]
LGTM

**Review by clamp03 — APPROVED** [review]

**Comment by JongHeonChoi** [comment]
Is this PR possible to merge?

**Comment by WonyoungChoi** [comment]
@JongHeonChoi I will merge after rebase it.

**Pull request merged**
