### PR TITLE
[NUI] Add left/right shadow effect for the scrollablebase.

### PR DESCRIPTION
**Pull request by huayongxu**
This patch is to implement left/right shadow effect for the
scrollablebase.

### API Changes ###

 - ACR:

### CODE REVIEW

**Review by elishateng — APPROVED** [review]
LGTM

**Review by AchoWang — APPROVED** [review]
Looks good to me.

**Comment by dongsug-song** [comment]
@huayongxu 
Hello, could you resolve conflicts and get review from Mr. @bshsqa ?
This is related to ScrollableBase which is used a lot in DA, so we check and review carefully.
@bshsqa 
Hello,
could you review this which is about ScrollableBase 's shadow effect animation?
thank you.

**Comment by huayongxu** [comment]
> @huayongxu
> Hello, could you resolve conflicts and get review from Mr. @bshsqa ?
> This is related to ScrollableBase which is used a lot in DA, so we check and review carefully.
> @bshsqa
> Hello,
> could you review this which is about ScrollableBase 's shadow effect animation?
> thank you.

I rebased and uploaded the patch.
Please take a look.
Thank you.

**Review by zhouleonlei — APPROVED** [review]
LGTM

**Review by AdunFang — APPROVED** [review]
It is OK.

**Pull request merged**
