### PR TITLE
[NUI][NUI.Devel] Update line coverage TCs of NUI.Devel.

### PR DESCRIPTION
**Pull request by AchoWang**
### Description of Change ###
Update TCs following latest nui codes.

### API Changes ###

 - ACR:

### CODE REVIEW

**Review by wb0716 — APPROVED** [review]
Good for me

**Review by zg2nets — APPROVED** [review]
lgtm

**Review by huayongxu — APPROVED** [review]
lgtm

**Review by zhouleonlei — APPROVED** [review]
lgtm

**Review by elishateng — APPROVED** [review]
LGTM

**Review by dongsug-song — APPROVED** [review]
approve

**Pull request merged**
