### PR TITLE
[NUI] Fix issue that BindingContext can't be used in C# code

### PR DESCRIPTION
**Pull request by AdunFang**
### API Changes ###

 - ACR:

### CODE REVIEW

**Review by myroot — CHANGES_REQUESTED** [review]
The original implement of `BindableObject` is support a chain of BindingContext between parent and descendant. 
I think, you do better to fix it to work rather than this PR. 

As I search, 
https://github.com/Samsung/TizenFX/blob/6405fb6c273725b83ad82ad5e237bd109b314f6b/src/Tizen.NUI/src/public/XamlBinding/Element.cs#L324-L349
This code propagate `BindingContext` to descendant, but Any NUI classes are not override `LogicalChildrenInternal` so `BindingContext` could not propagate to child

**Comment by WonyoungChoi** [comment]
@AdunFang please rebase this RP with master branch first

**Comment by dongsug-song** [comment]
@AdunFang 
Hello, could check the review comments and resolve the conflict?

I put the **\*\*NO MERGE\*\*** label on this PR now.
**You can remove this label for yourself when this PR is ready to be reviewed and merged.**
(**\*\*NO MERGE\*\*** label has no restriction to submit PR or to edit this patch. Just for notification and marking)
Thank you.

**Comment by dongsug-song** [comment]
@AdunFang 
Hello, Mr. Fang, as I know, the related issue has been resolved, so I think it would be OK to close this PR for now.
If you want to make this PR be reviewed, please re-open and resolve conflicts. OR please upload new PR again.
Thank you.

**Pull request closed without merging**
