### PR TITLE
[XamlBuild] Add XamlOptimization to use xaml/injection/examl

### PR DESCRIPTION
**Pull request by elishateng**
### Description of Change ###

1. Add XamlOptimization to use xaml/injection/examl. If this patch included in target, then NeedInjection can be replaced by XamlOptimization.

Usage:
\<XamlOptimization>0\</XamlOptimization>  //Use Xaml
\<XamlOptimization>1\</XamlOptimization> //Use Injection
\<XamlOptimization>2\</XamlOptimization> //Use EXaml.

Note: NeedInjection is still in maintain, but it will be deprecated later. Default we use EXaml, so XamlOptimization default is 2.

### API Changes ###

 - ACR:  None (It won't affect previously function)

### CODE REVIEW

**Review by wb0716 — APPROVED** [review]
Good for me

**Review by AdunFang — APPROVED** [review]
It is OK.

**Review by huayongxu — APPROVED** [review]
lgtm

**Review by zhouleonlei — APPROVED** [review]
lgtm

**Review by zg2nets — APPROVED** [review]
lgtm

**Review by AchoWang — APPROVED** [review]
Looks good to me.

**Review by everLEEst — COMMENTED** [review]
whole idea looks good.
is it possible to support EXAML, or INJECTION as type not int value?

**Comment by elishateng** [comment]
> 

It's also possible. But we afraid it is not easy to change or spell it.

**Comment by elishateng** [comment]
> whole idea looks good. is it possible to support EXAML, or INJECTION as type not int value?

It's also possible. But we afraid it is not easy to change or spell it.

**Comment by dongsug-song** [comment]
@elishateng 
Hello, Mr. Teng
this can't be accepted, because it violate the backward compatibility.
please maintain "NeedInjection" and add the new options.
also 0,1, 2 is not good. please use meaningful word.
thank you.

**Comment by elishateng** [comment]
> @elishateng Hello, Mr. Teng this can't be accepted, because it violate the backward compatibility. please maintain "NeedInjection" and add the new options. also 0,1, 2 is not good. please use meaningful word. thank you.

Hi, Mr. SSong, I talked with Mr. Fang, he said it is not easy to change or spell it, and also we may has other values later to speed xaml more.

**Review by dongsug-song — APPROVED** [review]
looks good to me

**Pull request merged**
