### PR TITLE
[NUI] Modify svace issues for NUI and wearable

### PR DESCRIPTION
**Pull request by zhouleonlei**
### Description of Change ###
Modify svace issues for NUI and wearable

### API Changes ###

 - ACR:

### CODE REVIEW

**Review by elishateng — APPROVED** [review]
LGTM

**Review by wb0716 — APPROVED** [review]
Good for me.

**Review by AchoWang — APPROVED** [review]
Looks good to me.

**Review by huayongxu — APPROVED** [review]
lgtm.

**Review by zg2nets — APPROVED** [review]
good ！

**Review by huiyueun — APPROVED** [review]
LGTM

**Review by AdunFang — APPROVED** [review]
It is OK.

**Review by rabbitfor — APPROVED** [review]
LGTM

**Pull request merged**
