### PR TITLE
[NUI] Apply xaml loaded event for NUIApplication

### PR DESCRIPTION
**Pull request by elishateng**
### Description of Change ###

1. Add XamlLoaded event for NUIApplication
2. Add Xaml line info for bindable object

These changes to make beholder more useful.
This patch include the changes of the following patches:
https://github.com/Samsung/TizenFX/pull/3790 (merged in DevelNUI)
https://github.com/Samsung/TizenFX/pull/3808 (merged in DevelNUI)
https://github.com/Samsung/TizenFX/pull/3824 (merged in DevelNUI)

### API Changes ###

 - ACR: None (It won't affect previously function)

### CODE REVIEW

**Review by wb0716 — APPROVED** [review]
Good for me

**Review by AdunFang — APPROVED** [review]
It is OK.

**Review by huayongxu — APPROVED** [review]
lgtm

**Comment by xuelian-bai** [comment]
looks good to me

**Review by zhouleonlei — APPROVED** [review]
lgtm

**Review by AchoWang — APPROVED** [review]
Looks good to me.

**Review by huayongxu — APPROVED** [review]
lgtm

**Review by dongsug-song — APPROVED** [review]
looks good to me

**Pull request merged**
