### PR TITLE
[NUI] Fix CA2000 Warnings

### PR DESCRIPTION
**Pull request by zhouleonlei**
### Description of Change ###
Fix CA2000 Warnings

### API Changes ###

 - ACR:

### CODE REVIEW

**Review by huayongxu — APPROVED** [review]
lgtm.

**Review by AdunFang — APPROVED** [review]
It is OK.

**Review by elishateng — APPROVED** [review]
LGTM

**Review by AchoWang — APPROVED** [review]
Looks good to me.

**Comment by rabbitfor** [comment]
I am sorry to revert this.
In my opinion, storing signal as a field just for removing warnings is redundant.
For now, I think it'd better to suppress warnings for the signals.
We need to find better way after then.

**Pull request merged**
