### PR TITLE
Add ViewProperty and EXaml(public) TCs.

### PR DESCRIPTION
**Pull request by AchoWang**
### Description of Change ###
Add ViewProperty and EXaml(public) TCs.

### API Changes ###

 - ACR:

### CODE REVIEW

**Review by elishateng — APPROVED** [review]
LGTM

**Review by wb0716 — APPROVED** [review]

**Review by zhouleonlei — APPROVED** [review]
LGTM

**Review by AdunFang — APPROVED** [review]
It is OK.

**Review by huayongxu — APPROVED** [review]
lgtm.

**Review by dongsug-song — APPROVED** [review]
looks good to me

**Pull request merged**
