### PR TITLE
[NUI] Fix ObjectDump can't output logs

### PR DESCRIPTION
**Pull request by elishateng**
### Description of Change ###

1. Fix ObjectDump can't output logs

### API Changes ###

 - ACR:

### CODE REVIEW

**Review by huayongxu — APPROVED** [review]
lgtm.

**Review by zhouleonlei — APPROVED** [review]
LGTM

**Review by AchoWang — APPROVED** [review]
Looks good to me.

**Review by AdunFang — APPROVED** [review]
It is OK.

**Pull request merged**
