### PR TITLE
[NUI] Deprecated PropertySet event and fix some properties can't fire PropertyChanged issue

### PR DESCRIPTION
**Pull request by elishateng**
### Description of Change ###

1. Deprecated PropertySet event 
2. Fix some properties can't fire PropertyChanged issue

### API Changes ###

 - ACR:

### CODE REVIEW

**Comment by dongsug-song** [comment]
@elishateng 
Hello, could you check the conflict and "ACR Required" tag?

@neostom432 
Hello, this patch changes the Layout property. could you review this?
Layout => LayoutProperty => UpdateLayout() 

Thank you.

**Review by AdunFang — APPROVED** [review]
It is OK.

**Comment by dongsug-song** [comment]
@elishateng 
Hello, 
Could you please check again?
It has not been updated for a long time and it has "ACR Required" tag.
Also, code conflict needs be solved.
Thank you.

**Comment by dongsug-song** [comment]
@elishateng
Hello,
Could you please check again?
It has not been updated for a long time and it has "ACR Required" tag.
Also, code conflict needs be solved.
**OR if this PR is not valid anymore, please close quickly.**
Thank you.

**Comment by elishateng** [comment]
Hello, Mr. SSong, Sorry for late response. As we talked in message, I'll repush it in API9. Now I close it first.

**Comment by elishateng** [comment]
This is for https://github.com/Samsung/TizenFX/issues/1740.

**Pull request closed without merging**
