### PR TITLE
[NUI] Change IsCreateByXaml to virtual

### PR DESCRIPTION
**Pull request by AdunFang**
### API Changes ###

 - ACR:

### CODE REVIEW

**Review by wanchao-xu — APPROVED** [review]
Looks good to me

**Review by xuelian-bai — APPROVED** [review]
looks good to me

**Review by xiaowei-guan — APPROVED** [review]
LGTM

**Review by zg2nets — APPROVED** [review]
lgtm

**Review by AchoWang — APPROVED** [review]
Looks good to me.

**Review by zhouleonlei — APPROVED** [review]
lgtm

**Review by everLEEst — APPROVED** [review]
LGTM but please be careful to check this may cause any compatibilty problem.

**Pull request merged**
