### PR TITLE
[NUI] Add object dump function

### PR DESCRIPTION
**Pull request by elishateng**
### Description of Change ###

1. Add ojbect dump fucntion for NUI.
2. Call clear backgound when setting Backgound.

### API Changes ###

 - ACR:

### CODE REVIEW

**Comment by dongsug-song** [comment]
@elishateng 
Hello,
I am sorry for late review...
could you explain what object dump is for and how it can be operated?
could you add some sample code here?
thank you.

**Comment by elishateng** [comment]
> @elishateng
> Hello,
> I am sorry for late review...
> could you explain what object dump is for and how it can be operated?
> could you add some sample code here?
> (also merge conflict should be resolved)
> thank you.

Hello, Mr. SSong,
In order to debug easily, we want to add object dump api to print necessary infos.
For example, we want to see if the properties of a view are set correctly, we can call its objectdump api.

**Comment by dongsug-song** [comment]
@elishateng 
Hello,
OK, I see, then please fix merge conflict.

**Comment by elishateng** [comment]
> @elishateng
> Hello,
> OK, I see, then please fix merge conflict.

Hello, Mr. SSong,
I've update PR, please review it again.

**Comment by dongsug-song** [comment]
@elishateng 
Hello, thank for updating. I will merge.
but from next time, please add sample app or sample code to show how it can be used.

ex )  https://github.com/Samsung/TizenFX/pull/1469/files
test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/VisibilityChangedTest.cs

thank you.

**Comment by elishateng** [comment]
> @elishateng
> Hello, thank for updating. I will merge.
> but from next time, please add sample app or sample code to show how it can be used.
> 
> ex ) https://github.com/Samsung/TizenFX/pull/1469/files
> test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/VisibilityChangedTest.cs
> 
> thank you.

Thank you, Mr. SSong. I got it.

**Review by AdunFang — COMMENTED** [review]
It is OK.

**Pull request merged**
